### ISSUE TITLE
promotion window should capture mouse

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2692] opened 2016-10-20 07:18 UTC
an old gripe ... with these small changes to the unit panel, it will capture the mouse, that is it will work even if a unit is hidden below. which it currently doesn't.

[WorldView.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/541008/WorldView.zip)

is it possible to include this (the EUI version at least)? original unmodified files are under  assets\DLC\Expansion2\UI\InGame\WorldView

**Comment by LoneGazebo** [comment] 2016-10-20 15:18
Is it the promotion buttons that break?

**Comment by ilteroi** [comment] 2016-10-20 17:43
yep. this annoys me no end

**Comment by ilteroi** [comment] 2016-10-30 10:51
still not good

**Comment by LoneGazebo** [comment] 2016-10-30 15:16
I thought I merged. Will look.

**Comment by LoneGazebo** [comment] 2016-10-30 23:47
@Iamblichos mind taking this on? A little UI work seems fun, eh? :)

**Comment by Iamblichos** [comment] 2016-10-31 00:34
I'm on it.

**Comment by Iamblichos** [comment] 2016-10-31 19:04
FYI...this is a non-issue in the vanilla game, because it's coded right in the Unitpanel.lua.....are you guys using EUI, can you confirm in non-EUI?

**Comment by LoneGazebo** [comment] 2016-10-31 19:18
It is an EUI issue yep.

**Comment by Iamblichos** [comment] 2016-10-31 19:22
well I can already tell you that the problem is that he has the LuaEvents that are set to hide the enemyunitpanel wrapped up into the Events.SequenceGameInitComplete function...so it isn't going to fire since that function only fires on game load.

**Comment by Iamblichos** [comment] 2016-10-31 19:23
I'm implementing a work around...

**Comment by Iamblichos** [comment] 2016-11-01 00:56
Alright none of my attempts worked. There's something wrong with his code, and I'm not exactly sure how to fix it without doing a major rewrite of it (which in its current condition is a big mess and not worth it).

**Comment by Iamblichos** [comment] 2016-11-01 16:53
The way I see it is, is that this is a basic EUI problem, meaning if you use this with the vanilla game and EUI, you will have the problem.

**Comment by LoneGazebo** [comment] 2016-11-01 16:56
Yeah. And bc1 is awol. Unfortunately @ilteroi not sure we can fix this. :)

**Comment by ilteroi** [comment] 2016-11-01 19:46
hmm. so you're saying the fix works only in the non-EUI version? that's a shame

**Comment by Iamblichos** [comment] 2016-11-01 19:51
Not quite, I'm saying there is nothing to fix in the non-EUI version because the Unitpanel.lua is coded right by firaxis to hide the EnemyUnitPanel.lua upon them sharing space.

**Comment by ilteroi** [comment] 2016-11-01 20:47
hmm. but i do remember that changing this ConsumeMouse property from 0 to 1 solved the problem .... maybe i mixed up EUI and non-EUI?

**Comment by Iamblichos** [comment] 2016-11-01 21:42
It might help with non-EUI, but I'm not sure why it should, since the Unitpanel.lua of the NON-EUI changes little if anything. The consume shouldn't have anything to do with it, because this bit of code is what handles it:

```
function ShowHideHandler( bIshide, bIsInit )
    if( bIshide ) then
        local EnemyUnitPanel = ContextPtr:LookUpControl( "/InGame/WorldView/EnemyUnitPanel" );
        if( EnemyUnitPanel ~= nil ) then
            EnemyUnitPanel:SetHide( true );
        end
    end
end
ContextPtr:SetShowHideHandler( ShowHideHandler );

function OnEnemyPanelHide( bIsEnemyPanelHide )
    if( g_bWorkerActionPanelOpen ) then
        Controls.WorkerActionPanel:SetHide( not bIsEnemyPanelHide );
    end
end
LuaEvents.EnemyPanelHide.Add( OnEnemyPanelHide );
```

**Comment by Iamblichos** [comment] 2016-11-01 22:24
See the problem also is, is that if you put the NON-EUI files into the CP (Unitpanel.lua, and your fixes to the *.xml files above), and then also delete the Unitpanel folder in the UI_bc1 folder (so that for example you want to use all of the EUI benefits without the EUI unitpanel changes), it still doesn't work. He's got some fundamental problem within the core EUI that's preventing the Enemyunitpanel from hiding correctly as it should.

**Comment by ilteroi** [comment] 2016-11-01 22:45
but here's the thing - in my mind, the enemy unit panel shouldn't even be triggered if the mouse event is correctly captured by the (friendly) unit panel which is "on top" of the enemy unit.

but then, i don't have a clue about this ...

**Comment by Iamblichos** [comment] 2016-11-01 22:48
It shouldn't...but he's got something messed up. I tried editing the EUI files for those .xml files using your method of above, even tried a work around for recalling that function to hide. No attempt I tried worked which lead me to believe there's a more fundamental problem with it. That code, I believe is not made correctly.

**Comment by ilteroi** [comment] 2016-11-02 07:04
ok - i give in :)

**Comment by Iamblichos** [comment] 2016-11-07 15:23
Close out or do we want to rewrite EUI? ;)~

**Comment by LoneGazebo** [comment] 2016-11-07 15:43
Let's close. Bigger fish and all that.

**Closed by LoneGazebo** 2016-11-07 15:43 UTC
Labels: Not going to fix, The Iamblichos Initiative
