### ISSUE TITLE
Game not counting resources correctly

### ISSUE THREAD

**Issue by Zanteogo** [LoneGazebo/Community-Patch-DLL#6826] opened 2020-07-21 19:22 UTC
_1. Mod version (i.e Date - 6/19):_ 
6-19-2 + recursive's posted updates 

_2. Mod list (if using Vox Populi only, leave blank):_ 
R.E.D. - Smaller Landmarks (v.5)
R.ED. Modpack (v. 27)

_3. Error description:_ 
Game not adding strategic resources resources correctly

_4. Steps to reproduce (optional):_
Seems to happen randomly

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
http://s000.tinyupload.com/?file_id=59478867251833524610

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
https://ibb.co/C1LVq5K

**Comment by RecursiveVision** [comment] 2020-07-21 19:35
Duplicate of #6821

**Closed** 2020-08-06 16:32 UTC
Labels: Fixed for upcoming version
