### ISSUE TITLE
No railroad bonus for harbor (1-23)

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1174] opened 2016-01-29 01:35 UTC
![2016-01-28_00001](https://cloud.githubusercontent.com/assets/11132095/12664521/cc96c76e-c5f5-11e5-9ddc-39b5f124a128.jpg)

I meet all the requirements, harbor in city/connection with capital, discovered railroad, on separate landmass. No idea why I'm not getting the production bonus, unless the requirements were changed in the CBP (if so, apologies). Save and logs attached (this is the 1-23 version, full CPP w/ EUI).

[Railroad bonus.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/109159/Railroad.bonus.zip)

**Comment by joosegoose** [comment] 2016-01-29 04:59
Update...checked back later in the game and am now getting the bonus. Don't know what could have changed between now and then.

**Comment by LoneGazebo** [comment] 2016-01-29 05:16
I think at least one other city has to have started the railroad connection for it to count.
G

**Comment by joosegoose** [comment] 2016-01-29 05:18
I had that, though. Almost all of my cities on the mainland had railroad connections, including my coastal cities with harbors.

**Comment by LoneGazebo** [comment] 2016-01-29 16:34
Weird.

**Comment by LoneGazebo** [comment] 2016-01-29 19:46
Ilteroi, this and the random loss of city connection status for happiness (i.e. sudden isolation unhappiness) makes me think that the blockade code might be a little buggy. Any thoughts?

**Comment by ilteroi** [comment] 2016-01-30 11:20
i just added some logs to check this, but i don't see what could be the problem yet

**Comment by Der-Zorn-Gottes** [comment] 2016-02-01 07:37
"I think at least one other city has to have started the railroad connection for it to count."

I had an eye on this in my current archipelago game. 
I didn`t build a single road on my starting island, let alone a railroad.
Still all my cities with harbors got the bonus once I discovered railroads.

**Comment by ilteroi** [comment] 2016-02-08 08:02
cannot reproduce this. savegame is outdated unfortunately. propose to close this and re-open if necessary

**Comment by LoneGazebo** [comment] 2016-02-08 15:07
Sounds good.

**Closed by LoneGazebo** 2016-02-08 15:07 UTC
Labels: Paging Dr. Ilteroi
