### ISSUE TITLE
Units disobey orders suddenly

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#2900] opened 2016-12-14 04:13 UTC
_1. Mod version (i.e Date - 4/23):_
12-13

_2. Mod list (if using Vox Populi only, leave blank):_
Thal's Promotion
Unique Cultural Influence
JFD's cultural diversity (core + soundtrack)

_3. Error description:_ 
My units disobey orders suddenly. All units spent all their movement at the beginning of turn. Fortified units remain there and moving units move around the map.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

Saves before bugs happen and the last turn I have played.
[Log and Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/650779/Log.and.Save.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ricanuck** [comment] 2016-12-14 04:24
Jesus, G, I told you to stop improving this!

Now you have created Skynet.

**Comment by LoneGazebo** [comment] 2016-12-14 05:36
@ricanuck we did it.

@ilteroi possible issue with homeland AI recruitment change you made?

**Comment by ilteroi** [comment] 2016-12-14 07:06
ah? cannot reproduce here, but i don't have your latest code, g

**Comment by TechpriestEnginseer** [comment] 2016-12-14 09:34
Yeah this is ridiculous, workers are being automated despite me telling them to go to sleep.

**Comment by 8h42** [comment] 2016-12-14 10:48
Automation commands such as "Explore" and "Build improvements" cause this issue.

Active Mods:
VP + EUI

**Comment by XplosiveLun** [comment] 2016-12-14 11:21
@8h42
That isn't my cause though what is the cause. Strangely, a few turns after negotiating with England, I rearrange my soldiers and then suddenly that happens

**Comment by RockettSJ** [comment] 2016-12-14 15:48
Just throwing it out there that I have the same problem. When I set a scout to auto explore, all my other units (boats, workers, warriors) etc done the same

**Comment by ricanuck** [comment] 2016-12-14 18:00
They will be back.

Seriously, I didn't have the time to test this, but I wouldn't be able to reproduce it anyways as I never automate anything... I didn't even imagined that people would do that. A true civ player does not automate. ;)

**Comment by RockettSJ** [comment] 2016-12-14 18:13
@ricanuck Thanks for the update. Do you think the hotfix will be savegame compatible? I don't want to continue this game if a fix is incoming

**Comment by ilteroi** [comment] 2016-12-14 18:18
ok - i think i got it

**Comment by ilteroi** [comment] 2016-12-14 18:31
try this 
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/652520/CvGameCore_Expansion2.zip)

i don't have gazebo's latest changes but it should be compatible with the 12/13 release.

**Comment by LoneGazebo** [comment] 2016-12-14 18:32
@RockettSJ it'll be savegame compatible. Push your fix @ilteroi to github and i'll merge and push to master.

**Comment by ricanuck** [comment] 2016-12-14 18:34
@RockettSJ , I was joking..."I will be back", remember? Skynet.

**Comment by ilteroi** [comment] 2016-12-14 19:31
the fix hasn't been verified yet but i'm pretty sure, cause it was a stupid mistake :)

anyway it's pushed

**Closed** 2016-12-14 20:42 UTC
Labels: Already fixed
