### ISSUE TITLE
patch release july 16th

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6812] opened 2020-07-16 21:58 UTC
with gazebo's continued absence it's time for a patch release ... can somebody link this on the forum?

(see below)

notes:

* replace the DLL in you mods/community patch folder with this one
	* goes on top of the 6/19 release
	* this patch breaks savegames!
* i'm including the PDB file. this should be placed next to the DLL. 
	* if anybody experiences a crash, please upload the callstack.log file!
* this is only my stuff, the diplo changes from recursive are not included
	* because they need database changes ...

changes:

* fixed disappearing air units
* civilians can always stack, combat units can not stack, independent of domain
	* if necessary we can make embarked combat units stronger
* improved AI tactical behavior
	* at least i hope so, need feedback
* major performance improvement
* max religion spread distance is now equal to trade distance
	* different for land/water, depending on buildings
	* on average pressure is higher than before now
* misc smaller bugfixes

**Comment by RecursiveVision** [comment] 2020-07-16 22:17
@ilteroi I posted it on the forum for you: https://forums.civfanatics.com/threads/new-official-version-june-19th-6-19.659579/page-25#post-15838563

**Comment by LoneGazebo** [comment] 2020-07-17 00:44
I wonder how the AI will handle the embark rules when they try to do a combined landing assault. @ilteroi you've tested for that?

**Comment by ilteroi** [comment] 2020-07-17 13:06
@RecursiveVision 👍
@LoneGazebo : are there any special rules you are alluding to? as far as i know everything works, otherwise i wouldn't have made it public. but then you never know ... welcome back anyway!

**Comment by RecursiveVision** [comment] 2020-07-17 16:00
@ilteroi Which branch did you use to create this build? #6813 (a merge error from when Gazebo merged the branches earlier) is preventing EUI leader information from displaying. I fixed the issue for next version, but I can release a build fixing the merge errors in the interim.

**Comment by dailyminerals** [comment] 2020-07-18 03:09
Will that next version be posted here or somewhere else?

**Comment by LoneGazebo** [comment] 2020-07-18 03:11
@ilteroi oh just talking about the volume of units that muster during a mixed invasion.

**Comment by RecursiveVision** [comment] 2020-07-18 15:06
@dailyminerals Here, and on the forums. Will fix today.

**Comment by RecursiveVision** [comment] 2020-07-18 15:52
@ilteroi Fix uploaded and posted on the forums. Savegame compatible with your patch above. https://forums.civfanatics.com/threads/new-official-version-june-19th-6-19.659579/page-26#post-15841668

Normal: 
[Normal.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4941929/Normal.zip)

43 Civs:
[43 Civs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4941930/43.Civs.zip)

Here is the code I used in case of any problems:
https://github.com/RecursiveVision/Community-Patch-DLL/commit/8849f4494b6c6b5de8c6bc0281ee776bc696af9a

Note that this code modifies the build to be compatible with the database files that were installed by Gazebo's 6-19 release executable - NOT the ones that are currently uploaded on the repository - although merging #merge-fix, if you do so, will still work with the repository's database files because it adds new functions without removing any.

Database and build files are all fixed in my pull request for next version.

**Comment by RecursiveVision** [comment] 2020-07-20 03:15
@ilteroi With G's return all my changes and all your pushed changes have been merged into the master branch, so I recreated ole for you if you wanna use it...also considering how many files I modified (including some you modified as well; I merged both of our changes) you may want to be working from the latest code.

**Comment by ilteroi** [comment] 2020-07-27 15:33
new build, july 27th

[CvGameCore_Expansion2_596ce0730.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4982875/CvGameCore_Expansion2_596ce0730.zip)

(link removed from original comment)

**Comment by RecursiveVision** [comment] 2020-07-28 01:59
Hey @ilteroi, unrelated but there's speculation on the forums that your account issues there are due to some kind of secret pact between Firaxis and CivFanatics - which seems ridiculous to me given that VP has five subforums and Gazebo is still there, and I said as much here: https://forums.civfanatics.com/threads/new-official-version-june-19th-6-19.659579/page-33#post-15855635

May help if you explained the issue you're having?

**Comment by azum4roll** [comment] 2020-07-28 02:39
I assume that's not savegame compatible?

**Comment by RecursiveVision** [comment] 2020-07-28 03:38
@azum4roll My fix is compatible with ilteroi's, ilteroi's is not compatible with 6-19-2.

**Comment by ilteroi** [comment] 2020-07-28 05:16
july 27 is not compatible.

re: civfanatics, i got a warning from google to change my password ... but that somehow didn't work so i'm stuck in limbo. never got any confirmation emails. tried contacting the admins but no answer. ran out of patience, can live without.

**Comment by bigcat88** [comment] 2020-07-28 05:58
Does statecraft issue with adding plain count of res present here or it is already fixed?

**Comment by yyEdge** [comment] 2020-07-28 14:59
Many thanks for fixing the air interception animation issue!

**Comment by RecursiveVision** [comment] 2020-07-28 15:20
@ilteroi I spoke to an admin on the forums and he responded regarding your account:

"I checked ilteroi's account and I see he is from Germany and uses gmx as an email provider. We have long standing issues with gmx blocking our emails as spam. I will reset his password and send him a temporary password via a conversation. The problem is, if he doesn't get it, I may have to relay it through someone else?

I also saw in the admin site a second account named ilteroi_the_second. I will try contacting him via conversation to see if it is indeed him."

**Comment by bigcat88** [comment] 2020-07-28 17:55
@ilteroi can you fix this pls? ))
https://github.com/LoneGazebo/Community-Patch-DLL/issues/6695

**Comment by ilteroi** [comment] 2020-07-28 18:43
@RecursiveVision : thanks for facilitating. i can create a new account with another email address if necessary.

@bigcat88 : i assume it's fixed already but not in my branch. and i'm afraid of merging because then i would need to do a full release, which i can't.

**Comment by RecursiveVision** [comment] 2020-07-28 18:55
@ilteroi To fix it you just need to comment out the three lines in CvPlayer.cpp that call getResourceFromCSAlliances. Which actually isn't fixed in master due to an oversight, so if you fix it in your branch, that'd work.

Re: Your account - no problem. The admin I contacted was **leif erikson**, so if you create a new account with a compatible email domain and contact that admin, they said they'll help you solve the issue.

https://forums.civfanatics.com/members/leif-erikson.26891/

**Comment by CppMaster** [comment] 2020-07-28 21:28
I'm playing July 27th build and I get this error when hovering over leaders:
![nil val](https://user-images.githubusercontent.com/8946274/88723886-ed1a2780-d129-11ea-9b1d-eb0f0f271bff.png)
Is that a quick bug to fix?

**Comment by RecursiveVision** [comment] 2020-07-28 23:52
@ilteroi I see you didn't base your new code on the merge fix branch. :)

**Comment by ilteroi** [comment] 2020-07-29 06:12
my bad ... can you tell me the id of the commit i should merge against? and which works without database changes?

**Comment by azum4roll** [comment] 2020-07-29 10:39
> edit: also i need more info on this getResourceFromCSAlliances() thing. which three lines? there are many to choose from.

The last 3 occurrences I bet.

**Comment by RecursiveVision** [comment] 2020-07-29 16:43
@ilteroi https://github.com/RecursiveVision/Community-Patch-DLL/commit/8849f4494b6c6b5de8c6bc0281ee776bc696af9a

This works without database changes.

**Comment by RecursiveVision** [comment] 2020-07-29 16:45
For the getResourceFromCSAlliances thing, compare the diplomacy branch to master and check the CvPlayer.cpp changes - that should fix it.

**Comment by RecursiveVision** [comment] 2020-07-29 16:46
https://github.com/LoneGazebo/Community-Patch-DLL/compare/diplomacy

**Comment by LoneGazebo** [comment] 2020-07-29 17:58
Once you guys have your merge commits sorted out, let me know and I'll make a master merge and merge my meager changes in.

**Comment by RecursiveVision** [comment] 2020-07-29 18:35
@LoneGazebo I would make another combined pull request but I'm on vacation with no computer access.

Master branch currently contains all of my changes - and all of ilteroi's changes up to "performance improvement for tactsim".

So to correctly merge everything, you'd need to:
- Merge the changes from ilteroi's commits on July 21 onwards in the drk branch

- Recomment out the 3 lines from CvPlayer.cpp (getResourceFromCSAlliances, described just above - since that's the only fix that wasn't merged properly)

- Add in your own changes

**Comment by RecursiveVision** [comment] 2020-07-29 18:39
Probably the easiest way to do it without merge errors to just grab the changed files from ilteroi's branch and replace the ones from master in your local repository...

Also you can ignore the diplomacy branch - I haven't tested my memory rework yet, as I explained in #6833.

**Comment by RecursiveVision** [comment] 2020-07-29 18:54
Okay, so ilteroi has made changes to the following files since my merge (in pushed commits).

These files were not changed by me, so you can just swap in the drk branch version of the files with no issues:
CvAIOperation.cpp
CvAStar.cpp
CvMilitaryAI.h
CvPlot.cpp
CvPlot.h
CvReligionClasses.cpp
CvTacticalAI.cpp
CvTacticalAI.h
CvTradeClasses.h
CvUnit.h
CvUnitCombat.cpp
CvLuaPlot.cpp

These files were also changed by me, so merging them could cause merge errors:
CvCity.cpp
CvHomelandAI.cpp
CvMilitaryAI.cpp
CvPlayerAI.cpp
CvTradeClasses.cpp
CvUnit.cpp
CvLuaPlayer.cpp

**Comment by ilteroi** [comment] 2020-07-29 19:56
honestly i think we should do a little git tutorial, this is hell right now. but i could merge cleanly at least.

@LoneGazebo : what's your timeframe for a proper release?

we still have those crashes to sort out ... did you make any progress on them? unfortunately my callstack gambit didn't work out so well. maybe we can recruit somebody who experiences crashes to run it in windbg or the visual studio debugger.

**Comment by RecursiveVision** [comment] 2020-07-29 20:14
If there's a better method for merging I'd be happy to learn that - merging everything manually took hours.

While we're on the subject of useful tutorials, it'd be pretty cool if we had comprehensive tutorials on how to install the IDE, build the DLL, fix build errors, use the debugger, and analyze crash reports. If this were easily accessible knowledge we could have more contributors to the project. I've learned how to do the first three but am still unclear on the other two.

**Comment by LoneGazebo** [comment] 2020-07-29 20:17
@ilteroi just recovering from a head-cold; tomorrow is my birthday, so I'm taking the day off. Maybe this weekend?

**Comment by ilteroi** [comment] 2020-07-29 20:45
well there are a million visual studio tutorials on the net ... for debugging, this shows the basics: https://docs.microsoft.com/en-us/visualstudio/debugger/debugger-feature-tour?view=vs-2019 . one specialty is that since we only build the gamecore DLL, i typically start the game manually and then use "attach to process" when the game is running. 

analyzing crash dumps is hard. callstacks can be corrupted or misleading, you need the right symbols, etc. but take a look at #6459.

@LoneGazebo : no rush, i'll just do another patch release.

**Closed** 2020-07-29 20:55 UTC
Labels: Announcement

**Comment by RecursiveVision** [comment] 2020-07-29 21:12
@LoneGazebo Happy birthday! 😄

**Comment by azum4roll** [comment] 2020-07-30 02:31
I'd help if Visual Studio doesn't take 5 minutes to load on my laptop and take a huge chunk out of my 8GB RAM.
