### ISSUE TITLE
Civ Hang during AI turn. Reproducable.

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4107] opened 2018-03-26 18:26 UTC
_1. Mod version (i.e Date - 4/23):_
20b March

_2. Mod list (if using Vox Populi only, leave blank):_
Enhanced Naval Warfare for Vox Populi (v 1)

_3. Error description:_ 
Netherlands AI hang the game. I think that is during their attack on some city. 

_4. Steps to reproduce (optional):_
Press 'Next' , Netherlands will ask to trade, Accept deal and Hang appears.

[loop.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1848956/loop.zip)

**Comment by Iamblichos** [comment] 2018-03-27 19:06
@ilteroi  might need to check: void CvTacticalAI::ClearEnemiesNearArmy(CvArmyAI* pArmy)

**Comment by Iamblichos** [comment] 2018-03-28 01:35
Just to clarify I've found a reproducible hang in that function between the while statement and the delayed death check. It would just loop back and forth into that when I stepped into it.

**Comment by ilteroi** [comment] 2018-03-28 07:00
hey, welcome back!

i see the problem, easy fix

**Comment by Iamblichos** [comment] 2018-03-28 16:22
Yeah I've been away. Had some health issues I had to address with my lower back. It's funny how sports from my younger days is catching up with me. Glad to be back. Thanks!

**Comment by longtomjr** [comment] 2018-03-29 14:28
Found this bug as well. Dunno if it will help, but it usually hangs after a trade offer from the civ that hangs during that turn. Also, I am new to testing beta releases, will a stable release be savegame compatible to make it easier to check if it is the same issue and have been fixed?

**Comment by LoneGazebo** [comment] 2018-03-30 20:17
@longtomjr what kind of offer was in the deal? Best to open a new issue for your case, most likely not related to @bigcat88

**Comment by longtomjr** [comment] 2018-03-31 09:07
@LoneGazebo Will do, was actually 2 offers :) that triggered it (any offer) will open a new report, can just close it later if it is a dupe

**Closed** 2018-04-09 20:25 UTC
