### ISSUE TITLE
clang build warnings and linker errors

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10452] opened 2023-11-11 11:47 UTC
the clang build generates lots of warnings:

```
==== C:\repos\civ-vp\CvGameCoreDLL_Expansion2\CvDealAI.cpp ====
warning: unknown warning option '-Wno-enum-constexpr-conversion' [-Wunknown-warning-option]
In file included from C:\repos\civ-vp\CvGameCoreDLL_Expansion2\CvDealAI.cpp:12:
C:\repos\civ-vp\CvGameCoreDLL_Expansion2/CvDealAI.h(72,23) : warning: extra qualification on member 'GetStrategicResourceItemList' [-Wmicrosoft-extra-qualification]
        vector<int> CvDealAI::GetStrategicResourceItemList(ResourceTypes eResource, int iNumTurns, bool bFromMe, int iNumAvailable, bool bPeaceDeal);
                    ~~~~~~~~~~^
C:\repos\civ-vp\CvGameCoreDLL_Expansion2\CvDealAI.cpp(5083,135) : warning: relational comparison result unused [-Wunused-comparison]
                        if (pLoopCity->plot()->GetNumEnemyUnitsAdjacent(pLoopCity->getTeam(), NO_DOMAIN, NULL, false, GET_PLAYER(eWinningPlayer).getTeam()) >= 2, true)
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
3 warnings generated.

==== C:\repos\civ-vp\CvGameCoreDLL_Expansion2\CvMinorCivAI.cpp ====
warning: unknown warning option '-Wno-enum-constexpr-conversion' [-Wunknown-warning-option]
C:\repos\civ-vp\CvGameCoreDLL_Expansion2\CvMinorCivAI.cpp(6499,9) : warning: 5 enumeration values not handled in switch: 'NO_MINOR_CIV_QUEST_TYPE', 'MINOR_CIV_QUEST_CONTEST_CULTURE', 'MINOR_CIV_QUEST_CONTEST_FAITH'... [-Wswitch]
        switch (eQuest)
                ^~~~~~
2 warnings generated.
```

and then it fails with linker errors (although there are not compilation errors) ...

**Comment by JohnsterID** [comment] 2023-12-13 05:01
Clang version? -Wno-enum-constexpr-conversion was added to make clang 16 work.

```
clang version 17.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

```
==== update_commit_id.bat ====
Nothing to commit, working tree clean.
Version identifier will be "Release-4.2.7 d71a8f7ee Clean"
==== C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\Lua\CvLuaDeal.cpp ====
In file included from C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\Lua\CvLuaDeal.cpp:12:
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\Lua/../CvDealAI.h(72,23) : warning: extra qualification on member 'GetStrategicResourceItemList' [-Wmicrosoft-extra-qualification]
   72 |         vector<int> CvDealAI::GetStrategicResourceItemList(ResourceTypes eResource, int iNumTurns, bool bFromMe, int iNumAvailable, bool bPeaceDeal);
      |                     ~~~~~~~~~~^
1 warning generated.
==== C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\Lua\CvLuaPlayer.cpp ====
In file included from C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\Lua\CvLuaPlayer.cpp:27:
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\Lua/../CvDealAI.h(72,23) : warning: extra qualification on member 'GetStrategicResourceItemList' [-Wmicrosoft-extra-qualification]
   72 |         vector<int> CvDealAI::GetStrategicResourceItemList(ResourceTypes eResource, int iNumTurns, bool bFromMe, int iNumAvailable, bool bPeaceDeal);
      |                     ~~~~~~~~~~^
1 warning generated.
==== C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvDealAI.cpp ====
In file included from C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvDealAI.cpp:12:
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2/CvDealAI.h(72,23) : warning: extra qualification on member 'GetStrategicResourceItemList' [-Wmicrosoft-extra-qualification]
   72 |         vector<int> CvDealAI::GetStrategicResourceItemList(ResourceTypes eResource, int iNumTurns, bool bFromMe, int iNumAvailable, bool bPeaceDeal);
      |                     ~~~~~~~~~~^
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvDealAI.cpp(5187,135) : warning: relational comparison result unused [-Wunused-comparison]
 5187 |                         if (pLoopCity->plot()->GetNumEnemyUnitsAdjacent(pLoopCity->getTeam(), NO_DOMAIN, NULL, false, GET_PLAYER(eWinningPlayer).getTeam()) >= 2, true)
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
2 warnings generated.
==== C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvDealClasses.cpp ====
In file included from C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvDealClasses.cpp:14:
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2/CvDealAI.h(72,23) : warning: extra qualification on member 'GetStrategicResourceItemList' [-Wmicrosoft-extra-qualification]
   72 |         vector<int> CvDealAI::GetStrategicResourceItemList(ResourceTypes eResource, int iNumTurns, bool bFromMe, int iNumAvailable, bool bPeaceDeal);
      |                     ~~~~~~~~~~^
1 warning generated.
==== C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvDiplomacyAI.cpp ====
In file included from C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvDiplomacyAI.cpp:19:
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2/CvDealAI.h(72,23) : warning: extra qualification on member 'GetStrategicResourceItemList' [-Wmicrosoft-extra-qualification]
   72 |         vector<int> CvDealAI::GetStrategicResourceItemList(ResourceTypes eResource, int iNumTurns, bool bFromMe, int iNumAvailable, bool bPeaceDeal);
      |                     ~~~~~~~~~~^
1 warning generated.
==== C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvDiplomacyRequests.cpp ====
In file included from C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvDiplomacyRequests.cpp:17:
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2/CvDealAI.h(72,23) : warning: extra qualification on member 'GetStrategicResourceItemList' [-Wmicrosoft-extra-qualification]
   72 |         vector<int> CvDealAI::GetStrategicResourceItemList(ResourceTypes eResource, int iNumTurns, bool bFromMe, int iNumAvailable, bool bPeaceDeal);
      |                     ~~~~~~~~~~^
1 warning generated.
==== C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvDllDealAI.cpp ====
In file included from C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvDllDealAI.cpp:14:
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2/CvDealAI.h(72,23) : warning: extra qualification on member 'GetStrategicResourceItemList' [-Wmicrosoft-extra-qualification]
   72 |         vector<int> CvDealAI::GetStrategicResourceItemList(ResourceTypes eResource, int iNumTurns, bool bFromMe, int iNumAvailable, bool bPeaceDeal);
      |                     ~~~~~~~~~~^
1 warning generated.
==== C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvMinorCivAI.cpp ====
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvMinorCivAI.cpp(6497,9) : warning: 5 enumeration values not handled in switch: 'NO_MINOR_CIV_QUEST_TYPE', 'MINOR_CIV_QUEST_CONTEST_CULTURE', 'MINOR_CIV_QUEST_CONTEST_FAITH'... [-Wswitch]
 6497 |         switch (eQuest)
      |                 ^~~~~~
1 warning generated.
==== C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvPlayer.cpp ====
In file included from C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvPlayer.cpp:33:
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2/CvDealAI.h(72,23) : warning: extra qualification on member 'GetStrategicResourceItemList' [-Wmicrosoft-extra-qualification]
   72 |         vector<int> CvDealAI::GetStrategicResourceItemList(ResourceTypes eResource, int iNumTurns, bool bFromMe, int iNumAvailable, bool bPeaceDeal);
      |                     ~~~~~~~~~~^
1 warning generated.
```

**Comment by ilteroi** [comment] 2023-12-13 21:18
hmm, updated clang to v17 ... managed to crash it :)

```
==== C:\repos\civ-vp\CvGameCoreDLL_Expansion2\stackwalker\StackWalker.cpp ====
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang-cl.exe C:\\repos\\civ-vp\\CvGameCoreDLL_Expansion2\\stackwalker\\StackWalker.cpp /FoC:\\repos\\civ-vp\\clang-build\\Release\\CvGameCoreDLL_Expansion2\\stackwalker\\StackWalker.obj /YuCvGameCoreDLLPCH.h /FpC:\\repos\\civ-vp\\clang-build\\Release\\CvGameCoreDLLPCH.pch -m32 -msse3 /c /MD /GS /EHsc /fp:precise /Zc:wchar_t /Z7 /Ox /Ob2 -flto /DFXS_IS_DLL /DWIN32 /D_WINDOWS /D_USRDLL /DEXTERNAL_PAUSING /DSTACKWALKER /DCVGAMECOREDLL_EXPORTS /DFINAL_RELEASE /D_CRT_SECURE_NO_WARNINGS /D_WINDLL /DSTRONG_ASSUMPTIONS /DNDEBUG /IC:\\repos\\civ-vp\\CvGameCoreDLL_Expansion2 /IC:\\repos\\civ-vp\\CvWorldBuilderMap\\include /IC:\\repos\\civ-vp\\CvGameCoreDLLUtil\\include /IC:\\repos\\civ-vp\\CvLocalization\\include /IC:\\repos\\civ-vp\\CvGameDatabase\\include /IC:\\repos\\civ-vp\\FirePlace\\include /IC:\\repos\\civ-vp\\FirePlace\\include\\FireWorks /IC:\\repos\\civ-vp\\ThirdPartyLibs\\Lua51\\include -Wno-invalid-offsetof -Wno-tautological-constant-out-of-range-compare -Wno-comment -Wno-enum-constexpr-conversion
1.	<eof> parser at end of file
2.	Optimizer
Exception Code: 0xC0000005
```

also, what is the deal with these warnings about GetStrategicResourceItemList? which extra qualifiers?

**Comment by JohnsterID** [comment] 2023-12-14 09:32
Well that is broken, I'm not sure. Clang 16 and 17 work for me. I just use the below in batch file on my different systems.
```
@echo On
cd C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL
py build_vp_clang.py --config debug
cmd /k
```

The warning is due to unnecessary use of the class name CvDealAI:: inside the class definition itself. Removing CvDealAI:: from CvDealAI.h:72 builds without the warning.

**Comment by JohnsterID** [comment] 2023-12-22 09:36
```
==== update_commit_id.bat ====
Nothing to commit, working tree clean.
Version identifier will be "Release-4.2.7 768fb4dcc Clean"
==== C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvCityStrategyAI.cpp ====
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvCityStrategyAI.cpp(5046,168) : warning: operator '?:' has lower precedence than '*'; '*' will be evaluated first [-Wparentheses]
 5046 |                 iValue += ((kPlayer.GetEspionage()->GetNumSpies() + kPlayer.GetPlayerTraits()->GetExtraSpies() * 10) + (pkBuildingInfo->GetGlobalEspionageModifier() * MOD_BALANCE_VP ? 30 : -20) + (pkBuildingInfo->GetSpyRankChange() + pkBuildingInfo->GetInstantSpyRankChange() * 100));
      |                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvCityStrategyAI.cpp(5046,168) : note: place parentheses around the '*' expression to silence this warning
 5046 |                 iValue += ((kPlayer.GetEspionage()->GetNumSpies() + kPlayer.GetPlayerTraits()->GetExtraSpies() * 10) + (pkBuildingInfo->GetGlobalEspionageModifier() * MOD_BALANCE_VP ? 30 : -20) + (pkBuildingInfo->GetSpyRankChange() + pkBuildingInfo->GetInstantSpyRankChange() * 100));
      |                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvCityStrategyAI.cpp(5046,168) : note: place parentheses around the '?:' expression to evaluate it first
 5046 |                 iValue += ((kPlayer.GetEspionage()->GetNumSpies() + kPlayer.GetPlayerTraits()->GetExtraSpies() * 10) + (pkBuildingInfo->GetGlobalEspionageModifier() * MOD_BALANCE_VP ? 30 : -20) + (pkBuildingInfo->GetSpyRankChange() + pkBuildingInfo->GetInstantSpyRankChange() * 100));
      |                                                                                                                                                                        ~~~~~~~~~~~~~~~^~~~~~~~~~
1 warning generated.
==== C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvEspionageClasses.cpp ====
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvEspionageClasses.cpp(7373,51) : warning: comparison of different enumeration types ('CivApproachTypes' and 'MajorCivApproachTypes') [-Wenum-compare]
 7373 |                         if (pDiplomacyAI->GetCivApproach(eTargetPlayer) <= MAJOR_CIV_APPROACH_HOSTILE)
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
==== C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvMinorCivAI.cpp ====
C:\Users\IEUser\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvMinorCivAI.cpp(6461,9) : warning: 5 enumeration values not handled in switch: 'NO_MINOR_CIV_QUEST_TYPE', 'MINOR_CIV_QUEST_CONTEST_CULTURE', 'MINOR_CIV_QUEST_CONTEST_FAITH'... [-Wswitch]
 6461 |         switch (eQuest)
      |                 ^~~~~~
1 warning generated.
```
New first two from https://github.com/LoneGazebo/Community-Patch-DLL/pull/10508, parentheses warning could be potentially fixed with the below but enum-compare should be confirmed by @axatin due to the immense work on the PR.

`iValue += ((kPlayer.GetEspionage()->GetNumSpies() + kPlayer.GetPlayerTraits()->GetExtraSpies() * 10) + ((pkBuildingInfo->GetGlobalEspionageModifier() * MOD_BALANCE_VP) ? 30 : -20) + (pkBuildingInfo->GetSpyRankChange() + pkBuildingInfo->GetInstantSpyRankChange() * 100));`

**Comment by axatin** [comment] 2023-12-22 12:43
thanks for letting me know, I will fix the espionage-related issues

**Closed** 2024-01-02 20:45 UTC
