### ISSUE TITLE
The Mysterious CTD

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#625] opened 2015-09-13 10:44 UTC
So I've been hunting this thing for months. Every mod combination under the sun. There may be some stochastic element to its triggering. It doesn't appear to happen if CP/CBP isn't loaded.

It looks like this:
1) you press end turn
2) some AI turn appears to hang for 1 or 2 sec and then CTD
[3) reloading a save reproduces the crash at the same turn]

The debug log shows the last action as being 
"changeNumGameTurnActive(1) m_iNumActive=1: setTurnActive() for player..."
every time.

I was looking into whether or not it was a specific civ that was incompatible. I was testing Tomatekh's Garamantes this latest time. I had just had a negative test (i.e. no crash) running only LS' Flanders with the same setup:
CIVDF
CBP
CP
CSD
CBP- compatibility
E&D(CBP version)
Historical Religions Edit
JFD's ExCE
More Luxs
(London Eye Wonder, Nuclear Fusion Reactor, Petronas Towers) <--- All late game buildings, likely innocent

This setup I've built up over time with no crashes, but as I say, it may be random and I'm misattributing the cause. The crash occurred just before the Industrial Era. 

Here is the log folder from that crash: https://www.dropbox.com/sh/z1bvev3s9rordgj/AAA2LFEXm_FWkiILFQNH0_uZa?dl=0

I brought it up with Tomatekh and followed his advice - removing the LUA files - but to no avail.

I feel bad bringing such a problem up with you, but I've been trying to solve it myself for ages and am at my wits' end. Need some debugging direction.

**Comment by ilteroi** [comment] 2015-09-13 12:52
note the callstack.log file ... it's empty. this can mean two things:

1. the crash does not occur in the dll
2. you need debugging symbols

i guess it's 2. you can get the pdb file from gazebo, or you download and compile the project yourself.
then, after the next crash, the log should contain the file and line where the problem occurred.

**Comment by LoneGazebo** [comment] 2015-09-14 00:24
I'm going to guess it is E&D. Try running a few games without it and see if it still happens. Any kind of 'soft hang' like that is usually LUA. DLL crashes will be instant (or an endless loop), but not in-between.
G

**Comment by Hokath** [comment] 2015-09-14 06:59
So I thought I'd ruled out E&D, but I concede there might be two different crashes going on. Will drop E&D and see if the frequency is significantly reduced. In the mean time, what is this pdb file do for life? That just means python debugger to me :P

**Comment by Hokath** [comment] 2015-09-14 17:18
Doesn't seem to have any effect getting rid of E&D.
Still seeing this empty callstack file. Will get rid of ExCE next, but I've been through all this before.

**Comment by JFDaly** [comment] 2015-09-15 07:09
From my experience, an empty callstack means a nil ID is being passed to some function, via some third party function (possibly to the DLL, which, IIRC, is when crashes occur). For me, this has always been a Decision or an Event from E&D, because of how many functions it jumps over.

If you can deduce a problem with ExCE, though, do post about it in my thread. Most of the old things that would've been a red flag for this have since been made obsolete by the DLL, so I wouldn't expect it.

**Comment by Hokath** [comment] 2015-09-15 22:26
The hunt continues, definitely nothing to do with E&D.
In the CustomMods log, do you think these final lines are significant?
"
CvUnit.cpp: 5554 - jumpToNearestValidPlotWithinRange(1) failed for unit Archer at plot (45, 17)
CvUnit.cpp: 5554 - jumpToNearestValidPlotWithinRange(1) failed for unit Spearman at plot (27, 33)
"

**Comment by Hokath** [comment] 2015-09-16 09:00
MiniDump of latest crash https://www.dropbox.com/s/nykw4299ihagnv9/CvMiniDump.dmp?dl=0

**Comment by LoneGazebo** [comment] 2015-09-16 15:02
Crash goes to disassembly through lua. I don't want to beat a dead horse, but there's definitely a lua bug in one of your other mods that is causing this.

G

**Comment by Hokath** [comment] 2015-09-16 15:12
In that case I will reinstall everything and run CPP + ExCE to confirm it is this interaction.

Yeah I changed the install path to point to the MODS folder since I accidentally deleted it while trying to scroll to the end (to see it was pointing to the right place).

**Comment by LoneGazebo** [comment] 2015-09-16 17:41
Yep, I did it that way so that the installer would delete existing copies of the mods before installation.

It'll work, technically, that way, but yeah, trust the installer. :)

I'd definitely report all of this to JFD.

**Comment by Hokath** [comment] 2015-09-16 22:22
Link to the latest info for his Modjesty
https://www.dropbox.com/sh/w1zxt9fiphx2wyd/AABYME0wCO8I32Qwuz9H1-bEa?dl=0

**Comment by LoneGazebo** [comment] 2015-09-17 03:58
Bunch of JFD stuff popping up:

[303173.996] Invalid Reference on Improvement_ResourceTypes.ResourceType - "RESOURCE_JFD_FEATHERS" does not exist in Resources
[303173.996] Invalid Reference on Improvement_ResourceType_Yields.ResourceType - "RESOURCE_JFD_FEATHERS" does not exist in Resources
[303174.168] Invalid Reference on Resource_YieldChanges.ResourceType - "RESOURCE_JFD_FEATHERS" does not exist in Resources
[303174.168] Invalid Reference on Resource_Flavors.ResourceType - "RESOURCE_JFD_FEATHERS" does not exist in Resources
[303174.168] Invalid Reference on Resource_FeatureBooleans.ResourceType - "RESOURCE_JFD_FEATHERS" does not exist in Resources
[303174.168] Invalid Reference on Resource_FeatureTerrainBooleans.ResourceType - "RESOURCE_JFD_FEATHERS" does not exist in Resources
[303174.683] Invalid Reference on Unit_AITypes.UnitType - "UNIT_EXPLORER" does not exist in Units
[303174.683] Invalid Reference on Unit_ClassUpgrades.UnitType - "UNIT_EXPLORER" does not exist in Units
[303174.683] Invalid Reference on Unit_FreePromotions.UnitType - "UNIT_EXPLORER" does not exist in Units
[303174.683] Invalid Reference on Unit_FreePromotions.UnitType - "UNIT_EXPLORER" does not exist in Units
[303174.683] Invalid Reference on Unit_FreePromotions.UnitType - "UNIT_EXPLORER" does not exist in Units
[303174.683] Invalid Reference on Unit_Flavors.UnitType - "UNIT_EXPLORER" does not exist in Units
[303175.634] Invalid Reference on Unit_BuildingClassPurchaseRequireds.UnitType - "UNIT_EXPLORER" does not exist in Units
[303175.821] Invalid Reference on Resource_JFD_RarityMods.ResourceType - "RESOURCE_JFD_FEATHERS" does not exist in Resources

**Comment by JFDaly** [comment] 2015-09-17 07:47
I'd deleted my Feathers resource and CBP's explorer should the CBP be active, but didn't properly clean up the references (the 'delete missing references' file was loaded before this, by mistake). Not sure if such can caused CTDs, but hopefully so, and I'll push out an update promptly.

**Comment by Hokath** [comment] 2015-09-17 22:24
Didn't help it. It's back, with a vengeance.

**Comment by jeditimelord** [comment] 2015-09-18 01:12
I think I'm getting the same issue with the same message always on the crash. I don't use E&D. The CustomMods file always ends with the same types of lines as well
"
CvUnit.cpp: 5554 - jumpToNearestValidPlotWithinRange(1) failed for unit Spearman at plot (52, 61)
CvUnit.cpp: 5554 - jumpToNearestValidPlotWithinRange(1) failed for unit Warrior at plot (62, 15)
"

The empty Callstack file is there for me as well. I'd love to help by providing files etc. for evidence but I don't know what would be useful. The crashes are always instant so if what @LoneGazebo said was true I suspect the dll. If there's a pdb file that would help for debugging I'd be glad to use it and report back.

**Comment by LoneGazebo** [comment] 2015-09-18 05:12
That warning isn't necessarily a CTD, just FYI.

Do you use ExCE?
G

**Comment by jeditimelord** [comment] 2015-09-18 12:19
No. I've purposely stopped using other mods with CP and CBP except for a personal mod I made which gives extra traits, buildings, and units to the Shoshone, purely an XML mod. My suspicion which I haven't been able to prove yet is that it crashes when a civilian ends a turn under a military unit of another civ. Previous crashes came during AI turns but the last one came right as I used a Great Prophet on a City State while standing under a unit from the City State.

It does not always occur at the same turn; reloading the save will sometimes let it go for a few more turns.

**Comment by Iamblichos** [comment] 2015-09-20 15:47
Hi I just wanted to confirm what jeditimelord said above. I've been using the CP and the DLL - Various Mod Components for some time (not together of course), and I notice strange CTD with what might be the civilian units (particularly water plots, and enemy units with my civilian units). I suspect it could be something not right in the Civilian Traffic jams mod. Since the CP and the VMD have a common code base, I see it in both mods.

**Comment by Vyyt02** [comment] 2015-09-20 19:46
I suggest you add IGE to your mod setup and kill the AI unit(s) you suspect is/are causing the CTDs. If the following AI turn does not end up with CTD, then you will know for sure which unit is causing the trouble.

**Comment by JFDaly** [comment] 2015-09-20 22:06
Oh, if it's something to do with the Traffic Jam mod, then that could help explain why ExCE might be also causing CTDs. In the last version, I did turn the Traffic Jam functionality on via ExCE.

**Comment by LoneGazebo** [comment] 2015-09-21 14:03
NMCTJ is enabled by default in the CP, and no one gets CTDs from that just in the CP.

G

**Comment by Iamblichos** [comment] 2015-09-21 14:40
That very well may be in and of itself with CP and VMD. There is an incompatibility somewhere possibly between JFD's lua Civ code and CP and VMD when that mod is enabled. When I turn that mod off in VMD, I get no CTDs. With it on, I'm guaranteed to have a CTD anywhere from turns ~45 and on (and with it defaulted on, same time frame in CP). Could be something in the LUA code in the way it is tracking units. Will be difficult tracking down the incompatibility.

**Comment by jeditimelord** [comment] 2015-09-22 12:25
Are you sure it's in the CP? I'm up to date as of this weekend's patch and I couldn't find it in the settings.sql file and my workers couldn't cross Incan units.

**Comment by Iamblichos** [comment] 2015-09-27 19:41
Looked back over this issue again and my crashes are not because of civilian traffic jams mod but database ID issues where entries are deleted and ID's not remapped in my mod. Something to be aware of in your own mods and others.

**Comment by Hokath** [comment] 2015-09-28 09:27
So CBP wipes all the promotion IDs and reassigns them? If a unit tries to receive a promotion through lua that no longer exists, will this then crash it to desktop?

**Comment by Iamblichos** [comment] 2015-09-28 14:26
The CBP remaps the promotion IDs. Most lua code I've seen and written myself calls it out by Type string, not by promotionID. Some IDs are never to be messed with. The CP/CBP documents the one's he's modified and added into the DLL (e.g. Yields).

For further info: http://forums.civfanatics.com/showthread.php?p=13157588

**Comment by LoneGazebo** [comment] 2015-09-28 14:34
CBP now (as of two versions ago) does not Id remap the, outside of what they aleeady were. Promotion database should look the same. 

G

**Comment by Iamblichos** [comment] 2015-09-28 14:43
Hmmm....I just looked at PromotionChanges.sql from your release last night and at the end it has:

CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
	INSERT INTO IDRemapper (Type) SELECT Type FROM UnitPromotions ORDER BY ID;
	UPDATE UnitPromotions SET ID = ( SELECT IDRemapper.id-1 FROM IDRemapper WHERE UnitPromotions.Type = IDRemapper.Type);
	DROP TABLE IDRemapper;

	UPDATE sqlite_sequence
	SET seq = (SELECT COUNT(ID) FROM UnitPromotions)-1
	WHERE name = 'UnitPromotions';

**Comment by LoneGazebo** [comment] 2015-09-28 16:25
Yes. The IDs should match up. I did that because the <replace> xml generates new IDs, instead of using the old ones.

**Comment by ftristram** [comment] 2015-09-30 14:44
Hey,
I downloaded the CPP Full (No-EUI Version) yesterday and I got multiple CTD upon AI turns (running no other mods). It happened far less frequently when I turned AI portrait graphics to 'simple'. I am at a point now though that reproduces the CTD every time. See this savegame: https://www.dropbox.com/s/t0lcju3um028bsf/QuickSave.Civ5Save?dl=0

Upon clicking end turn, Netherlands will ask for a defensive pact, then Polynesia will ask for open borders, than the game CTDs at the end of Polynesia's turn/beginning of city state phase. If you declare war to Polynesia before you end your turn, it appears the crash is avoided.

Hope that helps you guys to nail it down.

**Comment by LoneGazebo** [comment] 2015-09-30 14:47
Mod list?

**Comment by ftristram** [comment] 2015-09-30 15:22
Just the ones from the Community Patch Project:
- City State Diplomacy for CBP v. 27
- Civ IV Diplomatic Features CBP edition v. 10
- Community Balance Patch - Compatibility Files v. 1
- Community Balance Patch v.13
- Community Patch v. 66
- More Luxuries v. 155

**Comment by LoneGazebo** [comment] 2015-09-30 15:27
What's the specific date on the CP? As in, is it 9/24? 9/27? Etc.

G

**Comment by ftristram** [comment] 2015-09-30 15:32
CP is 9-27v2, CBP and compatibility files are 9-27, City State Diplo and Civ IV Diplo are 6-19.

**Comment by LoneGazebo** [comment] 2015-09-30 23:23
I was able to run the game without issue past that point. Are you sure your video drivers, etc. are up to date?

**Comment by ftristram** [comment] 2015-10-01 20:50
Yeah, never had any problems with it. Used Steam to verify the game files, didn't change anything. I enabled logging and saved the logs for when it crashes and when the next turn begins successfully (by making an open border agreement with Polynesia on the previous turn the crash is avoided).
https://www.dropbox.com/s/ama32f2wjafa9c6/logs_crash.zip?dl=0
https://www.dropbox.com/s/zaxs6377af9ykv8/logs_no_crash.zip?dl=0
I guess I'll try it on my laptop too, but if it seems to be a local problem if it doesn't work for you.

**Comment by LoneGazebo** [comment] 2015-10-02 04:26
Latest version isn't savegame compatible, but I think it'll fix the CTD for your next game.

**Closed by LoneGazebo** 2015-10-02 04:26 UTC
Labels: question
