### ISSUE TITLE
text localization not working

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5961] opened 2019-12-14 15:12 UTC
if an air attack is intercepted, there is no notification because localization returns an empty string ...

```
strBuffer = GetLocalizedText("TXT_KEY_MISC_YOU_ATTACK_BY_AIR_INTERCEPTED", pInterceptor->getNameKey(), pkAttacker->getNameKey(), iDefenderDamageInflicted, pCity->getName().GetCString());
```

the template is defined as 

		<Row Tag="TXT_KEY_MISC_YOU_ATTACK_BY_AIR_INTERCEPTED">
			<Text>While attacking {@4_CityName), an enemy {@1_UnitName} intercepted your {@2_DefUnitName} ({3_Num} damage)!</Text>
		</Row>

so i don't see the problem? any ideas?

**Comment by ilteroi** [comment] 2019-12-15 19:11
i've added a failsafe so that you at least see the name of the template that should have been shown in case localization fails ... but I still don't understand what's wrong here

**Comment by UndeadDevel** [comment] 2019-12-17 21:20
This is just a guess, but it could it have anything to do with the fact that for all but the last variables in the string there is an "@" character for referencing them?
Maybe it gets fixed by adding the "@" for the last one? So
`({@3_Num} damage)`
instead of
`({3_Num} damage)`
Perhaps this leads to some sort of parsing failure resulting in the whole function or whatever terminating...

**Comment by ilteroi** [comment] 2019-12-18 13:58
good point, i'll try that

**Comment by ilteroi** [comment] 2019-12-20 21:30
well that didn't work unfortunately ...

**Comment by UndeadDevel** [comment] 2019-12-20 21:33
Have you tried a simple text for that template, without any references in it? That would at least show if the issue is with "interpreting" the references or something else...

**Comment by LoneGazebo** [comment] 2019-12-20 23:16
@ilteroi not sure, localization is weird in the DLL

**Closed** 2020-04-16 15:59 UTC
Labels: Calling all Modders!
