### ISSUE TITLE
Targeting/ movement errors with enemy units in tiles other than that displayed.

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2221] opened 2016-07-25 06:41 UTC
Bug Report Template

Mod Version (i.e Date - (4/23b)):
July 15th

1. Mod List (if using standard CPP set, leave blank):
+FlagPromotions v7
+InfoAddict v22
+Leadership Reformations v4

2. Type of error (i.e. crash, interface bug, AI quirk): 
The targeting is pointing to tiles that don't contain units and the units themselves are usually, though not always, 2 tiles away.

Not just naval units experience this, though it appears to be more common with them.

Targeting the tile that allows it, and dealing enough damage, does remove the unit from the game and it is shown as being destroyed in the tile that it appears in.

3. Steps to reproduce:

4. Additional information:
Screenshot of a melee unit trying to move to attack an enemy but suffering from ZOC from an unit apparently in the tile adjacent.
![melee attack error](https://cloud.githubusercontent.com/assets/3291695/17092460/3340382a-5286-11e6-9950-30964ce9c588.jpg)

Screenshot of a ranged unit firing at an unit that isn't in the tile displayed.
![ranged attack error](https://cloud.githubusercontent.com/assets/3291695/17092468/3e63e6de-5286-11e6-8ff4-c9224e26e15f.jpg)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment] 2016-07-25 14:02
@ilteroi, any thoughts?

**Comment by ilteroi** [comment] 2016-07-25 14:30
not yet, will take a look later ... unfortunately the OP is a bit sparse with information, "steps to reproduce" would have been nice

**Comment by LoneGazebo** [comment] 2016-07-25 15:37
My guess is that one or more of the caches we use for handling adjacent units/enemies is not clearing properly on unit death.

**Comment by ilteroi** [comment] 2016-07-25 21:48
no news - can't reproduce ... seems to be rare

**Comment by ilteroi** [comment] 2016-07-25 21:49
maybe already fixed by other changes

**Comment by GrantSP** [comment] 2016-07-25 23:03
I didn't add any specific "steps to reproduce" because they should be self-evident: be at war and either move, or target, with your units.

With any knowledge of the code it seems similar to the way the units have their combat resolved BEFORE the movement is shown, ie. they take and deal damage and then move into a position where combat is initiated. Possibly also why recon units sometimes engage in combat instead of moving around an enemy unit/barb camp.

**Comment by ilteroi** [comment] 2016-07-26 05:59
this is not productive. if you want to help to get this fixed, please provide a savegame.

**Comment by Iamblichos** [comment] 2016-07-26 13:58
I've noticed this as well. Even happens to me when I make large movements with a scout, and it runs into another unit and has to back track for another open plot. The graphics stay on a certain tile, while the actuality of the unit is on another.

**Comment by LoneGazebo** [comment] 2016-07-26 15:00
Again, guys, speculation not super helpful. Savegames are king.

**Comment by GrantSP** [comment] 2016-07-26 23:17
Look, I'm not being obstructive or anything but I didn't believe a savegame would show anymore detail than a couple of screenshots.
The logs generated didn't show anything odd and I still don't know what you will gain by seeing it in action, other than 1st-hand experience.
I will, whenever I encounter it again, provide a savegame, that game is long ago finished and discarded.

**Comment by LoneGazebo** [comment] 2016-07-27 01:13
Saved games allow us to hook into the DLL and run the stack live. That's infinitely more useful than a screenshot. Pleads submit one if you can replicate it.

**Closed** 2016-08-03 02:10 UTC
Labels: Need more information
