### ISSUE TITLE
More than 3 Vassales = Bug, and more bug about vassales

### ISSUE THREAD

**Issue by Cat-du-Fromage** [LoneGazebo/Community-Patch-DLL#5071] opened 2019-01-16 22:28 UTC
_1. Mod version (i.e Date - 4/23):_
12-18

_2. Mod list (if using Vox Populi only, leave blank):_
JFD_Prussia
Civic and reform
Wonders expand

_3. Error description:_ 
All of theses issues below where present in september already, when i used VP only.

Problem 1)
This Bug already appears in the version of October (with vox populi Only)
In my last multiplayer game, i just got my 3rd vassale, but when i go to the vassal's windows i got a very bad surprise.
![image](https://user-images.githubusercontent.com/46396184/51281941-24abfd80-19e4-11e9-8d2b-e2d3b60df058.png)
When i tried to click on Leader Name, nothing happens(note there should'nt be "Leader Name", but the name of each of my vassales)

problem 2)
Also, big issue we experiment, when we make pease with a other player, and the same player you just make peace with attak your vassales, it doesn't drag you into war,

Maybe it's in purpose, but in my opinion a master should be able to defend his vassales.

Problem 3)
When a player attack someone who is the vassal of a other player, Peace will be force the turn AFTER, so if you do this with an AI you can bug abuse and kill his entire army, since he won't strike-back AND then you can declare war right after the peace is forced.

solution: In my opinion, when you declare war to a vassal, you declare war to his master too

Thoses problems (EXEPTION the first one) are minor since they only appear in multiplayer, so by setting rules (no bugabuse, ect..)you can "avoid" them.

Hope you can read me, sorry for my english ^^

_4. Steps to reproduce (optional):_
problem 1) Get 3 or more Vassal
problem 2) need 2-3 players to reproduce since AI avoid this situation
problem 3 need to be 2 players, since AI don't declare war to vassales

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Vassal_Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2766298/Vassal_Bug.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Cat-du-Fromage** [comment] 2019-04-11 21:53
EDIT after lots of game it appears, that desync cause the bug, BUT the annoying thing is that even quit/restart the game don't fix that... seems like desync cause some corruption

**Comment by Edaka** [comment] 2019-12-17 09:51
Desyncs are tricky, see #5350 . I'll close this for now and leave that one open, since desyncs seem to be the root cause.

**Closed by Edaka** 2019-12-17 09:51 UTC
Labels: Logging Needed
