### ISSUE TITLE
Missing action buttons on air units

### ISSUE THREAD

**Issue by Christmasbg** [LoneGazebo/Community-Patch-DLL#8893] opened 2022-05-20 19:18 UTC
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.2.0, DX 10 & 11):_
Using the last Vox Populi version 2.2 and DirectX 11

_2. Mod list (if using Vox Populi only, leave blank):_
Using the full Vox Populi install + Info Addict (v 22) + Promotion Flags for EUI (v 3.1a)

_3. Error description:_ 
Air units are missing action buttons. Bombers do not have the air strike action button. Fighters do not have the air sweep action buttons. Both can be seen on the screenshots. Intercept action is not missing and Nuke action for nukes is not missing. 

---------------------------

1. Log files:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8743498/Logs.zip)

2. Save game:
[NapoleonSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8743500/NapoleonSave.zip)

3. Screenshots:
[Images.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8743506/Images.zip)

**Comment by LessRekkless** [comment] 2022-05-21 19:59
duplicate of #8879

**Closed** 2022-05-21 20:07 UTC
Labels: Fixed for upcoming version
