### ISSUE TITLE
Unit icons occasionally offset

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1088] opened 2016-01-11 21:48 UTC
Also noted by The MarshmallowBear on the forums, units are occasionally having their icons slightly offset to the upper left. Not the biggest deal, but you can see how it could be confusing during a war or crowded map (it makes the unit seem as if on a different tile).

![2016-01-11_00002](https://cloud.githubusercontent.com/assets/11132095/12247678/b2dda2ee-b87a-11e5-91aa-d618a7f4e2e0.jpg)
![2016-01-11_00001](https://cloud.githubusercontent.com/assets/11132095/12247677/b2db3d2e-b87a-11e5-8818-150bd0489d08.jpg)

In this second screen, look at the Byzantine warriors.

**Comment by GrantSP** [comment] 2016-01-11 23:25
Noticed this last night as well. Makes it an odd experience when your city bombardment alert icon is active and you try targeting where the icon is only to have it fail.
Why or how this UI glitch happens is above my pay-grade.

**Comment by LoneGazebo** [comment] 2016-01-12 01:47
Is it an EUI thing?

**Comment by joosegoose** [comment] 2016-01-12 02:08
Possibly. The latest beta is the first time I've noticed it though.

**Comment by GrantSP** [comment] 2016-01-12 02:10
Not sure if it is an EUI thing, don't think EUI touches the units that way. Could be wrong.

**Comment by LoneGazebo** [comment] 2016-01-12 16:28
Not blaming EUI, just narrowing my search. UI stuff like that is generally handled in LUA. My thought (and I'm bringing @ilteroi in on this) is that garrison status for a unit isn't being reset when they leave a city, so their unit icon is staying where it goes for a garrison. Not sure if that's correct, though, but it seems like the LUA is interpreting their status as garrisoned via the DLL.

**Comment by ilteroi** [comment] 2016-01-12 21:42
sounds like a plausible theory. of course garrison status is supposed to be reset when the unit leaves the city ... but who knows.

**Comment by GrantSP** [comment] 2016-01-12 23:26
The garrison idea does sound like a plausible one except I've just now received a unit from a CS, which obviously has never been garrisoned,  and it too shows this offset.

**Comment by LoneGazebo** [comment] 2016-01-13 01:49
Code from flag lua:

        -- Technically, we should get a UnitGarrisoned event after the creation event if
        -- the unit is garrisoned.  So IsGarrisoned should always be false at creation.
        -- In the interest of preserving behavior I'm allowing m_IsGarrisoned to be set
        -- using IsGarrisoned() on creation.  However, in the strategic view this causes
        -- a visibility error in some odd cases so there it always starts as false.
        if( InStrategicView() )
        then
			o.m_IsGarrisoned = false;
		else
			o.m_IsGarrisoned = pUnit:IsGarrisoned();
		end

**Comment by ilteroi** [comment] 2016-01-13 07:08
will check. by the way, would it be possible to make it so that you can select the unit also by clicking on it's flag?

**Comment by LoneGazebo** [comment] 2016-01-13 18:06
I can check.

**Comment by ilteroi** [comment] 2016-01-13 20:22
been running a testgame with a breakpoint for this condition, but no hit ... i didn't change anything lately, so i'm at a loss right now

**Comment by LoneGazebo** [comment] 2016-01-13 20:33
Well, they are on the version just before your garrison mk.3, so perhaps it is fixed now? I also cannot reproduce.
G

**Comment by LoneGazebo** [comment] 2016-01-14 06:41
Fixed.

**Closed by LoneGazebo** 2016-01-14 06:41 UTC
Labels: Fixed, Gazebo is on the Case
