### ISSUE TITLE
VP 4.4.2. Marsh tiles have tundra texture. (Single and Multiplayer)

### ISSUE THREAD

**Issue by vaderkos** [LoneGazebo/Community-Patch-DLL#10584] opened 2024-01-10 11:22 UTC
_1. Mod Version (4.4.2). Current Version: 4.4.2_
4.4.2_VP-SSEM_EUI
https://drive.google.com/drive/folders/1Qq5mWnGGv2uuEPA62azseUhw-pE4--3O

_2. DirectX Version_
11

_3. List of Other Mods_
-

_4. Describe the Issue_
Marsh tiles have tundra texture

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[marsh tundra.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13886894/marsh.tundra.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13886912/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
-

_8. Steps to reproduce the Issue (Optional)_
Create or load game, and look for marsh tiles.

_9. Screenshots of the Issue (Optional)_
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/13507416/37eebad6-1357-4228-ab60-c18d3438254a)

**Comment by azum4roll** [comment] 2024-01-11 01:41
Duplicate of #10583

**Closed by azum4roll** 2024-01-11 01:41 UTC
