### ISSUE TITLE
Yields disappear from map whenever I click next turn

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3275] opened 2017-06-09 12:26 UTC
_1. Mod version (i.e Date - 4/23):_

current beta
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Play game.
Click next turn while having yields of the tiles shown. While the turn is passing, the yields will not be shown.

**Comment by ilteroi** [comment] 2017-06-09 13:30
probably a side effect of the delayed fog of war update at the end of the turn. need to check

**Comment by ilteroi** [comment] 2017-06-09 16:59
can't confirm. works for me ...

**Comment by Enrico-Swagolo** [comment] 2017-06-09 17:17
Do you use EUI?

**Comment by ilteroi** [comment] 2017-06-09 19:03
sure

**Comment by Enrico-Swagolo** [comment] 2017-06-09 19:14
Maybe you're not in the regular view? Are you in the specialistic, less resource intensive one? I mean the yield icons on the terrain, they get covered after next turn is shit and typically refreshed by moving around units (only in the area that'd be the field of view of the moved unit). I saw on community patch forum that someone else has the same problem, that seems weird.

**Comment by Enrico-Swagolo** [comment] 2017-06-10 09:40
I looked at the last patch thread and yet another person seemingly has the problem, look at randomnub's picture. Yields are only showcased in places he has moved his units probably, otherwise the land is not showing its yields.

**Comment by Grabbl** [comment] 2017-06-10 11:57
I have the same problem and tried a some things:

As Enrico-Swagolo said, the yield icons disappear when clicking "next turn".
Then, when moving a unit, yields are shown for all tiles that a unit gets field of view (but not tiles that were already in field of view, e. g. from cities).
Disabling and reenabling yield icons shows them for all tiles, as intended, but they disappear at "next turn" again.

**Comment by ilteroi** [comment] 2017-06-15 06:41
should be fixed, give it a try

**Comment by Enrico-Swagolo** [comment] 2017-06-17 11:02
Alas, it's not fixed

**Comment by ilteroi** [comment] 2017-06-17 13:08
hmm. i was just guessing after all ... don't know what to do about this then.

**Comment by Enrico-Swagolo** [comment] 2017-06-17 15:23
It's related to the reveal of tiles remaining for the duration of the turn as after yields disappear, moving somewhere will reveal the yields in the line of sight of the guy, but dunno. Strangely, actions like using a Great Person to make a great tile also make it so the yields are revealed.

**Comment by LoneGazebo** [comment] 2017-06-17 16:14
I'll look at it when I get a chance.

**Closed** 2017-07-18 21:49 UTC
Labels: Need more information
