### ISSUE TITLE
Multiplayer "m_aiWarDamageValue" desync on VP4.2.7

### ISSUE THREAD

**Issue by Cyclopia31** [LoneGazebo/Community-Patch-DLL#10418] opened 2023-11-01 15:29 UTC
1. Mod Version (X.Y.Z). Current Version: 4.2.7
VP 4.2.7
Modpack link: https://drive.google.com/file/d/1vKXFwngomErxVWwBv2FOUmS7KJ7ktF6c/view?usp=sharing

2. DirectX Version
DirectX 11

3. List of Other Mods
Even more ressources, 3/4 UC, SuperSettler v2

4. Describe the Issue
Hi, I tested a little the multiplayer stability using the latest version. I can see a "variable_out_of_sync" on only the non host "net_message_debug.log". It's a "m_aiWarDamageValue" desync like the one in report 10338: https://github.com/LoneGazebo/Community-Patch-DLL/issues/10338
I hope it can help :)

_5. Data
Here the logs and saves for both players: https://drive.google.com/file/d/1--BjJZaS68lvQVEdxqGofs4n_WogtZ62/view?usp=sharing

**Comment by seroperson** [comment] 2023-11-18 15:39
Hello! Thank you for reporting and sorry for such a late response. I checked these two issues, but unfortunately I'm unable to reproduce both of them. I see there is definitely something wrong because the same variable is desynced in both cases, but looks like something is desyncing internally way far earlier from the actual `m_aiWarDamageValue` got desynced, or maybe some specific circumstances are required to make this desynced, because I played this game maybe 5 turns before the desync and still can't reproduce. I will add more logs to this variable and maybe next report will make things clearer.

**Comment by axatin** [comment] 2024-06-09 13:53
I can't reproduce the desync either. @Cyclopia31 can you test if it is consistently reproducible when the two of you play it?

**Comment by Cyclopia31** [comment] 2024-06-11 18:10
> I can't reproduce the desync either. @Cyclopia31 can you test if it is consistently reproducible when the two of you play it?

Hi @axatin I have seen some of it. But I can't repeat it :(

If you want I have a game on VP 4.7.3 with https://github.com/LoneGazebo/Community-Patch-DLL/pull/10919 & https://github.com/LoneGazebo/Community-Patch-DLL/pull/10930 integrated to the .dll. I have also deleted the in-game report of desyncs (in the chat).

We had two resyncs during the first 120 turns. Do you want me to post a github Issue or you do not work on modified .dll ?

**Comment by axatin** [comment] 2024-06-15 18:43
It it easier to work with released versions. 4.9 should be stable

**Comment by axatin** [comment] 2024-07-16 19:25
closed as it can't be consistently reproduced. also, let's focus on the desyncs in the newer versions.

**Closed by axatin** 2024-07-16 19:25 UTC
Labels: Multiplayer
