### ISSUE TITLE
CTD after end turn

### ISSUE THREAD

**Issue by pikasnoop** [LoneGazebo/Community-Patch-DLL#7564] opened 2021-03-08 21:43 UTC
_1. Mod version (i.e Date - 12/1): 3-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: CTD after pressing end turn. Happened 3 times on this turn, I have no clue why. Happens after I accept to renew the defensive pact with Persia.

_4. Steps to reproduce (optional): Save is included, just hit end turn, accept the defensive pact (I did not try without accepting, would like to keep the pact) and it should crash. If not it is something on my end.
[save and cvminidump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6104328/save.and.cvminidump.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment] 2021-03-08 23:42
may be fixed by #7561

**Comment by ilteroi** [comment] 2021-03-10 21:55
anyway duplicate of #7561

**Closed by ilteroi** 2021-03-10 21:55 UTC
