### ISSUE TITLE
"School of Philosophy" can't be built even if criteria are met. (Multiplayer)

### ISSUE THREAD

**Issue by vaderkos** [LoneGazebo/Community-Patch-DLL#10486] opened 2023-11-29 14:30 UTC
_1. Mod Version (3.10.14). Current Version: 4.2.7_
Modpack 3.10.14_VP-SSEM_EUI 
Modpack link: https://drive.google.com/file/d/1BQ_B5x-fDyvmGvdfLHRKp_4MX-YW_eA7/view?usp=drive_link
Modpack forum link: https://forums.civfanatics.com/threads/voxpopuli-modpacks-last-update-4-2-7.685164/

_2. DirectX Version_
11

_3. List of Other Mods_
* EUI
* Super Settler
* Even More Luxury Resources

_4. Describe the Issue_
Played multiplayer with my friends. England player reported that "School of Philosophy" can't be built

"School of Philosophy" can't be built event if all criteria met.
What checked:
* Libraries in city. (From Great Library)
* National citizens required
* It's not being built in any other city
* It's not already constructed in any owned city

What tried:
* Clearing cache
* Loading from turns where required technology is not researched.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[For Report Gandhi_0122 AD-0175.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13501660/For.Report.Gandhi_0122.AD-0175.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13501650/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
Game didn't crash.

_8. Steps to reproduce the Issue (Optional)_

0. Load multiplayer game
1. Change your nation to England
2. Load game
3. Proceed to next turn until technology researched.
4. Try to build "School Of Philosophy"
5. Check required criteria for "School Of Philosophy"
6. "School Of Philosophy" can't be built

_9. Screenshots of the Issue (Optional)_
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/13507416/4ec80199-3231-4ed6-9346-e2890455c28b)

**Comment by tomekpa** [comment] 2023-12-02 13:37
Just to clarify, it may be a little rude to ask, but are you sure, you didn't put it by accident into other city que?
You can build it only in once city at once.

**Comment by vaderkos** [comment] 2023-12-02 16:43
> Just to clarify, it may be a little rude to ask, but are you sure, you didn't put it by accident into other city que? You can build it only in once city at once.

No, we checked multiple times. Btw. required technology is not researched, so you can't built it till next turn that is in save. And when turn is next you immediately can't build it.

**Comment by Cyclopia31** [comment] 2023-12-04 18:46
Did you had a "Force resync" during your game, especially between turn 0 et 1 ? A force resync is a loading screen for both players between 2 turns. Something seems broken in your game, for example England can see some american territory without a unit there.

**Comment by vaderkos** [comment] 2023-12-04 18:53
> Did you had a "Force resync" during your game, especially between turn 0 et 1 ? A force resync is a loading screen for both players between 2 turns. Something seems broken in your game, for example England can see some american territory without a unit there.

Yeah, we had 1 as I remember, but not at first turn, somewhere in the middle of the game. Also he mentioned that he saw some territory even there were none of his units there, but we didn't take this seriously...

**Comment by Cyclopia31** [comment] 2023-12-04 19:05
Maybe this is the root of your problems, unfortunately I think seroperson (the Multiplayer master guy !) can't help you here because most logs are cleared when loading a game: the logs when you encountered the sync issue are lost if you didn't save them before trying to reload the game :/

**Comment by vaderkos** [comment] 2023-12-04 19:24
> Maybe this is the root of your problems, unfortunately I think Seroperson (the Multiplayer master guy !) can't help you here because most logs are cleared when loading a game: the logs when you encountered the sync issue are lost if you didn't save them before trying to reload the game :/
> 
> I think you should add "Multiplayer" on your title.

Anyway, thx for helping ;D

**Comment by axatin** [comment] 2024-05-22 21:00
According to the game data England is already building the school of philosophy somewhere (for each civ the game stores a list of all the buildings currently under construction). That's obviously wrong, but I can't tell what causes the error, as it's wrong already in the turn of the savegame. Do you still have saves from earlier in the game?

**Comment by vaderkos** [comment] 2024-05-22 21:24
@axatin no, I don't. But I think it is specific to this version. It does not appear on 4.6.2. Maybe that is somehow connected to caravans problem. Sometimes you can' build caravan even there are available trade routes, or if you started building caravan game during desyncs messes up build queue, comletely removing peoduction invested by it, or in worse case changes queue to caravan. This is very frustrating especially if you are competing for some wonders, but had caravan problem in between. But this is very offtop for this thread

**Comment by axatin** [comment] 2024-05-23 15:00
I'll have a look at the caravan issue. This one seems to be specific to the game you were playing, maybe caused by some earlier desync. Can't be fixed without the previous saves.

**Closed by axatin** 2024-05-23 15:00 UTC
Labels: Multiplayer
