### ISSUE TITLE
Inca units idling on mountains

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1318] opened 2016-02-23 19:55 UTC
Version 2/17
I noticed a few times that the Inca would place a heavily wounded unit on a mountain and let it idle there for a very long time (in fact for as long as I had visibilty of the tile).
It looks like the AI has given the unit the "heal" command, but since units can no longer heal on mountains...

**Comment by LoneGazebo** [comment] 2016-02-23 20:01
Maybe you scared it, and it was playing dead?

**Comment by ilteroi** [comment] 2016-02-23 20:13
i see the problem. fix incoming

**Comment by LoneGazebo** [comment] 2016-02-23 20:24
@ilteroi, not to off-topic, but take a look at the "Tallying up units for" logs in the tacticalAI. Almost all functions are returning 0 for # of units found, especially naval operations. I think this may be why we're seeing limited efficacy for the AI right now.

**Comment by LoneGazebo** [comment] 2016-02-23 21:04
I'm working on it now. For some reason, actions that needed a water plot were passing in coastal land, not coastal water, which was -needless to say- bad.

**Comment by ilteroi** [comment] 2016-02-24 07:39
re: tallying up units ...

i just realized it's important to call NumberOfFillableSlots() with both a target plot and a muster plot, else it will fail. will fix tonight.

**Comment by LoneGazebo** [comment] 2016-02-24 14:53
Yeah, I've fixed that issue already ilteroi. Grab my latest before you start.

**Comment by LoneGazebo** [comment] 2016-02-24 15:27
Also: http://forums.civfanatics.com/showpost.php?p=14174880&postcount=21

This is a single case, but I can confirm over-eagerness by the AI to withdraw and heal. Too many withdraw/heal moves in the TacticalMoves pool? Considering that the AI usually has more than enough units to wage war, it might be fair to make the AI slightly more suicidal with its units.

**Comment by ilteroi** [comment] 2016-02-24 20:58
well, there are two conditions for healing:

- unit hitpoints below 20%
- unit has taken so much damage last turn that it would die next turn

as for not attacking the city, that can happen if the projected damage is less than 1/12th of the city hitpoints.

other news:
- just got a "don't settle near us" from arabia when in fact i settled _away_ from them
- adopted the authority finisher but got only one unit although 3 cities have >=8 citizens

**Comment by LoneGazebo** [comment] 2016-02-24 22:14
Hmm...re: not attacking city, I do wonder, though, why we see the 'no melee support, withdrawing' happening during operations that clearly have enough melee support.

**Comment by ilteroi** [comment] 2016-02-25 07:23
will check

**Comment by ilteroi** [comment] 2016-02-25 19:52
indeed something's not right.
```
299, Austria, Zone ID: 21, Area ID: 1166, Value: 15, FRIENDLY Str: 142560 (11), Ranged: 691200 (1), ENEMY Str: 93078 (11), Ranged: 9135335 (9), Closest Enemy: 0, Enemy, Land
299, Austria, Zone ID: 23, Area ID: 1158, Value: 5, FRIENDLY Str: 0 (1), Ranged: 691200 (1), ENEMY Str: 94518 (13), Ranged: 9135335 (9), Closest Enemy: 0, Enemy, Water

299, Austria, Zone ID: 21, Linz, Enemy  , Land  , WARZONE  Withdraw
299, Austria, Zone ID: 23, Linz, Enemy  , Water  , WARZONE  Withdraw

299, Austria, Using move TACTICAL_POSTURE_WITHDRAW for zone 21 (city Linz) - turn slice 8035
299, Austria, Using move TACTICAL_POSTURE_WITHDRAW for zone 23 (city Linz) - turn slice 8035

299, Austria, Using move TACTICAL_CLOSE_ON_TARGET for zone 21 (city Linz) - turn slice 8035
299, Austria, Using move TACTICAL_CLOSE_ON_TARGET for zone 23 (city Linz) - turn slice 8035
```
and this is the situation - austria was last to move, so they didn't lose any units since then:

![image](https://cloud.githubusercontent.com/assets/1358966/13332141/eb6400c8-dc00-11e5-982d-f54edb93b407.png)

- enemy ranged strength is way off
- why first withdraw and then close in?

**Comment by ilteroi** [comment] 2016-02-25 20:56
ouch. seems that ranged power is multiplied by 100 and melee power isn't?

**Comment by LoneGazebo** [comment] 2016-02-25 21:03
That seems wrong. Is that calculation happening in the tactical analysis map?

**Comment by ilteroi** [comment] 2016-02-25 21:29
yep. most definitely a bug. testing the fix right now

**Comment by ilteroi** [comment] 2016-02-25 22:06
also solved another enigma. new tactical postures depend on the previous turn's postures, but the postures were not being saved. saving and loading thus changed the behavior of the AI.

**Comment by ilteroi** [comment] 2016-02-25 22:27
pushed. seems to work.

**Comment by ilteroi** [comment] 2016-02-25 22:38
i think the "no melee support" messages are mostly harmless.

there are some zones which appear to contain multiple cities. originally only the first one was attacked, i changed it so that all of them are tested. if there are no units at all there, that message is what you get.

need to dig deeper why they are even listed as target, they may even be neutral?

**Comment by LoneGazebo** [comment] 2016-02-26 01:57
That's interesting. In the logs can we label 'neutral' cities as such?

**Comment by LoneGazebo** [comment] 2016-02-26 01:57
Thanks for tackling this!

**Comment by ilteroi** [comment] 2016-02-26 06:58
the neutral thing is just a theory at this point .. and ideally there should be only one city target per zone, so something is still a little bit off it think

**Comment by LoneGazebo** [comment] 2016-02-26 15:01
I'll give it a look as well.

**Comment by LoneGazebo** [comment] 2016-02-26 15:54
(Looking at github) in AddToDominanceZones, there is this line:

```
if(m_TempZone.GetTerritoryType() == TACTICAL_TERRITORY_ENEMY ||
	        m_TempZone.GetTerritoryType() == TACTICAL_TERRITORY_NEUTRAL ||
	        m_TempZone.GetTerritoryType() == TACTICAL_TERRITORY_FRIENDLY)
	{
```

**Comment by LoneGazebo** [comment] 2016-02-26 15:59
Other theory: the ::extend function in the tactical analysis map - is it possible that this function is expanding zone size to include multiple cities? Perhaps, instead of scaling zone size based on map size, we should scale it based on minimum city distance?

G

**Comment by ilteroi** [comment] 2016-02-26 18:18
it seems to be the case that some moves are not marked as "dominance zone moves" (IsDominanceZoneMove), causing the tactical AI to apply them to all targets at once and not per zone. so maybe not a problem.

also, all city targets are enemies, but of course not every enemy city is besieged at all times. i put in a check to bail if the zone around the city has enemy dominance. should clear up the logs.

just pushed my latest.

**Closed** 2016-02-28 23:07 UTC
Labels: Fixed for upcoming version, Paging Dr. Ilteroi
