### ISSUE TITLE
Morocco cant pillage trade units even at war

### ISSUE THREAD

**Issue by BiteInTheMark** [LoneGazebo/Community-Patch-DLL#5048] opened 2019-01-07 00:16 UTC
_1. Mod version (i.e Date - 4/23):_
12-18

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi Only but using it as Modpack

_3. Error description:_ 
Morrocos UA allows them to pillage trade units, even if they are not at war, with the exception, they are heading towards morrocan cities. This is fine, but morocco cant pillage those trade routes, if the owner of it declares war and I have to look at those trade units safely leaving my territory. I dont think this safety passage should still work, if the owner declares war.

_4. Steps to reproduce (optional):_
Heres the save, if you look into the log, you also can see at turn 312 Ashurbanipal pillaged my trade unit, even I have build Firaxite Materials (other issue I reported)
[Morocco cant plunder.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2731039/Morocco.cant.plunder.zip)

**Comment by bigcat88** [comment] 2019-01-07 12:08
Duplicate of this?
https://github.com/LoneGazebo/Community-Patch-DLL/issues/4757

**Comment by BiteInTheMark** [comment] 2019-01-07 12:41
Yes, but still not solved.
Can't pillage them, even if they are already turning home.

**Closed** 2019-01-08 22:10 UTC
Labels: Fixed for upcoming version
