### ISSUE TITLE
Settling With Pioneer Duplicates/Deletes Capital

### ISSUE THREAD

**Issue by vetox20** [LoneGazebo/Community-Patch-DLL#8036] opened 2021-06-12 15:14 UTC
_1. Mod version (i.e Date - 4/14):_

6-7-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Very weird one. When going to settle a city with a Pioneer in owned territory, it creates a "clone" city of my capital (Moscow) and the two just bug out. Capital population drops to 3, all buildings removed (but not) and the city does not function.

_4. Steps to reproduce (optional):_

Load save, and simply settle the pioneer where I have it placed.
[Pioneer_Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6642427/Pioneer_Bug.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bsesar** [comment] 2021-06-12 15:32
Duplicate of #7962 ?

**Comment by IanE9** [comment] 2021-06-12 18:45
> Duplicate of #7962 ?

Almost certainly. It's good that we have reproduction steps now though! Interesting that it happened again with Russia.

**Comment by LoneGazebo** [comment] 2021-06-17 01:58
@ilteroi found your Zebra

**Comment by ilteroi** [comment] 2021-06-17 06:28
cannot reproduce ... must be some other factor involved

**Comment by RockettSJ** [comment] 2021-06-17 07:05
I had this happen when I settled in some tiles that were already owned by myself. It's a long shot, but as soon as I used ingame-editor to make those tiles "free land", the settling worked as intended.

**Comment by ilteroi** [comment] 2021-06-17 07:16
ah, good hint ... got it

**Comment by vetox20** [comment] 2021-06-18 23:26
Just to add to this, i just encountered it again, but with an enemy Mayan city. You try and take one down, the other one bugs, disappears and barrages your guys invisibly.
![20210618191618_1](https://user-images.githubusercontent.com/82966157/122623673-07733180-d06b-11eb-972d-57e5e83340a0.jpg)

**Closed** 2021-06-21 02:09 UTC
Labels: Fixed for upcoming version
