### ISSUE TITLE
3/1 - Two civs military ships sharing the same water.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6320] opened 2020-03-05 04:01 UTC
_1. Mod version (i.e Date - 2/9):_
3/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Korea and the Zulus naval ships are sharing the same water space.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/75946778-aa4a7100-5e63-11ea-97e5-63b9e7869b32.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment] 2020-03-05 15:06
You said you wanted better melee combat for naval ships...

**Comment by HeathcliffWarriors** [comment] 2020-04-09 12:54
Duplicate of #6429

**Closed** 2020-04-09 12:54 UTC
Labels: Fixed for upcoming version
