### ISSUE TITLE
2/18 - Advisor Panel CTD

### ISSUE THREAD

**Issue by ASCII-Guy** [LoneGazebo/Community-Patch-DLL#6286] opened 2020-02-24 00:49 UTC
_1. Mod version (i.e Date - 2/9):_
2.18.3b

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Opening the advisor panel will sometimes crash the game.

_4. Steps to reproduce (optional):_
Open the advisor panel. The crash seems to happen at random.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4242810/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): [AutoSave_0070 BC-1200.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4242815/AutoSave_0070.BC-1200.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): [CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4242809/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment] 2020-02-24 01:45
Duplicate of #6242.

@LoneGazebo This crash has been happening for a while.

**Closed** 2020-04-16 16:04 UTC
Labels: CTD
