### ISSUE TITLE
Military deployment is still extremely threatening (when almost no units near borders)

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5804] opened 2019-11-06 12:41 UTC
_1. Mod version (i.e Date - 4/23):_
10/23

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) List Enhancements for VP (v 5)
(ui) Trade Opportunities for VP (v 8.1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v3)
Global - City State Airbases (v 4)
Improved Air Recon (v 1)
Promotion Flags EUI (v 1.2)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Religion Spread (Vox Populi) (v 1.0)

_3. Error description:_ 
Askia, who I've vassalized 16 turns ago, still thinks my military deployment is "extremely threatening" (-15 modifier) even though there hasn't been significant military near his borders for about 10 turns (see screenshot)...is this something that @HeathcliffWarriors has fixed already or a different problem?
For the last 5 turns the only military near / in his borders was a single Explorer; other units are at least 3 tiles away and also inside my borders (except civilian units).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![threatening](https://user-images.githubusercontent.com/30495439/68298845-5173f300-0092-11ea-9fbf-495305d3f327.jpg)

**Comment by HeathcliffWarriors** [comment] 2019-11-06 14:00
Nope, that's a new one. Not sure what the cause could be, unless you have additional units (like ships) off screen? Civilian units and scouts aren't supposed to be counted.

**Comment by HeathcliffWarriors** [comment] 2019-11-06 14:03
Hold on, think I got it. It's not updating the threat posture because the function simply ends before resetting the threat level if they've given you Open Borders, which is the case for any vassal player. Vanilla bug, will fix.

**Comment by HeathcliffWarriors** [comment] 2019-11-06 15:35
Should be fixed now. @UndeadDevel

**Closed** 2019-11-08 20:38 UTC
