### ISSUE TITLE
assyria is a perennial loser

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#951] opened 2015-12-18 15:57 UTC
maybe it's because the AI doesn't know how to use the siege towers effectively - in any case i've never seen assyria succeed, the are mostly defeated by the midgame.

so we should either redesign the UU, or improve the handling i guess

**Comment by Iamblichos** [comment] 2015-12-18 17:05
What are you noticing in game with the Siege Towers specifically? Not putting them in front of cities, not building them, not employing them, etc?

**Comment by Edaka** [comment] 2015-12-18 17:59
Last time I played against Assyria was a long time ago when AI units used to hang around owned cities instead of participating in wars. I'd notice huge groups of siege towers clumped around Assyrian cities, just sitting there. I'd say Assyria used to overproduce their UU, at least back then.

**Comment by ilteroi** [comment] 2015-12-18 18:42
they still do overproduce them. and they are useless for defense, except as cannon fodder.

**Comment by Der-Zorn-Gottes** [comment] 2015-12-21 11:54
Sorry for hijacking you thread, but there is another siege tower related issue I want to report:
When the mounted missle unit line finally upgrades to melee cav, you get to redistribute the accumulated XP among melee promotions.
The same should be done when the siege tower upgrades to trebuchet.

**Comment by ilteroi** [comment] 2015-12-30 20:45
how can we reduce the number of siege towers they will build?

also i suspect we need some additional checks in the code - it seems that AI is trying to use siege towers to attack units, which doesn't work.

**Comment by LoneGazebo** [comment] 2015-12-30 21:09
There's the buildsanity unit code in the buildingproductionAI. We should use that to make sure the AI is only building them if making a sneak attack army. I added a unit trait (I believe) that allows you to easily check in the DLL if a unit is a city attack only unit (instead of having to a promotion search). More details when I get to my PC later.

G

**Comment by ilteroi** [comment] 2015-12-30 22:24
wouldn't it be possible to change some flavor values so they don't even attempt to build them?

**Comment by LoneGazebo** [comment] 2015-12-30 22:29
Eh, even with lowered flavors, it'll still randomly build them. Best to use the sanity model to deal with it.

**Comment by ilteroi** [comment] 2016-01-03 21:04
well, thinking about it some more, it's not a very good UU if we have to try and prevent them from actually building it ...

**Comment by LoneGazebo** [comment] 2016-01-04 00:20
yeah, no joke.

**Comment by Iamblichos** [comment] 2016-01-07 00:11
I'd hate to see this unit gone. Such a strong city taker.  One of the best siege units for its era.

**Comment by Iamblichos** [comment] 2016-01-07 00:19
Here's an idea: how about redesigning them as a troop transport (like my transport mod). Allow ranged units to cargo on them and fire on them or melee units attack from siege tower. Give the siege tower extra combat strength if HasCargo().

**Comment by ilteroi** [comment] 2016-01-07 07:36
i like the idea but i dread the implementation

**Comment by Iamblichos** [comment] 2016-01-07 14:49
You mean getting the AI to actually use it as intended? Or perhaps give it some kind of unit stacking rule.

**Comment by LoneGazebo** [comment] 2016-01-07 16:16
Yeah, that'd be a chore to teach the AI. Blegh.

**Comment by Iamblichos** [comment] 2016-01-07 16:48
do we have a handy example with the aircraft carrier AI?

**Comment by LoneGazebo** [comment] 2016-01-07 17:19
Not really, as the question is 'why/when would a melee troop load in,' not 'it must in order to move.

**Comment by Iamblichos** [comment] 2016-01-07 20:19
It seems doable. Perhaps I should finally dig into the DLL. LIke if it's preparing a siege assault and within no more than 2 tiles adjacent.

**Comment by LoneGazebo** [comment] 2016-01-07 20:31
Well, we aren't necessarily going to change the siege tower to that, so I wouldn't get ahead of yourself (unless you desire to see the AI be able to do it anyways). Godspeed if you want to try.

G

**Comment by Iamblichos** [comment] 2016-01-08 17:05
Yeah I do desire them to use it since in my mod of your CP I have a plot damage for Ocean tiles for land units that cross them, and no terrain damage while unit IsCargo. So I have some desire to make the transport AI logic work properly.

**Comment by LoneGazebo** [comment] 2016-01-08 18:56
The logic works, but the AI will need to be taught how and when to do it.
G

**Comment by LoneGazebo** [comment] 2016-01-14 20:40
Closing thread, as this is more of a balance than an AI issue.

**Closed by LoneGazebo** 2016-01-14 20:40 UTC
Labels: help wanted
