### ISSUE TITLE
CTD on save load 4/20

### ISSUE THREAD

**Issue by John12000** [LoneGazebo/Community-Patch-DLL#4247] opened 2018-04-21 17:40 UTC
_1. Mod version (i.e Date - 4/23):_
4/20 with IamBlichos's hotfix from here: https://github.com/LoneGazebo/Community-Patch-DLL/issues/4216

_2. Mod list (if using Vox Populi only, leave blank):_
VP Full Version w/ EUI

_3. Error description:_ 
Game crashes to desktop when loading the save or any of the autosaves for that game.

_4. Steps to reproduce (optional):_
Just load any of the saves.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1934810/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

2 Autosaves before hard save:
[AutoSave_0234 AD-1620.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1934807/AutoSave_0234.AD-1620.zip)

[AutoSave_0235 AD-1625.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1934806/AutoSave_0235.AD-1625.zip)

Hard save:
[Lehomo_0236 AD-1630.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1934808/Lehomo_0236.AD-1630.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1934805/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by Infixo** [comment] 2018-04-21 23:00
I am not sure this fix is save-game compatible, there are some DB changes after all.
Start a new game, do few turns and try to reload. See if the problem still exists.

**Comment by LoneGazebo** [comment] 2018-04-22 02:31
@Infixo database changes are savegame compatible (they don't always update the database, but they don't break so long as you don't add entirely new entries).

**Comment by Iamblichos** [comment] 2018-04-22 02:51
Some tables you can add entirely new entries. If it’s a table that has enums, it can often break save game compatibility.

**Comment by John12000** [comment] 2018-04-22 03:38
I added the hotfix before I started this save.

**Comment by John12000** [comment] 2018-04-22 11:45
I'm not using any of the hotfixes Gazebo released in the 4/20 release thread. Just the initial 4/20 release and the Iamblichos fix from Github.

Also I just did a new game to turn 50 and reloaded it with no crash, however the game I uploaded above was doing fine for a save I made on turn 212:
[Lehomo_0212 AD-1510.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1935521/Lehomo_0212.AD-1510.zip)

Are the hotfixes save game compatiable? If so I may just reinstall the mod with the latest hotfix. As well as reinstall Civ and switch the hard drive it's installed on to see if any of that fixes it.

**Comment by Infixo** [comment] 2018-04-22 23:39
I was able to load your save file from turn 212 and play with no issues. Using VP 4-20-4 version.
[Lehomo_0215 AD-1525.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1936227/Lehomo_0215.AD-1525.zip)

I was not able to load turn 236.

**Comment by Infixo** [comment] 2018-04-23 00:03
Breaks in CvTeam.cpp on line 9498

`CvInfosSerializationHelper::ReadHashedDataArray(kStream, m_aiForceTeamVoteEligibilityCount, GC.getNumVoteSourceInfos());`

**Comment by LoneGazebo** [comment] 2018-04-23 01:03
@infixo that’s a weird place to crash, I don’t think we’ve added any new memory variables to cvteam in a long time.

**Comment by Infixo** [comment] 2018-04-23 02:42
Yeah, I know. A desync probably is way before that.
But assuming that bith saves were done using the same .exe then the problem lies within those 20 turns. The game must have produced some data that were saved but couldn’t be read. If this is the situation then there could be more crashes like this, we’ll see.

**Comment by John12000** [comment] 2018-04-24 12:34
Is there any more info that you need from me? It appears my save is completely toast. Which is fine. I've started over many times, but I don't want to start over just to have it happen again.

**Comment by Jotaro31400** [comment] 2018-04-24 13:04
I've got the same issue but I couldn't load my save, I will upload my save when I m home.

**Comment by Infixo** [comment] 2018-04-24 13:07
@John12000 I suggest you install the latest hotfixed VP i.e. 4-20-4. I was able to load and play your save from T212. Then just play and pay attention to what @bigcat88 wrote in #4268 (I'm not saying this is an issue, has not beed confirmed as of now). Also, set autosaves to every turn and if a CTD happens again then post the save file from the last turn you were playing. The point is that we need to be able to recreate a CTD to debug it.

**Comment by John12000** [comment] 2018-04-24 14:40
Ok so I went back to turn 212, the save that you were able to play Infixo. I had the game autosave every turn from turn 212 to turn 236 the turn that I couldn't load my save. The save crashes on turn 229, which is when one of Mongolia's cities revolts. I can load the autosave before the revolt, but not any of the saves after the revolt.

Turn 228:
[AutoSave_0228 AD-1590.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1943212/AutoSave_0228.AD-1590.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1943213/Logs.zip)

Turn 229:
[AutoSave_0229 AD-1595.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1943221/AutoSave_0229.AD-1595.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1943220/Logs.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1943219/CvMiniDump.zip)

I'm also going to install the latest hotfix as suggested and see if the 2 saves uploaded above will load.

**Comment by John12000** [comment] 2018-04-24 14:47
Also I wasn't sure if I'm supposed to clear the logs folder each time, so here is the full log from my turn 212 to turn 236.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1943278/Logs.zip)

**Comment by Jotaro31400** [comment] 2018-04-24 14:55
1. Mod version (i.e Date - 4/23):
4/20 version 4

2. Mod list (if using Vox Populi only, leave blank):
VP 
Infox EUI improved
less ice on the map
less warmonger
More unique component
reforestation
really advanced setup ( removed venise as AI ) 
Infox' UI filter in trade route 

(None of the extra mod brought those issue with 4-4 version ) 

3. Error description:
Game crashes to desktop when loading the save or any of the autosaves for that game.

4. Steps to reproduce (optional):
Just load any of the saves.


[Replay&CivMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1943324/Replay.CivMiniDump.zip)

I can't load any save, you have the mini dump with it

**Comment by John12000** [comment] 2018-04-24 15:50
Updated to the latest version 4-20-4 and the save still crashes on load for turn 229 and any save after, and doesn't crash for turn 228 and any save before.

Jotaro31400 did you or any of the AI have any city revolts? It seems bigcat88 from https://github.com/LoneGazebo/Community-Patch-DLL/issues/4268 and I both started having issues with loading our saves after there was a city revolt.

**Comment by Infixo** [comment] 2018-04-24 16:36
The game certainly produces a corrupted save file at some point - gamecore.log has tons of "type not found hash" errors when trying to load such a file. Looks like it is related to revolts.

**Comment by Infixo** [comment] 2018-04-24 19:32
@John12000 @bigcat88 
Below is a DLL with a fix. I tested it on @John12000's file from Turn 228. Got a revolt, then saved and loaded again with no problems.
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1944278/CvGameCore_Expansion2.zip)
You also need to change one UI file because I made a fix that is not yet released. But this is unrelated to CTD, simply if you want to play further you should change this file because otherwise the diplo window will be broken.
[DiploGlobalRelationships.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1944292/DiploGlobalRelationships.zip)

**Comment by Infixo** [comment] 2018-04-24 19:35
@Jotaro31400 Try out the above fix. I was not able to load files because I don't have required mods. If your issue is related to revolts then you should have it fixed.

Important: you need to apply the fix BEFORE any city would revolt. Once the city revolted, the internal game data becomes corrupted and you cannot take it back.

**Comment by Infixo** [comment] 2018-04-24 19:45
Explanation
CvTeam class keeps the members in m_members vector, but also there's a variable m_iNumMembers that keeps how many there are. 
When a city revolts the game looks for a free team ID and a player ID. Eventually team is ignored, and the game uses the team pre-assigned to a free player ID. 
Then the game adds a new player (that used to be a revolted city) to the team. It increases m_iNumMembers and calls CvTeam::addPlayer(). And here is the problem: addPlayer actually doesn't add a player because it's already there, pre-assigned. All ends in in a state where m_iNumPlayers = 2 but m_members.size() = 1.
When saving, the Write function writes to a save file 2 (m_iNumMembers) and outputs only 1 member from m_members. When reloading, the game reads 2 members thus making a desync in the input stream. The crash happens some time later and as usual in such cases is totally unrelated to members.

**Comment by Infixo** [comment] 2018-04-24 19:46
Fix
addPlayer returns a bool that tells if player was really added. Depending on that, m_NumMembers is either increased or decreased thus always being in sync with m_members.size().

**Comment by LoneGazebo** [comment] 2018-04-24 20:10
@Infixo that makes sense - wonder why I'm saving and loading without issue? Very strange.

**Comment by LoneGazebo** [comment] 2018-04-24 20:12
@Infixo we'll need a method to check against preexisting CSs that have revolted (for a retroactive hotfix solution), no?

**Comment by Infixo** [comment] 2018-04-24 20:25
I posted info in the forum, we'll see if the problem affects many people. As for now there are 2 confirmed cases and maybe 2 other. 
Maybe it's better to just release a hotfixed version asap and don't allow it to spread into many games.

**Comment by LoneGazebo** [comment] 2018-04-24 20:43
@Infixo i intend to hotfix ASAP, though I do think we could make nummembers = 1 for the hotfix as a safety

**Comment by Infixo** [comment] 2018-04-24 20:51
If you want to do so, then one line in CvTeam needs a change.
After reading m_iNumMembers use std::min(...,1)
Cannot just set it to 1 because 0 is actually valid. I wrote in explanation that a new team is searched but ignored. Alas, init() is called for it and it resets the members to 0. This is then written into a file and it’s ok, there are no problems reading it.

**Comment by LoneGazebo** [comment] 2018-04-24 20:53
I think we should, at least for the hotfix. I'll make the change. I still can't figure out why I'm saving/loading on my end okay...

**Comment by Infixo** [comment] 2018-04-24 21:18
I comment on that in the other thread.
The issue is only with City-States, i think. If a city revolts and join somebody, no new team is needed and the faulty code is not executed.

**Comment by John12000** [comment] 2018-04-25 04:46
Ok looks like the 2 files above fixed the issue.

**Comment by bigcat88** [comment] 2018-04-25 15:04
In new version all is fine, check load after revolt - no crashes.

**Closed** 2018-04-28 16:54 UTC
