### ISSUE TITLE
machine gun promotion

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4382] opened 2018-05-14 17:58 UTC
does anyone need the "cover fire" promotion? is that a vanilla thing or where does it come from?

![image](https://user-images.githubusercontent.com/1358966/40014332-8fcef29e-57b0-11e8-8839-2c8c6044eee6.png)

i stumbled on it because it's very very bad for performance.

rule of thumb: do not implement something which forces you to iterate over all enemy players a million times per turn.

anyway i feel a similar effect could be had by giving a defense bonus to adjacent friendly units.

**Comment by ilteroi** [comment] 2018-05-14 18:14
in any case these area effect promotions are a problem for the AI. we have special code for generals and the like, but tactical combat doesn't consider the effect.

**Comment by LoneGazebo** [comment] 2018-05-14 19:51
It is vanilla code. The promotion is on the modern era and up ranged units.

**Comment by LoneGazebo** [comment] 2018-05-14 19:59
as @Iamblichos noted, I don't see any reason why we can't use the improved AOE evaluation cache for this, even in the tactical AI.

**Comment by Iamblichos** [comment] 2018-05-14 19:59
err.. I meant that ReverseGreatGeneral function.

**Comment by Iamblichos** [comment] 2018-05-14 19:59
But all these feed into one area effect function now.

**Comment by Iamblichos** [comment] 2018-05-14 20:02
Basically I would all ReverseGreatGeneral functions IsNearbyPromotion area effect units in the same place that we want to put generals. They can't stack, but we should swap out with the unit that is there unless it is front line and the unit we would be swapping with has a combat strength we need.

**Comment by Iamblichos** [comment] 2018-05-14 20:03
that is, if the RGG or INP is a combat unit and not a civilian.

**Comment by LoneGazebo** [comment] 2018-05-14 20:19
Yeah - I'd rather not start chopping features for performance if we can reasonably get them to fit into the existing structure.

**Comment by LoneGazebo** [comment] 2018-05-14 20:36
FYI @ilteroi @Iamblichos @davenye I'm going to upload the merged master soon, it's got all of your changes merged in. Because there were merge conflicts I had to do it manually - please _please_ take a minute and compare the code to yours, make sure that your intended changes made it into master. I've done my best to triple-check things but mistakes can happen!

**Comment by Iamblichos** [comment] 2018-05-14 20:49
For sure, and I will certainly try and make this whole lot easier for you in the future (my first time managing a branch within a master, so my apologies).

**Comment by LoneGazebo** [comment] 2018-05-14 20:53
no worries @Iamblichos it wasn't just that - you and @ilteroi were inadvertently altering similar blocks of code, so there would have been conflicts regardless.

**Comment by ilteroi** [comment] 2018-05-14 20:57
it's probably best to give it some time to settle ... a lot of changes on my end. just pushed another fix

**Comment by Iamblichos** [comment] 2018-05-14 20:59
Yeah, a long conversation on Steam about Sappers and CityAttackSupport launched a whole series of code writing and code performance that mainly @ilteroi did. I mean this next version should be hot, assuming we don't have too many bugs.

**Comment by LoneGazebo** [comment] 2018-05-14 21:01
saw your fix @ilteroi.

Just pushed merged version. I too made some performance improvements. We shall see! Please take a look at the uploaded commit, see if you see anything that sticks out or is missing.

**Comment by Iamblichos** [comment] 2018-05-14 21:03
@LoneGazebo, hopefully you went with @ilteroi's code because his is a modification (and simplification) of my initial write up. But I will report back here if need be.

**Comment by LoneGazebo** [comment] 2018-05-14 21:04
Where it was overwritten by Shiny I went with Shiny (per your convo) - where it was new from Iamblichos and not on Shiny I added from Iamblichos (and vice-versa)

**Comment by Iamblichos** [comment] 2018-05-14 21:35
@LoneGazebo all good on my end.

**Comment by LoneGazebo** [comment] 2018-05-14 21:38
cool, that's a good sign then that I didn't fuck anything up

**Comment by Iamblichos** [comment] 2018-05-14 22:05
That's a good feeling!

**Comment by Iamblichos** [comment] 2018-05-14 22:16
Okay, so I just deleted my branch and recreated  it (too many commits in there that aren't mine) so I'm not starting with one fresh commit ahead of master. Not necessary for release.

**Comment by ilteroi** [comment] 2018-05-15 17:49
i merged back into my branch, only relatively few conflicts, seems good. testgame running ...

**Comment by Iamblichos** [comment] 2018-05-16 09:43
Whew. Damn. Was this incremental up to 110 GB. Or did that file size come out of no where?

**Comment by Iamblichos** [comment] 2018-05-16 10:44
@LoneGazebo do you know which commit that changed autosaves? I know there was something that was done there recently...

**Comment by ilteroi** [comment] 2018-05-16 10:51
well, that's not a new thing i think. i had that a few weeks back and started getting disk full notifications during autoplay.

but it happened only once and never again, so i dismissed it ...

**Comment by LoneGazebo** [comment] 2018-05-16 13:53
@ilteroi any idea which release it happened after?

@iamblichos I don’t know, I was away and came back to find it. It was essentially eating all available space on c:

**Comment by ilteroi** [comment] 2018-05-16 14:03
unfortunately i can't remember ... but can you reproduce it? in that case it should be a simple matter of breaking into the debugger to see what it's doing. 

it's probably some sort of circular reference in a data structure. might also be possible to add some flags for "already written" and break if it's being written a second time.

**Comment by LoneGazebo** [comment] 2018-05-16 14:46
I’ll see if I can replicate. I had the debugger and Very Sleepy hooked into the game and neither threw a red flag...

**Comment by ryanmusante** [comment] 2018-05-17 01:51
Vladimir Panteleev's fork has a lot of new fixes: https://github.com/VerySleepy/verysleepy

**Comment by LoneGazebo** [comment] 2018-05-17 05:28
@ilteroi still seeing pretty common crashes here:

![image](https://user-images.githubusercontent.com/7849458/40158280-8eef9e7e-5971-11e8-9fdd-7c66e4a419df.png)

The fact that it's happening straight out of DLLgame makes me think it might be the interface doing this?

**Comment by ilteroi** [comment] 2018-05-17 06:33
that callstack makes no sense. probably something wrong with it. read the disclaimer ...

**Comment by Iamblichos** [comment] 2018-05-17 13:04
I tried to reproduce the autosave issue (I autosave every turn), couldn't reproduce it. Do you know where autosaves are handled in the DLL?

**Comment by LoneGazebo** [comment] 2018-05-17 14:15
I know @ilteroi it is weird and incomplete. But it is happening somewhat often in the late game. I’ll see if I can pin it down further.

**Closed** 2018-05-23 23:47 UTC
Labels: Need more information
