### ISSUE TITLE
5/5 - Hard CTD

### ISSUE THREAD

**Issue by TooManyCords** [LoneGazebo/Community-Patch-DLL#7838] opened 2021-05-09 04:27 UTC
_1. Mod version (i.e Date - 4/14):_ 5/5 (second hotfix I think)

_2. Mod list (if using Vox Populi only, leave blank):_Full VP + 3/4UC + better lakes + Wonders Expanded + World Congress Reformation

_3. Error description:_ Tried multiple paths, always crashes on the same turn. I hope this is fixable, I rarely enjoy playing Germany, but this one seems fun

_4. Steps to reproduce (optional):_Open game. Get crash.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6446937/Logs.zip)
[Bismarck_0279 AD-1295.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6446939/Bismarck_0279.AD-1295.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment] 2021-05-09 19:21
Closing - duplicate of #7835

**Comment by LoneGazebo** [comment] 2021-05-10 02:15
Please zip other mods from mods folder and upload.,

**Comment by TooManyCords** [comment] 2021-05-10 03:34
Did you want me to zip the whole mod folder? It would be quite large.

![ModList](https://user-images.githubusercontent.com/26443204/117602524-85f8bd00-b116-11eb-94ca-cb0c83527868.png)

These + World Congress Reformation (v8)

**Comment by LoneGazebo** [comment] 2021-05-10 03:56
Yeah. You can leave out the specifically VP ones.

**Comment by LoneGazebo** [comment] 2021-05-10 22:28
https://github.com/LoneGazebo/Community-Patch-DLL/files/6452252/CvGameCore_Expansion2.zip

**Comment by LoneGazebo** [comment] 2021-05-10 22:28
Try this DLL.

**Closed** 2021-05-14 16:48 UTC
Labels: CTD
