### ISSUE TITLE
Enemy melee units retreating when engaged by player melee units

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#1970] opened 2016-06-16 02:11 UTC
Bug Report Template

Mod Version (i.e Date - (4/23b)):
June 14th beta

1. Mod List (if using standard CPP set, leave blank):
+FlagPromotions v7
+InfoAddict v22

2. Type of error (i.e. crash, interface bug, AI quirk): 
When you move a melee unit more than 1 tile to engage an enemy melee unit the enemy unit is pushed to another tile with no damage taken.
Doesn't occur when melee is engaged from an adjacent tile.

3. Steps to reproduce:

4. Additional information:
Possibly related to #1959 

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment] 2016-06-16 02:14
This is probably a consequence of the head mission breaking that I just updated in the 6/15 version. Try that and report back.

**Comment by GrantSP** [comment] 2016-06-16 02:51
Might need to change that label. Just installed the hotfix and this is still happening.

**Comment by LoneGazebo** [comment] 2016-06-16 03:31
Sounds like something related to @ilteroi's head mission changes. I'll leave it to him.

**Comment by LoneGazebo** [comment] 2016-06-16 03:42
I just tested, and cannot reproduce. I'm reuploading the hotfix, let's see if this fixes it.

**Comment by GrantSP** [comment] 2016-06-16 03:53
Be sure to initiate melee from at least 2 tiles away.

**Comment by LoneGazebo** [comment] 2016-06-16 04:30
I did.

**Comment by ilteroi** [comment] 2016-06-16 06:36
are you sure this isn't a unit with the "heavy charge" promotion? or the defender is an atlatlist who can flee from melee?

**Comment by holder85** [comment] 2016-06-16 08:06
I experienced too this bug. when I attacked babarian with my warrior. they just 'jump' to 1 tile away and take no damage.

**Comment by GrantSP** [comment] 2016-06-16 08:09
Definitely not a "heavy charge" promotion or because the enemy is an atlatlist.
I've seen, am still seeing, it with all the melee units up to tercios, horsemen to knights and even with trireme/caravels.

**Comment by holder85** [comment] 2016-06-16 11:07
I got it!! this bug occur in this situation.
please look at these screenshots.

![civ5screen0001](https://cloud.githubusercontent.com/assets/19889762/16114664/62e4ebea-33fd-11e6-8068-0e56a9299f25.jpg)
![civ5screen0002](https://cloud.githubusercontent.com/assets/19889762/16114671/6829753a-33fd-11e6-8852-8b0a0e5564a4.jpg)

that is, when Player command unit to attack the enemy unit where not in adjacent tile, The enemy unit just jump to adjacent tile.

**Comment by cdanger341** [comment] 2016-06-16 11:51
I do not have screenshots for proof, but I have been experiencing this same behavior. The problem is that it is not consistent. Sometimes I can attack with a melee unit from 2+ tiles away and everything works as normal, but other times the defending unit moves 1 tile away and takes no damage. I have experienced this behavior with all melee units (warriors, spearmen, tiremes, horsemen, barbarians, etc.). This is most noticeable in the early game when fighting barbarians, as currently I can "clear" their camps simply by attacking them from 2 hexes away and pushing the defending barbarians off.

**Comment by LoneGazebo** [comment] 2016-06-16 14:54
I've tried dozens of permutations of this, and I can't get it to reproduce. You all are on 16-5-1, yes?

**Comment by F0rst1** [comment] 2016-06-16 15:02
In the previous version attacking from non-adjacent tile caused the attacking unit to stop before attacking and you had to make the attack command again from the adjacent tile. I was wondering, if this bug could be related to that. Is it possible that for some reason the attack command doesn't take place while the unit isn't adjacent to the defending unit but for some reason nothing stops the unit from moving to the tile where the defending unit already is?

**Comment by LoneGazebo** [comment] 2016-06-16 15:07
Not sure, but I've tried dozens of different scenarios a few times and no bugs seen. Make sure you are all on 6-15-1.

**Comment by cdanger341** [comment] 2016-06-16 16:02
Yes, I am using 6-15-1 because prior versions were causing the CTD bug and I could not play beyond the first few turns. I am noticing the same thing as F0rst1. In versions prior to 6-14, if I selected a melee unit and then selected a non-adjacent enemy unit to attach, the game would just move my unit to be adjacent to enemy unit. I would then have to select the enemy unit again to actually attack it. In 6-15-1 my melee units are moving and attacking in a single click, BUT sometimes this is leading to the "move the enemy away instead of attacking them" issues reported here. Otherwise the melee unit moves and attacks in a single fluid action.

One thing I have not seen discussed:

Who of us has attack animations turned on? That is, who is and who is not using the Quick Attack options?

I always leave Attack and Movement animations turned on (I like the visual feedback of this combined with RED modpack). Are the developers testing with animations turned off? I'm wondering if that may be where the issue lays...

**Comment by LoneGazebo** [comment] 2016-06-16 16:22
Yes, animations are off. Could be. I'll check.

**Comment by LoneGazebo** [comment] 2016-06-16 17:13
Alright, yep, that's it. Animations are the problem, but I have no idea why. @ilteroi quick movement, not quick combat, seems to be the issue.

**Comment by LoneGazebo** [comment] 2016-06-18 01:15
@ilteroi  see: https://github.com/LoneGazebo/Community-Patch-DLL/issues/1980 and https://github.com/LoneGazebo/Community-Patch-DLL/issues/1987

**Comment by LoneGazebo** [comment] 2016-06-18 01:15
There's definitely something odd going on here.

**Comment by ilteroi** [comment] 2016-06-18 06:41
i think i have an idea but i'm on the road right now. will check tomorrow

**Comment by LoneGazebo** [comment] 2016-06-18 07:49
No worries, take your time.

**Comment by ilteroi** [comment] 2016-06-19 21:10
ok - turns out when animations are enabled, movement is not executed directy but queued. ok so far, but the UnitAttack call was only made when there's no queued move. the de-queing never happened, so normal moves were made instead of attacks.

apparently i broke the "publishing" of the queued moves a while back and never noticed cause i have animations off. don't know where it was supposed to happen, but anyway, it seems to work now. ended up changing a bit more than i expected ... so i don't trust it yet, mind giving it a spin?

there is one problem i found: a DOW air strike on an enemy settler crashed the game - but inside Civ5.exe not in the DLL. don't know what to do about this - anyway couldn't reproduce it.

**Comment by LoneGazebo** [comment] 2016-06-19 22:48
Alright, merged and testing. Getting a consistent turn 0 CTD when cycling through AI turns to Turn 1. As soon as the barbarian processing is over it is crashing here:

![untitled](https://cloud.githubusercontent.com/assets/7849458/16180262/79c6f74c-364e-11e6-8399-7c2cd40c1822.png)

**Comment by LoneGazebo** [comment] 2016-06-19 22:54
I'll upload my merge shortly so you can look at it and try to reproduce.

**Comment by LoneGazebo** [comment] 2016-06-19 23:13
Alright, 6/19 version uploaded. Let me know if you have any ideas. I did merge VMC 68 of Whoward, but he doesn't touch random in his latest versions.

**Comment by LoneGazebo** [comment] 2016-06-20 01:45
@ilteroi, also, limited (pre-CTD) testing shows that latest version attacks from one tile away queue up the attack before the move, thus the unit will attack from two tiles away, then move up. Probably should be resolved in the opposite order?

**Comment by ilteroi** [comment] 2016-06-20 05:56
it crashes on writing to the stream? that's a new one ... must be the autosave

**Comment by LoneGazebo** [comment] 2016-06-20 13:59
I'll try. Odd that it is crashing in random, as that code is the same as yours. I'll look at reverting whowardand and see how it goes. Your change seemed to work except for the reversed resolution of mice and attack animations.

**Comment by LoneGazebo** [comment] 2016-06-20 16:13
Alright, CTD solved. Your change seemed to work except for the reversed resolution of moves and attack animations, so yay!

**Comment by LoneGazebo** [comment] 2016-06-20 20:22
@ilteroi, another fun quirk: it seems that issues with the missions are also causing duplication of trade units. This code is running twice for all AI trade units, resulting in AI trade units duplicating every time they the AI makes a trade unit:

else if (pkQueueData->eMissionType == CvTypes::getMISSION_ESTABLISH_TRADE_ROUTE())
			{
				CvPlot* pPlot = GC.getMap().plotByIndex(pkQueueData->iData1);
				CvAssertMsg(pPlot, "pPlot is null! OH NOES, JOEY!");
				if (pPlot)
				{
					if(hUnit->makeTradeRoute(pPlot->getX(), pPlot->getY(), (TradeConnectionType)pkQueueData->iData2))
					{
						bAction = true;
					}
				}
			}

**Comment by LoneGazebo** [comment] 2016-06-20 20:22
Line 1753 of UnitMission.cpp

**Comment by ilteroi** [comment] 2016-06-20 20:41
just stepped through it twice - no problem so far. hmm.

**Comment by LoneGazebo** [comment] 2016-06-20 21:19
If the AI makes a trade unit, and then sends that unit on a mission, it will do so twice.

bool CvGameTrade::CreateTradeRoute(CvCity* pOriginCity, CvCity* pDestCity, DomainTypes eDomain, TradeConnectionType eConnectionType, int& iRouteID) is called twice with two different RouteIDs for one trade unit, thus duplicating the trade unit. It doesn't always do it, but it does it consistently enough to drive up caravan/cargo ship amounts well over the limit.

**Comment by ilteroi** [comment] 2016-06-20 21:29
yeah i've seen it now. quite rare actually, don't know what's different in those cases ...

**Comment by LoneGazebo** [comment] 2016-06-20 21:33
It is relatively rare, but occurs often enough in a large game to horribly bloat trade unit numbers. Any idea why the mission is doubling? Is it just not getting cleared out in time?

**Comment by ilteroi** [comment] 2016-06-22 06:26
turns out i'm innocent this time :)

somebody put this code into ExecuteTradeUnitMoves():

		//if we already made 3 routes from here this turn, then skip it
		if (originCities.find(aTradeConnections[ui].m_iOriginID)!=originCities.end())
			iDupes++;

where previously only one route was allowed. and unfortunately canCreateTradeRoute() did not check if the unit is a zombie. so we would happily create up to 3 routes with the same unit.

**Comment by ilteroi** [comment] 2016-06-22 06:33
also note that the added code does not necessarily do what the comment says: it allows up to 3 dupes in total, not per city. but that's mostly irrelevant.

come to think of it, i would avoid a hard cap and allow dupes if the route is much better than the alternative.

**Comment by LoneGazebo** [comment] 2016-06-22 14:04
Oh no! It was me. Hmm. That code is a lie then.

**Comment by LoneGazebo** [comment] 2016-06-22 14:05
Any update on getting animations to fire in the proper order?

**Comment by ilteroi** [comment] 2016-06-22 14:27
yeah is fixed. still need to sort out the "next turn" problem though

**Comment by LoneGazebo** [comment] 2016-06-22 14:28
Cool. I'll fix the TR issue and clear out the rest of the rabble.

**Closed** 2016-06-26 03:24 UTC
Labels: Fixed for upcoming version, Paging Dr. Ilteroi
