### ISSUE TITLE
4/17 - Cannot end turn mid-game because "Next Turn" button is not working

### ISSUE THREAD

**Issue by sqrt93** [LoneGazebo/Community-Patch-DLL#6573] opened 2020-05-01 10:12 UTC
_1. Mod version (i.e Date - 4/17):_

4/17 (https://mega.nz/folder/2Jdw3aQT#Z49gV7KAyMq6YiG5BD9jaA)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  

I cannot end my turn mid-game because the "Next Turn" button is not working.

_4. Steps to reproduce (optional):_

- Load attached savegame
- Try to end turn. It doesn't work.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4563428/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Ramkhamhaeng_0232 AD-1610.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4563421/Ramkhamhaeng_0232.AD-1610.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment] 2020-05-01 11:51
duplicate of #6523

**Closed** 2020-05-01 11:51 UTC
