### ISSUE TITLE
Magical Air Units that teleport to different cities

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#6800] opened 2020-07-10 13:41 UTC
_1. Mod version (i.e Date - 4/17):_

June 19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Sending my air units to a particular city as usual in order to make a strike or whatever.  On the next turn...they're not there anymore.  Instead, they've appeared in another city somehow.  My city with air units was not attacked or anything.

Sometimes they don't move - on one turn, I made an attack with a bomber, and then the turn after the same wounded bomber is somehow in another city elsewhere in my empire.

_4. Steps to reproduce (optional):_

Just use Bombers I guess?  I have no idea what's going on.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by paramenides** [comment] 2020-07-12 04:31
My planes are disappearing completely, not shuttling to other cities. This is a very bad bug.

**Comment by Vyyt02** [comment] 2020-07-14 11:16
@paramenides , this is a bug from the April version (I suppose you have not updated to the June one?). And I worry that what @Gidoza is describing is caused by a fix to that bug.

**Comment by ilteroi** [comment] 2020-07-14 19:10
duplicate of #6725 

i think it's high time for a new release? or maybe a point fix at least

**Comment by RecursiveVision** [comment] 2020-07-15 16:03
@ilteroi If you push your code I'll merge it with my changes to make sure everything is compatible.

Sorry for sort of hijacking your branch by the way, I was anticipating Gazebo was about to merge it, but I guess he got busy

**Comment by ilteroi** [comment] 2020-07-15 17:27
no biggie, i can always invent new names :)

anyway merging is not a problem but making a releae with database changes is.

**Comment by paramenides** [comment] 2020-07-16 05:14
Oops, uh, no i am using the june one 6-19-2. Again for me, the planes just disappear. It might have something to do with stacking, but maybe not. I have had 6 planes vanish.




On Tuesday, July 14, 2020, 4:17 AM, Vyyt <notifications@github.com> wrote:




@paramenides , this is a bug from the April version (I suppose you have not updated to the June one?). And I worry that what @Gidoza is describing is caused by a fix to that bug.

**Comment by RecursiveVision** [comment] 2020-07-16 18:23
@ilteroi Gazebo hath returned: https://forums.civfanatics.com/threads/new-official-version-june-19th-6-19.659579/page-25#post-15838038

**Comment by RecursiveVision** [comment] 2020-07-16 19:42
@LoneGazebo I've carefully merged all of @ilteroi's changes into the ole branch, to avoid any conflicts between our files.

**Comment by ilteroi** [comment] 2020-07-28 07:58
duplicate #6725

**Closed by ilteroi** 2020-07-28 07:58 UTC
