### ISSUE TITLE
Civs spawn close together on map even when room exists to spread them out

### ISSUE THREAD

**Issue by dylansan** [LoneGazebo/Community-Patch-DLL#10558] opened 2024-01-02 22:29 UTC
_1. Mod Version (4.4.2). Current Version: 4.4.2_

_3. List of Other Mods_
(1) Community Patch (v. 126)
(2) Vox Populi (v. 17)
(3a) VP - EUI Compatibility (v. 1)
(4a) UI - Promotion Tree for VP (v. 23)
(over) More Unique Components  for VP (v. 87)
(text) Alternative Component Names for VP (v. 13)
(text) Promotion Overhaul for VP (v. 45)
(ui) Meaningful Colours (v. 15)
(ui) Trade Opportunities for VP (v. 21)
(ui) Wonder Planner for VP (v. 14)
+Fast Animations+ (v. 501)
=Furious Turns= (v. 1)
Squads for VP (v. 2)
UI - Destination (v. 4)
UI - Improved City View (VP) (v. 20)
UI - Map Pins (v. 17)
UI - Small Resource Icons (v. 4)
UI - Upgrade Tree (v. 9)
WH - Military Log for VP (v. 2)

Map Type: Tectonic - VI

_4. Describe the Issue_
Others have noticed something similar: The way civs are distributed across the map seems to be clustering some of them close together while the rest are spread out. In the attached screenshot, 4 of the 8 civs on this standard-size map have their capitals on one landmass, along with at least three city-states. Meanwhile, I spawned on my own continent with only one nearby city-state.

I'm using the Tectonic map script but I'm not sure what others are using.

Links to other players with similar behavior:
https://forums.civfanatics.com/threads/new-beta-version-4-4-2-december-31-2023.687367/post-16550878
https://forums.civfanatics.com/threads/new-beta-version-4-4-2-december-31-2023.687367/post-16551058

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

Saves from turn 0, and turn 545 (same as screenshot):
[VP012_4.4_RamKhamhaeng_0000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13814334/VP012_4.4_RamKhamhaeng_0000.zip)
[VP012_4.4_RamKhamhaeng_0545.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13814332/VP012_4.4_RamKhamhaeng_0545.zip)

_9. Screenshots of the Issue (Optional)_

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/22200358/ac4c41c6-5f53-42a5-8b56-e9b723c59184)

**Comment by azum4roll** [comment] 2024-01-03 00:59
For Tectonic, you need to pick the region division method in the options for different map types. Ask @n-core for details.

**Comment by Hokath** [comment] 2024-01-03 06:03
I've seen large regions of empty space in Oval and Pangea also, but not an expert so couldn't tell you if that is normal.

**Comment by azum4roll** [comment] 2024-01-03 06:18
The issue is overlapping regions, but OP doesn't have this problem.

**Comment by dylansan** [comment] 2024-01-03 19:10
Hm, okay. I chose a lot of random settings for the landmass generation so it's hard to predict what the map would look like, but I guess I should probably use the "Start Anywhere" option. (The other options are Largest Landmass (Terra-style) and Any Continents, which is probably what I picked)

**Comment by azum4roll** [comment] 2024-01-04 01:12
Start Anywhere/Rectangular is a safe pick, but sometimes it screws some civs by putting most of their monopoly resources on the other side of a rift.

**Comment by n-core** [comment] 2024-01-04 07:23
I can see from the screenshot, that land is one of the biggest landmasses on the map (and another one on the east of that land). So the game packed some civs there. For your kind of config, I suggest you pick the "Start Anywhere" option as it will ignore civ placement region rules.

In the next version, I will add a tooltip helper on the map option selection.

**Comment by azum4roll** [comment] 2024-01-11 01:47
If no further issue, I'm closing this.

**Closed by azum4roll** 2024-01-11 01:47 UTC
