### ISSUE TITLE
Crash during multiplayer game 3.10.14

### ISSUE THREAD

**Issue by EliskaSvobodova** [LoneGazebo/Community-Patch-DLL#10300] opened 2023-10-02 20:38 UTC
_1. Mod Version_
3.10.14 NON-EUI, created own modpack

_2. DirectX Version_
DX 10 & 11

_3. List of Other Mods_
None

_4. Describe the Issue_
The game crashes right before the start of the 99th turn. I am playing multiplayer in standard mode, over the internet, with 2 players and I am NOT the host. All civs seem to process correctly, but before the next turn starts, my game CTD. The host remains in the game (as the only human).

______________________________________________________________________________________
_5. Save Game From 1 Turn Before_
In the zip, from the host

_6. Logs_
In the zip, from the host and mine. Mine end after successfully processing a specific city-state, but before processing of another city-state begins.

_7. CvMiniDump.dmp File_
In the zip, also I've tried to analyze it in Windbg, this is a stack trace I got:

00 779bf3a4 5bd99abb     CvGameCore_Expansion2!CvSyncVar<CvSyncArchive<CvCity>::SyncVars::m_aiPowerYieldRateModifier_Traits>::save+0x1b [C:\Users\Admin\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvSerialize.h @ 263] 
01 779bf41c 5bdf4e19     CvGameCore_Expansion2!CvSyncVar<CvSyncArchive<CvCity>::SyncVars::m_aiProductionToYieldModifier_Traits>::compare+0x2fb [C:\Users\Admin\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvSerialize.h @ 280] 
02 779bf454 5bf0fc7b     CvGameCore_Expansion2!std::make_pair<FeatureTypes,int>+0x9 [C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\utility @ 133] 
03 779bf98c 5bf11185     CvGameCore_Expansion2!std::allocator<std::_List_nod<std::pair<const CvDealAI::SDealItemValueParams,int>,std::allocator<std::pair<const CvDealAI::SDealItemValueParams,int> > >::_Node *>::construct+0x2b
04 779bfa30 5bf42dcf     CvGameCore_Expansion2!CvInterfacePtr<ICvDeal1>::reset+0x25 [C:\Users\Admin\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLLUtil\include\CvDllInterfaces.h @ 1912] 
05 779bfa3c 00188c4a     CvGameCore_Expansion2!std::remove<std::_Vector_iterator<CvDeal,std::allocator<CvDeal> >,CvDeal>+0xaf [C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\algorithm @ 1296] 
WARNING: Stack unwind information not available. Following frames may be wrong.
06 779bfa58 004da403     CivilizationV_DX11+0xd8c4a
07 00000000 00000000     CivilizationV_DX11!GetTempHeap+0x963

It seems that the crash happens during the evaluation of resources value by AI.

_8. Steps to reproduce the Issue_
It doesn't matter what I do in the game in the last turn before the crash.

[CrashFiles.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12786244/CrashFiles.zip)

**Comment by Cyclopia31** [comment] 2023-10-03 10:38
Did you tried to clear the cache folder of both players? I have also these kind of issues and the only way to be able to continue the game is to delete both players cache folder. Maybe keep them in another place because the Devs may need them to be able to debug your issue.

**Comment by EliskaSvobodova** [comment] 2023-10-04 06:35
> Did you try to clear the cache folder of both players? I have also these kind of issues and the only way to be able to continue the game is to delete both players cache folder. Maybe keep them in another place because the Devs may need them to be able to debug your issue.

Yes, and once it got us to the next turn, but then the game crashed again. Here is the cache after one of the crashes (I had to divide it because of the file size limit).

[cache.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12800066/cache.zip)
[Localization-Merged.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12800068/Localization-Merged.zip)

**Comment by axatin** [comment] 2024-05-25 09:33
I tried several times, but I'm not able to reproduce this. I can load the game and play for several turns without any desyncs or crashes. As an old version is used here and several other causes of desyncs have been fixed in the meantime, I'll close this issue.

**Closed by axatin** 2024-05-25 09:33 UTC
Labels: CTD, Multiplayer
