### ISSUE TITLE
Religous pressure not working 1-11 version

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6113] opened 2020-01-14 05:15 UTC
_1. Mod version (i.e Date - 4/23):_ 1-11-20

_2. Mod list (if using Vox Populi only, leave blank):_  

_3. Error description:_ Only holy cities generate religious pressure, and only on themselves. The pressure from holy cities is not applied to other cities. Pressure modifiers do not appear to work. Trade routes are however creating pressure. 

_4. Steps to reproduce (optional):_
See attached screenshots from LifeOfBrian on the forum (no mods in use), and from my own game (using enhanced city view and reforestation mod). Logs folder and save game are attached for my game.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4057465/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[war korOda Nobunaga_0163 AD-1030.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4057461/war.korOda.Nobunaga_0163.AD-1030.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/59859911/72315924-753f5080-3662-11ea-9130-3c22e605e516.png)
![image](https://user-images.githubusercontent.com/59859911/72315931-7a9c9b00-3662-11ea-804b-2bc9cac3cf5d.png)
![image](https://user-images.githubusercontent.com/59859911/72315933-7e302200-3662-11ea-9f61-eea2ae00e6e7.png)
![20200113235955_1](https://user-images.githubusercontent.com/59859911/72315943-85efc680-3662-11ea-9d0e-05e7c7160286.jpg)

**Comment by ilteroi** [comment] 2020-01-14 06:20
duplicate of #6101

**Closed by ilteroi** 2020-01-14 06:20 UTC
