### ISSUE TITLE
Issues with trade routes and isolation

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1142] opened 2016-01-24 08:47 UTC
![2016-01-23_00003](https://cloud.githubusercontent.com/assets/11132095/12535321/69b0c0fa-c244-11e5-92f5-19d787ced9da.jpg)
![2016-01-23_00001](https://cloud.githubusercontent.com/assets/11132095/12535322/69bdcc64-c244-11e5-9229-90cef63f3a34.jpg)
![2016-01-23_00002](https://cloud.githubusercontent.com/assets/11132095/12535323/69c5010a-c244-11e5-8839-4c9f6169166d.jpg)

As you can see, at this point in time my internal trade routes were not eliminating my unhappiness from isolation. However, it seemed to be working fine when I paid attention to it earlier in the game and at points later in the game, so I really don't know what was going on. This is with the 1-23 hotfix, full CPP.

**Comment by LoneGazebo** [comment] 2016-01-26 02:36
Ilteroi, you have any ideas here? The code looks fine - is this possibly an issue with blockade calculations or something?

G

**Comment by LoneGazebo** [comment] 2016-01-26 02:36
Joose, can you link the save for this?

**Comment by joosegoose** [comment] 2016-01-27 05:11
:(

I'm not finding a save from when the issue was present in that game.

**Comment by Kolaris8472** [comment] 2016-02-01 00:36
I'm seeing this in the 1/29 version. It's pretty heavily modded though. Is the save game useful at all? 

Also I don't recall the cities in question being blockaded, which I think you mentioned as a possible cause. They are both coastal though, and barbarians may have wandered by without my noticing.

**Comment by LoneGazebo** [comment] 2016-02-01 03:04
Not if heavily modded (the save). We're investigating.

**Comment by ilteroi** [comment] 2016-02-08 08:04
no time to check yet

**Comment by LoneGazebo** [comment] 2016-02-17 18:46
Some users still reporting this – I think it might be that hostile units on a city connection (be it water or land) 'break' the connection, and possibly also the pathfinder that links them. This may or may not be related to the trade route selector issue in #1274.

**Comment by LoneGazebo** [comment] 2016-02-22 03:47
Ilteroi, I can reproduce this immediately at start of game with Carthage. Reveal map. Build your capital and a second coastal city. Next turn, you'll get the 'city connected' popup, but the city connection icon doesn't appear, and isolation unhappiness accrues. The problem is that this function:

`	std::map<int,std::pair<int,bool>>::iterator lastState = m_capitalConnectionLookup[eRestrictRoute].find(pCity->GetID());
	if (lastState!=m_capitalConnectionLookup[eRestrictRoute].end() && lastState->second.first==GC.getGame().getGameTurn())
		return lastState->second.second;`

seems to always return false for harbor connections. Is this a tech issue, a pathfinder flaw, or a cache issue?

**Comment by ilteroi** [comment] 2016-02-22 20:02
just stepped through it -> the problem is that if you don't have the wheel, you cannot have city connections. even with harbors. that's a carthage specific problem, but i fear there's something else

**Comment by LoneGazebo** [comment] 2016-02-22 20:26
I was afraid of that. To add to this, it seems that some tiles that aren't actually city connections are being labeled as such (random roads that may or may not be close to cities are being toggled as connections). This could be a caching issue, but it could also be some kind of weird aberrant pathfinder thing.

Re: the Wheel being a requirement, can't we just drop that? I mean, logically, you can't make a connection unless you have a build that allows it, and at the same time the UAs that benefit should be able to benefit regardless of the road (as that's the point of the UA). Thoughts?

**Comment by ilteroi** [comment] 2016-02-22 20:28
yeah, i've already modified the pathfinder, but i'll continue digging

**Comment by LoneGazebo** [comment] 2016-02-22 20:29
Strike that last issue (aberrant connections), it was a dumb on my part.

**Comment by LoneGazebo** [comment] 2016-02-22 20:31
Also, this is wrong thread for it, but I think forcing a much more aggressive stance for the AI during the first 20 turns or so of a war would be a smart move. The AI is extremely passive on the initial (right after DOW) offense. Might be worthwhile to try and 'force' the surgical city strike posture, even if the AI doesn't think it has the units to make said surgical strike.

**Comment by ilteroi** [comment] 2016-02-24 21:44
anyway, cannot reproduce the original issue. checked in a bunch of games now, no problem with traderoutes or isolation.

**Comment by LoneGazebo** [comment] 2016-02-24 22:12
Cool, seems we've fixed. Closing.

**Closed** 2016-02-28 23:07 UTC
Labels: Fixed for upcoming version
