### ISSUE TITLE
4.10 Gold income mismatch between CURRENT DEALS and actual income (+/-)

### ISSUE THREAD

**Issue by brsoft1981** [LoneGazebo/Community-Patch-DLL#11054] opened 2024-06-28 21:20 UTC
_1. Mod Version (X.Y.Z). Current Version: 4.10 with EUI

_3. List of Other Mods_ None

_4. Describe the Issue_
So, according to EUI, I've got -68 net balance with other civilizations. According to my CURRENT DEALS, my net balance is +7 (using +/- calculation). Something is wrong. 

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[SaveGames.zip](https://github.com/user-attachments/files/16036892/SaveGames.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![currentd](https://github.com/LoneGazebo/Community-Patch-DLL/assets/96129291/a5463e2c-ee48-4b19-84bf-5c44672d1b1b)
![currentdEUI](https://github.com/LoneGazebo/Community-Patch-DLL/assets/96129291/4bceca21-c61b-41c2-8b1a-f6d28a37d105)

**Comment by axatin** [comment] 2024-06-28 22:03
There's definitely a bug here. The problem is, the "gold to other civs" value is only updated when a deal starts/ends, so I don't know when the error happened or what caused it. If you have previous autosaves for this game, can you try to find out on which turn it started to be wrong? Otherwise, please keep an eye on it in your next game.

**Comment by brsoft1981** [comment] 2024-06-28 22:41
I found this mismatch at least 30 turns ago, but i can't find any clues for the reason :(

**Comment by axatin** [comment] 2024-06-29 08:49
Some deal-related bugs are now fixed for the next version (third-party peace treaties not expiring). This one might also have been caused by them. I'll close this issue for now. Watch it in the next release, if any discrepancies arise in a new game in the next version, reopen the ticket.

**Closed by axatin** 2024-06-29 08:49 UTC
Labels: Watch this in the next release

**Comment by brsoft1981** [comment] 2024-06-29 10:00
Thanks, I'm waiting for the next release :)
