### ISSUE TITLE
CTD on AI Turn 12-18 w/hotfix

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#982] opened 2015-12-22 17:53 UTC
http://forums.civfanatics.com/showpost.php?p=14100368&postcount=4090

**Comment by ilteroi** [comment] 2015-12-22 23:49
sorry, cannot use it, i didn't keep that build around and it seems none of my committed versions matches ... is it reproducable?

**Comment by Iamblichos** [comment] 2015-12-23 02:41
Yeah tried 3 reloads and crashed at same point. Look like from lua.log AI was about to make a deal with me.

**Comment by ilteroi** [comment] 2015-12-23 03:10
i put a debug build on https://dl.dropboxusercontent.com/u/16988401/civ/debug-build.zip

if you want, try again with this dll. i should be able to use the resulting minidump.

additionally, there should be a file calls "callstack.log" in the logs folder after a crash which is also interesting. (it needs the included PDB file to work)

**Comment by Iamblichos** [comment] 2015-12-23 15:59
Well I've got nothing on this, because it now passes with the debug DLL....

**Comment by ilteroi** [comment] 2015-12-23 17:34
shame. seems to be a heisenbug - let's keep this open for while in case it resurfaces

**Comment by Iamblichos** [comment] 2015-12-29 02:06
Got another CTD on AI Turn with your latest uploaded hotfix 12-28

https://www.dropbox.com/s/8kzwxcdisl2ji48/CvMiniDump.zip?dl=0

**Comment by Edaka** [comment] 2015-12-29 12:08
Here's a couple more CTDS reported on the forum. Just gathering them in one place. 

http://forums.civfanatics.com/showpost.php?p=14103683&postcount=4118
http://forums.civfanatics.com/showpost.php?p=14102419&postcount=4109
http://forums.civfanatics.com/showpost.php?p=14100639&postcount=4093

The last one's minidump was 0 bytes. Here's the modlist he's using: 
Community Patch, 
City-State Diplomacy Mod for CBP (11-5), 
Civ IV Diplomatic Features - CBP Edition (11/5), 
More Luxuries,
InfoAddict, 
Faster Aircraft Animations.

Could it be caused by not using CBP along with CSD and C4DF?

**Comment by Iamblichos** [comment] 2015-12-29 14:03
Another one.

https://www.dropbox.com/s/65tw70cx6vka9yx/CvMiniDump_2.zip?dl=0

**Comment by ilteroi** [comment] 2015-12-29 15:56
it's extremely hard to make use of the minidumps with all the different dll versions which have been flying around. 
 
there was an issue in the new CheckBuildingSanity function (divide by zero), which might be responsible. it has since been fixed, so i'm hoping that helps.

@LoneGazebo: i think it would be better to include the PDB files and enable the call stack logging for crashes. that makes it much simpler to see whats going on. maybe even ship the un-optimized build.

**Comment by LoneGazebo** [comment] 2015-12-29 16:21
On release versions I won't, but beta versions we can do that.
G

**Comment by Edaka** [comment] 2015-12-29 18:39
Yeah, figured so. All the links are after 12/18, but can't guarantee what version what user had during the crash.

**Comment by Iamblichos** [comment] 2015-12-29 19:09
Mine above is using the latest hotfix.

**Closed** 2016-01-03 18:44 UTC
