### ISSUE TITLE
Corporations screen won't leave

### ISSUE THREAD

**Issue by cairnsy44** [LoneGazebo/Community-Patch-DLL#1655] opened 2016-04-25 17:08 UTC
Bug Reports - Please fill out the following form:

1. Mod Version (i.e Date - (4/23b)): 4/23b

2. Mod List (if using standard CPP set, leave blank):
CPP except City-State Diplomacy
JFD's Roosevelt
JFD's Exploration Cont. and Exp.
JFD's Cultural Diversity
Sukritact's Events and Decisions v3
3. Type of error (i.e. crash, interface bug, AI quirk): 
Upon starting the game I click on "Begin Journey" and then the Cul.Div. info. Next is a Corporations and Monopolies screen that won't do anything even if I click on "close."

4. Steps to reproduce:

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment] 2016-04-25 17:13
This is a known conflict with JFD's mods. Please delete JFD's unique corporation (included with ExCE I believe).

**Comment by cairnsy44** [comment] 2016-04-28 14:42
thanks! Shortly after sending, I played around and tried without the 2 JFD mods. It worked as you know. I am really enjoying the CPP. Though I also notice that when I try to move my Great Works around to different buildings, I am unable to as the screen seems stuck on one of my satellite cities and doesn't let me select a work to move. 
 

    On Monday, April 25, 2016 2:13 PM, LoneGazebo <notifications@github.com> wrote:
 

 This is a known conflict with JFD's mods. Please delete JFD's unique corporation (included with ExCE I believe).—

**Comment by IllusVirus** [comment] 2016-05-04 02:19
So, I appear to be having this same issue with the latest beta.

I reload the game where I have founded a corporation, once the game completes loading the corp screen appears and cannot be closed. Other games that have not yet founded a corporation does not have this problem.

I've only ever used Quick Turns (mod) with CPP.


[Lua.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/248072/Lua.txt)

**Comment by mwhiter** [comment] 2016-05-04 02:29
@IllusVirus 

1) Which Corporation did you found?
2) If you go into Documents/My Games/Civ V/MODS/(2) Communitty Balance Patch/Modular Elements/Corporations/ - can you upload the contents of your Corporations.xml?

Interesting...

**Comment by IllusVirus** [comment] 2016-05-04 02:42
I founded the LandSea Extractors Inc.

Apologies, I didn't know how else to preserve the format of the xml and Thank you.
[Corporations.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/248085/Corporations.txt)

**Comment by mwhiter** [comment] 2016-05-04 22:32
@IllusVirus sorry to make you do this, since the original issue is related to JFD, can you create a new Github Issue with your problem specifically? It will require me to investigate a little bit and reproduce on my end, and I don't have the ability to until this weekend.

**Comment by IllusVirus** [comment] 2016-05-04 23:24
Ok, no problem.

**Comment by ilteroi** [comment] 2016-05-10 09:26
@mwhiter : this just happened to me as well - i have a savegame, but it needs the latest fefe branch dll - do you want it?

**Comment by mwhiter** [comment] 2016-05-10 22:06
Landsea extractors has a bugged XML definition causing the issue. This fix has been applied to master.

**Comment by LoneGazebo** [comment] 2016-05-10 22:30
Yep. closing.

**Closed by LoneGazebo** 2016-05-10 22:30 UTC
Labels: Cannot reproduce, Need more information
