### ISSUE TITLE
Reproduceable 'hang' between turns

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#3329] opened 2017-07-03 01:14 UTC
_1. Mod version (i.e Date - 4/23):_ 6/22

_2. Mod list (if using Vox Populi only, leave blank):_ Improved City View, Quick Turns

_3. Error description:_  The game essentially freezes between turns in the specific game I'm playing (I've already played one full game to completion on this install). I can't get past this turn no matter what.

_4. Steps to reproduce (optional):_ 'Next Turn'

[Sid Meier's Civilization 5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1118215/Sid.Meier.s.Civilization.5.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment] 2017-07-03 05:56
it's due to a worker finishing an auto-route probably ... if so, it's already fixed

**Comment by TechpriestEnginseer** [comment] 2017-07-03 15:38
Sweet. I can just add a kill worker function everytime the hang happens on my game tests. Thanks!

**Comment by joosegoose** [comment] 2017-07-04 00:42
Is there anything I'd be able to do to advance in the current game I have going?

**Comment by TechpriestEnginseer** [comment] 2017-07-04 01:31
Kill all the workers through IGE.

**Comment by joosegoose** [comment] 2017-07-04 01:35
Yeah that's kind of what I was thinking. I'd already tried dabbling with IGE, though I just tried to find 'problem'workers to see if destroying them would fix it. I stopped short of eliminating every worker though, and probably won't go to that length.

**Comment by ilteroi** [comment] 2017-07-04 09:58
duplicate of #3309

**Closed by ilteroi** 2017-07-04 09:58 UTC
