### ISSUE TITLE
A civ can talk to me even though we didn't even have a contact

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#426] opened 2015-07-18 07:05 UTC
![8930_2015-07-18_00004](https://cloud.githubusercontent.com/assets/1131228/8760692/06f399cc-2d45-11e5-8618-229b60232bb6.png)
Notice how Brazilia is shown in InfoAddict whilst it's not on my contact list.
![8930_2015-07-18_00005](https://cloud.githubusercontent.com/assets/1131228/8760698/348b899e-2d45-11e5-88f4-3cd3b4d0893a.png)

**Comment by LoneGazebo** [comment] 2015-07-18 14:44
That must be an issue with InfoAddict, as I don't see that issue without it.
G

**Comment by Radost** [comment] 2015-07-18 16:58
I do have that issue without it though.
![8930_2015-07-18_00039](https://cloud.githubusercontent.com/assets/1131228/8762635/19c24e24-2d98-11e5-89b5-b0cef0abcfb6.png)

**Comment by ilteroi** [comment] 2015-07-21 20:01
my bad, merged some untested code to improve observer mode. for some reason, observer team is team 21 (and has always been). so now this latent problem is exposed.

question is how to fix it:
- try to hide it again (team 21 will likely continue to have other unintended behaviors)
- restrict games to 21 major civs (likely won't go down well with users)
- try to move observer team to some other ID (follow-up bugs cannot be ruled out)

**Comment by ilteroi** [comment] 2015-07-21 20:26
as always, taking a look at the source is helpful.

- the OBSERVER_TEAM constant is only ever used in places I touched, so option 1 should be risk-free but the observer sees less
- made an experimental build with observers in team 64
- it might also be possible to do without a dedicated observer team

to be continued ...

**Closed** 2015-07-24 04:35 UTC
Labels: Fixed in upcoming version, help wanted
