### ISSUE TITLE
Ai stops building road a tile before final city tile

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4963] opened 2018-12-05 20:10 UTC
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When I order an AI to build a road from city X to city Y, they'll start the first tile, make all the other tiles correctly, but they'll always stop on the tile just before the destination city. They'll then ask you what to do and if you don't notice the road's not built, it's bad as you won't be getting the city connection for obvious reasons. You have to notice the Worker's on the final tile and then tell him again to build the tile.

**Comment by briantjack** [comment] 2018-12-22 17:53
Has this been addressed in the latest edition?

**Comment by ilteroi** [comment] 2018-12-23 12:00
couldn't reproduce it ...

**Comment by ryanmusante** [comment] 2018-12-23 12:40
May or may not be related to prior issue. I had posted on 4134 and at the time it might have been related to a mod conflict.

https://github.com/LoneGazebo/Community-Patch-DLL/issues/4964

https://github.com/LoneGazebo/Community-Patch-DLL/issues/4134

**Comment by ilteroi** [comment] 2018-12-27 19:05
ok this was quite the puzzle but luckily i like puzzles. fixed.

**Comment by briantjack** [comment] 2018-12-27 23:35
Thanks!

**Comment by briantjack** [comment] 2019-01-06 03:35
Will this change be included with the next version of VP?

**Closed** 2019-01-08 21:46 UTC
