### ISSUE TITLE
Randomly disappearing airplanes is still a problem! 

### ISSUE THREAD

**Issue by soeb80** [LoneGazebo/Community-Patch-DLL#6857] opened 2020-08-02 12:03 UTC
1. Mod version (i.e Date - 4/17):
Latest to date; 6-19 (including the latest july 29th patch)
2. Mod list (if using Vox Populi only, leave blank):
CP 6-19 installer (1,2,3,4,5,6a,7a,7b)
+Infoaddict
3. Error description:
Randomly disappearing airplanes is still a problem! 

Well, a large part of the problem was solved by Ilterio. 

So the problem is that airplanes randomly still disappear; I first thought that I was mistaken, but realized they started to disappear.

I tried to reproduce and identify the problem. I’m still not sure what doing it; seems random. It was not a problem as long it only was triplanes (2 units) and bombers (3 units), but when I started upgrading them to fighter plains and heavy bombers. 

I reloaded a saved game several times; when upgrading the air units. At last I manage to upgrade them without them disappearing. 

First I suspected that it occurred when two air units was stationed in one city, and one was upgraded; somehow temporarily extending the air unit limit. But after some attempts I manage to update both air units, so it’s probably not that.

**Comment by biburt** [comment] 2020-08-02 12:31
Can confirm this is still an issue (in my experience also only with later plane upgrades), although very random it seems. Interestingly enough it also happens to nuclear missiles. I spent 8 turns making one, moved it to a different city, and the next turn it went poof. On the plus side, the game clearly knew it went away as the resource counter adjusted for it and I just made another one. This is on the latest patch, but with only VP + IGE. If it happens again I'll post a save!

**Comment by soeb80** [comment] 2020-08-02 16:41
Ok, I have a save file for you; 
https://drive.google.com/file/d/1qFBDC_i6EX1IdEyUz59_Es8umS4aDyrQ/view?usp=drivesdk

So what’s happening here is that as soon I make peace with Attila of Mongolians; every air unit involved in combat this turn disappear (total of 4 units).

**Comment by azum4roll** [comment] 2020-08-03 02:21
Maybe it's the "move units out of borders when making peace" code that did it?

**Comment by olmer711** [comment] 2020-08-03 15:47
I have same problem. And i have save file, where u can reproduce bug.
 I use latest ilteroi patch and a couple of mods.
 VP (1,2,3,4,5,6a,7a,7b)
(build) More Wonders for VP
(over) More Unique Components for VP
(text) Promotion Overhaul for VP
(ui) List Enhancements for VP (v 5.2)
(ui) Meaningful Colours (v 8)
(ui) Wonder Planner For VP
CIV-Linked Great Generals (v 11)
PerfectWorld 3 (v 4)
Promotion Flags EUI for VP (v 3)
UI - Improved City View (Vox Populi EUI) (v 11.0)
Here is save file:
https://drive.google.com/file/d/1TTfdizM5wZedveWGSDAtF-E4Fojc-xgh/view?usp=sharing
Look to pictures to reproduce.
![1](https://user-images.githubusercontent.com/69159425/89200861-4f0adf00-d5b9-11ea-8792-9201628db8aa.png)
![2](https://user-images.githubusercontent.com/69159425/89200880-56ca8380-d5b9-11ea-8adc-ff3082ba395d.png)

**Comment by olmer711** [comment] 2020-08-03 15:59
It seems to me that the problem only concerns those units who ALREADY ATTACKED on their turn

**Comment by soeb80** [comment] 2020-08-03 17:46
> It seems to me that the problem only concerns those units who ALREADY ATTACKED on their turn

Not only; I initially experienced the problem after upgrading the unit. I was not in any war, nor did I move the units. Maybe some conflict with the diplomacy? 🤷🏼‍♂️

**Comment by ilteroi** [comment] 2020-08-03 20:54
cannot load the save and cannot reproduce locally ... difficult

**Comment by olmer711** [comment] 2020-08-04 05:37
> 
> 
> cannot load the save and cannot reproduce locally ... difficult

May be trouble in the modlist/mod versions. Here is my MODS folder in zip archive.
https://drive.google.com/file/d/1e9azijIRYzquKVriErOL0V5OvBBCHKx7/view?usp=sharing



> 
> 
> > It seems to me that the problem only concerns those units who ALREADY ATTACKED on their turn
> 
> Not only; I initially experienced the problem after upgrading the unit. I was not in any war, nor did I move the units. Maybe some conflict with the diplomacy? 🤷🏼‍♂️

Well, units lost their action points after upgrading. So problem concerns units witn NO AP remain.

**Comment by yyEdge** [comment] 2020-08-06 07:44
Can confirm this is a thing, and it happens with missiles too, I run a mod with a missile upgrade and after upgrading the missile with full air capacity in the city the entire air fleet is gone.

**Comment by olmer711** [comment] 2020-08-07 12:30
any chance to fix it?

**Comment by iqddd** [comment] 2020-08-08 17:40
Confirm. Same problem. I only play CommunityPatch without changing the balance. I'll try to make a save.

**Comment by iqddd** [comment] 2020-08-08 17:45
Planes disappear not only for the player, but also for the AI. There was one save where the Hun had 5 planes in the city. After the capture of another city, he transferred them to the captured city, and the planes disappeared.

**Comment by achaian** [comment] 2020-08-09 17:34
I am also having this problem using the 6-19 patch. I am not using any other mods, nor have I changed any of the CBP files. Here is exactly how it happened to me:

I built a great war bomber. I transferred it to another city, and the next turn it had disappeared.
I built a triplane. I transferred it to that same city, and it did not disappear. I was able to attack targets without issue for several turns.
I built another great war bomber. I transferred it to that same city, and the next turn, both it and the triplane had disappeared. The units that had disappeared did not continue to consume oil.

**Comment by DelJon** [comment] 2020-08-12 10:00
My Bombers were disappearing if I had made peace with someone and I had made a move with them beforehand during that turn.
https://github.com/LoneGazebo/Community-Patch-DLL/issues/6831 in this build.
After I noticed this and played around that it seemed fine.

**Comment by Inseerlink** [comment] 2020-08-13 21:37
Hi guys! I am not sure if this is of any help, but something called my attention - in my game it is only possible to have 2 airplanes per city, what happened when I got the second airplane though is that at the start of my turn the second airplane disappeared and appeared at another city (without any rebase command) - so I am guessing someone might have created a lua file in the new community patch which makes airplanes rebase when more than possible are stationed in a city, and this file might be corrupting the game functions (by making airplanes rebase to inexistant cities, thus making them disapear from game).

I am a completely new to programming, so I am not sure if I will be able to find what is causing the issue by my own, so I am just posting here in case someone knows lua better than me and might find what is making this happen.

**Closed** 2020-08-17 15:34 UTC
Labels: Cannot reproduce, Fixed for upcoming version, Paging Dr. Ilteroi
