### ISSUE TITLE
Lua stability

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6114] opened 2020-01-14 06:53 UTC
i'm getting intermittent crashes from Lua during autoplay, typically in CallTestAll() ... in different hooks. this is annoying and seems impossible to fix, at least for me. does this happen to others as well?

anyway, which of these lua hooks are actually used? i know modders might want to use them, but i would like to disable them by default if we don't need them in base vp. opinions?

**Comment by LoneGazebo** [comment] 2020-01-14 15:56
https://www.reddit.com/r/civ/comments/6a0j6l/civ_v_luajit_newer_version/

**Comment by ilteroi** [comment] 2020-01-14 17:33
i think i tried that before and there were issues but i'll try again

**Comment by ilteroi** [comment] 2020-01-26 20:23
still the same problem - but the crash is always an access violation in LuaSupport::CallTestAll(), so apparently it's an invalid pointer somewhere.

does anyone have an idea why that might be happening?

**Comment by LoneGazebo** [comment] 2020-01-26 21:15
do you have a repeatable crash? you could try to see if the crash is detectable while connected to the DLL

**Comment by ilteroi** [comment] 2020-01-26 22:09
nah, it's not repeatable. but annoying ...

**Comment by ryanmusante** [comment] 2020-01-29 01:51
https://forums.civfanatics.com/threads/luajit-for-civilization-v-faster-turns.399635/

**Comment by ilteroi** [comment] 2020-02-06 21:54
i patched out the lua callbacks and haven't seen a single crash since. works fine!

**Comment by LoneGazebo** [comment] 2020-02-06 21:56
Yeah I think the additional lua callbacks added by whoward in his API were overtaxing stuff.

**Comment by LoneGazebo** [comment] 2020-02-06 21:56
civ's lua interface isn't exactly...robust.

**Comment by LoneGazebo** [comment] 2020-02-07 17:16
@ilteroi are you gonna push the lua callback opt out? We could lock it behind a define that modders can enable. 

G

**Comment by Serpens66** [comment] 2020-04-12 09:07
@ilteroi Hi there :)
where can I see which callbacks you mean? I also recently started my first steps on dll modding, but because of far too many bugs in multiplayer, I'm using whowards dll as base, instead of community patch (although I dont know if multiplayer bugs are dll or lua related). 

Anyway which callbacks did you removed or where can I find "your branch"? My first goal is currently a bug free game, so if removing some callbacks might help...

Btw. I'm also struggling to build a dll, maybe you have a tip:
[URL="https://forums.civfanatics.com/threads/building-a-dll-based-mod-in-2019.645887/#post-15726745"]Building a DLL based mod in 2019[/URL]

**Comment by ilteroi** [comment] 2020-04-12 11:56
well for building you should follow the guide in VPs readme.

the lua switch is in the VP master branch, but callbacks are enabled by default in CP ... search for CORE_DISABLE_LUA_HOOKS in CustomModOptions.xml

**Comment by Serpens66** [comment] 2020-04-12 14:13
thank you very much, also for your and Gazebos work :)
Is there a thread (eg at civfanatics) where you write about dll stuff or I could ask questions, or simply open a new thread in community patch area?

And where can I find the documentation you mentioned? I readme I see a "how to build this" but it is only general information, no step by step nor trouble shooting. I tried it 2 times now, but I can not pass the "fatal error C1083: Cannot open include file: 'unordered_set': No such file or directory" error message from visual studio when trying to build the dll.

**Comment by ilteroi** [comment] 2020-04-13 08:45
well, i don't really know your setup, but i can tell you that unordered set is part of the visual c++ stl implementation, so you should have it. 

on my machine it's located at C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\unordered_set (for VC++ 2008) but each VS release has its own instance.

which version are you using? independent of the IDE version, you need to use the legacy 2008 toolset to compile/link the DLL.

also, unordered set it really only used to store some non-essential advisor messages, you can just as well rip it out and see how far you get without it.

**Comment by Serpens66** [comment] 2020-04-13 11:18
thank you very much.
I linked the civfanatics thread above, there you see what I did. Of course you can also answer there instead, so we dont have to spam this unrelated issue, sorry for that :(
In short:
* Install VS-2008
* Install VS-2010
* Install VS-2010 Isolated Shell
* Install VS-2010 SP1
Used the download links from bc1 in that thread.
And no, I dont have the unordered_set file there, so the error is correct.
I already commented that out, but the next issue was "unordered_map" so I thought this may be an very big list of missing files...
After I installed the things above, I started "Microsoft C++ 2010 Express".

I took a look at the 2010 installation folder, and there was a unordered_set file! I copied all files from there now to the 2008 installation (without replacing) and now... I get alot of errors thworn from unordered_set :D  I guess it is simply because it is an incompatible version.
Do you know where I get the correct version of 2008?

Offtopic:
I'm new to C++ and visual studio, but I really really wonder how any professional could ever work with that, there are soo many problems when working with that and old versions and so on, alsone installation is a real pain, especially newer versions, 2015 and up (because it forces you to download 15GB without pause and after that it tells you sth went wrong, and you have to download everything again, although you only need 500 MB of that packet)...

**Comment by ilteroi** [comment] 2020-04-13 16:20
good point about the service pack ... anyway, did you manage to attach the visual studio debugger to a running civ game with a custom gamecore dll?

anyway if you experience a crash while running in the debugger it shows you where the exception happened. it may be that there is no source available for the crash location, but look at the callstack, if lua51.dll is involved that is a strong hint ...

**Comment by Serpens66** [comment] 2020-04-16 07:12
found this guide on how to debug https://forums.civfanatics.com/threads/a-guide-to-debugging-crashes-with-a-custom-dll.506328 , I'm able to live debug now, at least break if there is a crash. But I can't set breakpoints myself, nor can I read minidump files (explained in that thread).

Anyway, is there no professional way to get a lua traceback, if the crash is caused by lua?
Eg. I get frequent crashes from the newst EUI, without any other mod installed, and would like to track it down. I will now try live debugging and hipe there is something crashing in the dll. But if it is a crash in lua, I wont be able to find the reason? (usually there is nothing about it in lua log)

Btw:
The 2 crashes I mentioned above (wth whowards dll) were caused when founding a pantheon without capital. But this is already fixed in CP, although it is part of "MOD_BALANCE_CORE"... So there is no easy way for me to find out all the vanilla bugfixes CP has, but whoward does not have?

**Comment by ilteroi** [comment] 2020-04-16 08:41
* there is no list of bugfixes ... at this point major parts of the vanilla code have been replaced, so you cannot really compare them anymore
* lua has its own callstack and there even is a function DumpCallStack() but it's not used at the moment. maybe it's possible to store the lua_state* in GetInstance() to a global variable and call DumpCallStack() in the c++ exception handler ... check CreateMiniDump()

**Comment by Serpens66** [comment] 2020-04-16 08:58
thanks. sounds good. unfortunately I'm no programmer and and dont know C++ (I'm currently learning by reading civ5 code). Is this something the CP-team will implement? It will also help to track down alot of crashes with CP-mods I guess.

**Closed** 2020-04-16 16:01 UTC

**Comment by ilteroi** [comment] 2020-04-16 20:40
i added lua stack logging ... good idea :)

**Comment by Serpens66** [comment] 2020-04-19 18:17
githubi really a strange place, wasnt able to find this topic, neither in closed issues not in my profile history. Found it via email link.

ilteroi: 
Could you explain how to use the lua stacking?
I build CP dll with the new addition and put the dll into the new beta build from 18.April. I found an easy way to crash the game with a lua command (by accident):
pPlayer:AddNotification(NotificationTypes.NOTIFICATION_BARBARIAN, descr, title, -1, -1)
And when VS attached I saw, that there was a crash in CvPlot in getImprovementType. At first I had no clue how this was related to my code. Will your lua loggin/callstack now help in any way to find out it was caused by this notification? 

I still have trouble to open minidumps. When I open it, it shows nearly nothing. When hitting "debug with natives" it throws an error about civ5.exe and when I continue I got a break indeed finally code from that getimprovementtype code. But that did not work for whowards dll, so I'm not sure if this is the supposed way.
Anyway, I see nothing about lua...

This specific crash shows C++ code, while other lua crashes only show LUA51.
So maybe your new lua callstack feature only works for the latter?
