### ISSUE TITLE
another inofficial build

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10613] opened 2024-01-22 07:20 UTC
with recursive being away, here's another inofficial update (dll only). savegame compatible, let's call it v4.4.3-inofficial.

changes:
* roadbuilding fixes from kungcheops
* war weariness
* india prophets
* AI expansion
* performance improvements

[CvGameCore_Expansion2-4.4.3-unofficial.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14006460/CvGameCore_Expansion2-4.4.3-unofficial.zip)

as always, this is a drop-in replacement for the existing dll in mods/communitypatch

**Comment by brsoft1981** [comment] 2024-01-22 07:44
I'll test it later :)

**Comment by brsoft1981** [comment] 2024-01-22 21:20
So far, so good. War weariness is working, AI expansion is ok too

**Comment by Hugo-Pratas** [comment] 2024-01-23 13:03
Crashes with override Starting Plots - communitu_79 map

**Comment by saamohod** [comment] 2024-01-23 21:17
> with recursive being away

Recursive being reclusive

**Comment by Nu-Illasera** [comment] 2024-01-24 14:23
Hold on , that makes no sense, that is only the dll, some of the fixes here had changes in SQL files and more, pretty sure there need to be more here for this to work right.

**Comment by Jabbado** [comment] 2024-01-31 09:23
> So far, so good. War weariness is working, AI expansion is ok too

I'm in my second game of this build going for domination victory in both and haven't seen a hint of war weariness.

**Comment by Hokath** [comment] 2024-01-31 16:52
I also didn't see any for a long time, but then I started getting smacked around by the Iroquois and it showed up, but as a very low number. Not sure it is working as intended.

**Comment by axatin** [comment] 2024-02-04 10:44
There was another issue with war weariness that's now fixed for the next official release (which will come soon).

**Closed** 2024-02-22 07:14 UTC
