### ISSUE TITLE
Automate explorer freezes game

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#2204] opened 2016-07-20 18:23 UTC
Bug Report Template

Mod Version (7/15):

1. Mod List (if using standard CPP set, leave blank):
InfoAddicts, Clock.

2. Type of error (i.e. crash, interface bug, AI quirk): 
Freeze.

3. Steps to reproduce:
I was playing Rome, more than 20 cities. Recently picked Imperialism. I selected an explorer (this with the spyglass) and clicked on Automate, and worked as expected, then selected another explorer, did the same thing and the game freezed. Pointer still moved, but game was freezed.

4. Additional information:

---------------------------
Supporting information:
Sorry, no minidump was generated. The zip file has a txt extension, please remove it before uncompressing.

[Logs.zip.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/374391/Logs.zip.txt)

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment] 2016-07-20 18:25
@ilteroi possibly the source of the phantom freezing? @GrantSP can you replicate?

**Comment by GrantSP** [comment] 2016-07-20 23:10
Never seen it while playing Rome but apart from that, yes, exactly what I see.
Gaming freezing with unit actions happened to me more often when using the unitpanel actions and clicking them but it also happens when hotkeys are used.

**Comment by tu-79** [comment] 2016-07-23 08:52
It happened again near turn 300, now while automating a worker. I reloaded and tried to not automate units, but I was getting tired of doing everything manually.

I've notice another weird thing, don't know if it is related. When I send a unit to a voyage longer than one turn sometimes happens:
-The unit is refusing to make one of the steps automatically, but I can select the unit again and force it to move to the next tile (it doesn't lose the move points, but is unable to do it automatically).
-The unit ignores that there is already another unit in a tile, if the tile is not the target tile, and the unit can finish its turn stacked. Sometimes it's ok be able to pass over your other units when you can give the last hit to an enemy unit and you cannot find a good position for it, but if the enemy is not defeated, your units end stacked.
-If the last move of one turn ends in a city where there is already a garrisoned unit, the garrisoned unit exchange its place with the moving unit. The next turn I have to deal with 2 units in alert, and usually the unit that is inside the city is the passing one.

**Comment by ilteroi** [comment] 2016-07-23 09:41
the pathfinder quirks should be better now, just changed a few things.

lockup: not seen on my end,. what's your reproduction rate? how often does it happen in how many automations?

**Comment by smokeeye** [comment] 2016-07-24 09:37
I posted in the other "freeze" issue thread as well.
But if you do _automate any unit_ it will freeze eventually.

**Comment by GrantSP** [comment] 2016-07-25 00:53
My experiences are less predictable. I have only ever seen it when playing as France and some of my recon units can go forever without causing issue.

**Comment by LoneGazebo** [comment] 2016-07-25 01:26
Definitely not an epidemic, otherwise we'd be seeing a lot more freeze-related posts. This is going to be tough to find, and I'm not 100% sure that it isn't a client-side issue (i.e. a particular computer setup) that's leading to it.

**Comment by tu-79** [comment] 2016-07-25 11:00
It's the first time this freezing happens to me. I'm a W7 user, that's may be the cause you cannot replicate it. Never happened when my cities are few and my armies small. Rome is the first big civ I've tried in a while. My guess is that the more automated units the bigger chance for a freeze.

Also the other issues occur when AI is actually moving my units, not just finding paths. They happen when I hit 'Next turn', and the units move automatically to its targeted location (swap position with a unit that may stand in its last step, unable to make the next step by itself o ending its turn over another friendly unit when the other unit has no movement points available). I don't know if that behaviour was intended, but it's very confusing and most of the time I'm moving units that I didn't want to move.

**Comment by ilteroi** [comment] 2016-07-27 20:00
duplicate of #2190

**Closed by ilteroi** 2016-07-27 20:00 UTC
Labels: Need more information, Putmalk's Demesne
