### ISSUE TITLE
 Bugged work boats 

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1848] opened 2016-05-23 21:23 UTC
Bug Report Template

Mod Version 5-21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
 Automated work boats get bugged sometimes. When one arrives at a sea resource it gets stuck there, then other automated work boats arrive and get stuck there too.

3. Steps to reproduce:
 Savegame attached
[Harun al-Rashid_0387 AD-1967.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/278289/Harun.al-Rashid_0387.AD-1967.zip)

**Comment by GrantSP** [comment] 2016-05-25 23:00
Similar example to this is with automated workers trying to fix pillaged fishing boats.
I watched a worker enter the ocean, spend a turn on the tile, return to land via another route, walk back to the sea and enter the water and move to the same tile. Rinse repeat.

**Comment by ilteroi** [comment] 2016-06-06 20:53
workers trying to fix boats should be fixed now. but i could not reproduce the work boat pileup ...

**Closed** 2016-06-15 01:18 UTC
