### ISSUE TITLE
Kasbah doesn't connect Coal

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#740] opened 2015-11-03 18:56 UTC
![8930_2015-11-03_00003](https://cloud.githubusercontent.com/assets/1131228/10918232/758ffc90-8286-11e5-866c-950e7760a6c5.png)

**Comment by Radost** [comment] 2015-11-30 10:07
It still doesn't connect it.

**Comment by LoneGazebo** [comment] 2015-11-30 17:47
Can't replicate this, sorry. Works on my end.

**Comment by Radost** [comment] 2015-11-30 23:55
I can't even describe how this phrase makes me bootyblasted.
I have the game right beside me and there is something wrong with kasbah connecting resources. Unless you tried to replicate on some hot new dev version.

Here is the preview:
![8930_2015-12-01_00015](https://cloud.githubusercontent.com/assets/1131228/11488323/7c415536-97e7-11e5-82f9-1058c2d52832.png)
It clearly shows Kasbah won't connect the spices as opposed to plantations.

Further proof it doesn't connect resources:
![8930_2015-12-01_00017](https://cloud.githubusercontent.com/assets/1131228/11488235/de8ba9d6-97e6-11e5-96e0-15072b19e15f.png)
Investing into the amber tile has built a Kasbah for some reason. However, I can't invest into the oil tile.

**Comment by LoneGazebo** [comment] 2015-12-01 00:02
Bootyblasted?

The EUI tooltip is not reflective of what actually happens. If you build a kasbah on a resource tile, it should update in the top panel (and elsewhere), but it wont' show the tooltip 'picture' of it because it's not actually the resource connector). The Kasbah works just like a Great Person Improvement.

**Comment by LoneGazebo** [comment] 2015-12-01 00:07
If you are talking about the tooltip quirk, I can look into that.

**Comment by Radost** [comment] 2015-12-01 00:56
It's not "only a tooltip", strategics don't add up in the counter, as in the first screenshot.

**Comment by LoneGazebo** [comment] 2015-12-01 01:03
I'll look at it some more, but like I said earlier, tests could not replicate your report.

**Comment by EEUYY** [comment] 2015-12-17 13:56
Hi, I have got variance of this issue as well. I have early in the game build Kasbah around my cities and later when resources such as Coal and Oil and if they spawn under the Kasbah the game count the resource. So I thought that Kasbah didn't connect resources and proceed to replace improvement with Mine/Oil Well. When the worker started to build the new improvement and removed the Kasbah the game countet resource as negative of the value in th tile. So in this case the tile provided 7 oil and with the Kasbah the game counted 0 oil and I couldn't build planes or trade the resource to another civ and when the Oil Well was done the game again counted 0 oil and I'm still unable to use the resource as you can see in the screenshot (I merged 3 to get the tooltip).
I have also attached the save file if you want to try it out, if you still can't reproduce the problem with the save then there is probably som local cache error.
I have installed version 0.11.20 full but haven't enabled more More Luxuries.
![civ5screen0000_modded](https://cloud.githubusercontent.com/assets/10529861/11871069/316dba02-a4cd-11e5-92fd-11e7ff415318.png)
Save: https://pbdn-my.sharepoint.com/personal/patrik_pbdn_eu/_layouts/15/guestaccess.aspx?guestaccesstoken=H%2brVm8VpmowGngf6xxaBpchL%2fTaU3BmQh3aPq%2bHQlHw%3d&docid=005efa434fd5642669621ecc95057385a&expiration=1%2f16%2f2016+1%3a53%3a57+PM

**Comment by LoneGazebo** [comment] 2015-12-17 16:58
I believe this is fixed in the beta, but we shall see.
G

**Closed** 2016-01-03 18:45 UTC
Labels: cannot reproduce, Fixed
