### ISSUE TITLE
Premature Antiquity Site

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4347] opened 2018-05-05 18:54 UTC
_1. Mod version (i.e Date - 4/23):_4-30-4

_2. Mod list (if using Vox Populi only, leave blank):_FlagPromotions v.7

_3. Error description:_ 

A regular (not hidden) Antiquity Site gets revealed long before I discover Archaeology. A CS wants me to dig it, therefore I suspect this might be the cause. I couldn't find any other regular Antiquity Cite on the whole map.

**Comment by Infixo** [comment] 2018-05-05 21:34
No logs. No screenshot. No save file.
Also, could be a duplicate of #4164

**Comment by saamohod** [comment] 2018-05-05 21:39
>No logs. No screenshot. No save file.

![20180505215014_1](https://user-images.githubusercontent.com/16341598/39667740-76cac788-50c5-11e8-9354-16a964b6f204.jpg)

[AutoSave_0282 AD-1824.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1977111/AutoSave_0282.AD-1824.zip)

**Comment by Infixo** [comment] 2018-05-06 14:40
> 2. Mod list (if using Vox Populi only, leave blank):

You are using FlagPromotions v7 (affects saved games).

Even with FPv7 I cannot load this save with 4-30 version, the game CTDs.

Stream desyncs while reading a Map (CvMap::Read), then Plot (CvPlot:read) at line 13198. It is a part where the game reads resources and improvements.

**Comment by saamohod** [comment] 2018-05-06 15:11
>You are using FlagPromotions v7 (affects saved games).
Oops, my bad. I forgot this is the only mod I use which affects savegame.

>Even with FPv7 I cannot load this save with 4-30 version, the game CTDs.

Stream desyncs while reading a Map (CvMap::Read), then Plot (CvPlot:read) at line 13198. It is a part where the game reads resources and improvements.
Edit, This is the first plot, btw at (0,0) coor.

Sorry for asking a lay question. What does it mean for me? I'm using Tectonic Map Script (it doesn't affect savegame), in case this information helps.

**Comment by LoneGazebo** [comment] 2018-05-06 15:42
It means that certain tiles are not loading their data correctly for that map type, which explains your experiences with tiles being ignored, etc.

**Comment by saamohod** [comment] 2018-05-06 15:48
>It means that certain tiles are not loading their data correctly for that map type, which explains your experiences with tiles being ignored, etc.

Interesting.
So which of my mods could be the culprit? Tectonic Map Script? FlagPromotions? I think the rest of the mods are pretty innocuous.

**Comment by Infixo** [comment] 2018-05-06 20:19
Most likely the map script. After all there are issues with the map. Flag Promo works with units, promos and icons.

**Closed** 2018-05-10 21:42 UTC
Labels: Mod Conflict
