### ISSUE TITLE
Rebase fefe

### ISSUE THREAD

**Issue by biship** [LoneGazebo/Community-Patch-DLL#1895] opened 2016-05-31 13:54 UTC
As it looks like branch fefe is now even, can it be rebased/recreated so that it isn't so many commits ahead? 

"This branch is 170 commits ahead, 3 commits behind master."

**Comment by ilteroi** [comment] 2016-05-31 16:39
oh well. it's not a bad as it looks. the problem is that G often does manual merges, so git doesn't know about them but the changes are in master anyway.

i do have some updates though, will probably push later today. don't know when the next release is due, G  seems to be busy.

**Comment by ilteroi** [comment] 2016-05-31 16:40
d'oh. fat finger problem

**Comment by biship** [comment] 2016-05-31 17:19
The problem comes when i want to send anything to master once i've incorporated anything from fefe. It tries to commit hundreds of files :( 

Yeah I see master G has a strange way of updating (obliterating) master!

**Comment by ilteroi** [comment] 2016-06-01 20:30
you may be right ... i've in fact never tried it that way around, only from master to fefe :)

anyway, it's done. just pushed the rewritten AI operations code. not very visible but much more predictable what the AI will is doing.

@G: there's a litte script to summarize the logfiles (OperationalAILog.csv) here 
[opstats.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/294328/opstats.zip)

example output like this:
```
AI_OPERATION_CITY_BASIC_ATTACK : Ended: Cancelled 9 -- Ended: Target already captured 3 -- Ended: Success 7 -- Ended: Diplo Opinion Change 4
AI_OPERATION_DESTROY_BARBARIAN_CAMP : Ended: Lost Path to Target 2 -- Ended: War State Change 7 -- Ended: Success 8 -- Ended: No muster point 8
AI_OPERATION_CITY_SNEAK_ATTACK : Ended: Success 10 -- Ended: Diplo Opinion Change 7
AI_OPERATION_NAVAL_INVASION : Ended: Diplo Opinion Change 2
AI_OPERATION_ALLY_DEFENSE : Ended: Half strength 3 -- Ended: War State Change 4 -- Ended: Timed Out 3
AI_OPERATION_CITY_CLOSE_DEFENSE : Ended: Success 5 -- Ended: Diplo Opinion Change 5
AI_OPERATION_RAPID_RESPONSE : Ended: Half strength 2 -- Ended: No Units 2 -- Ended: No target 3 -- Ended: Diplo Opinion Change 3
AI_OPERATION_DIPLOMAT_DELEGATION : Ended: Success 6
AI_OPERATION_NAVAL_INVASION_SNEAKY : Ended: Cancelled 2 -- Ended: Diplo Opinion Change 6
AI_OPERATION_FOUND_CITY_QUICK : Ended: Half strength 2 -- Ended: Success 18 -- Ended: No target 4
AI_OPERATION_NAVAL_SUPERIORITY : Ended: No target 4
AI_OPERATION_FOUND_CITY_OVERSEAS : Ended: Success 2
AI_OPERATION_PILLAGE_ENEMY : Ended: Success 2 -- Ended: No target 2
AI_OPERATION_FOUND_CITY : POST At Target 2 -- Ended: Success 7 -- Ended: No target 3
```

**Comment by biship** [comment] 2016-06-01 23:43
@ilteroi why does your (current) fefe version of "Community Patch.civ5proj" still contain the error listed in issue 1704?
https://github.com/LoneGazebo/Community-Patch-DLL/issues/1704
Duplicate saneterrain.sql

**Comment by LoneGazebo** [comment] 2016-06-02 01:59
Awesome @ilteroi. I've been swamped with work lately but I'll get on this (and my other issues on here) over the next few days.

**Comment by LoneGazebo** [comment] 2016-06-02 02:00
Any noticeable improvements on the AI front regarding the operations?

**Comment by ilteroi** [comment] 2016-06-02 06:17
@biship : good question, i don't know - if it's in master, it should have been merged ...

@LoneGazebo : i sure like to think so, but i don't have baseline data to prove it ... anyway it seems all the outcomes in the logs make sense and that's after removing 4000 lines of code :)

**Comment by biship** [comment] 2016-06-02 09:41
Time to get fefe into master, then whack and recreate fefe?

**Comment by biship** [comment] 2016-06-11 23:57
fefe: This branch is 201 commits ahead, 10 commits behind master.
:(

**Comment by ilteroi** [comment] 2016-06-12 09:21
good news ... i've merged :)

**Comment by biship** [comment] 2016-06-12 10:10
Theres still something wrong with fefe. It doesn't have at least the fix in 1704, and is 203 commits ahead of master. Isn't it best to get the fefe changes into master, then delete and recreate fefe? There might be other updates to master missing from fefe...

**Closed** 2016-06-15 01:17 UTC
