### ISSUE TITLE
8/16 - Unit pathing incorrect

### ISSUE THREAD

**Issue by JohannesGaessler** [LoneGazebo/Community-Patch-DLL#6913] opened 2020-08-17 10:20 UTC
_1. Mod version (i.e Date - 4/17):_
8/16 after Gazebo applied the hotfixes

_2. Mod list (if using Vox Populi only, leave blank):_

* Really Advanced Setup
* Wonder Race
* I'm playing on Linux via WINE

_3. Error description:_ 
There seems to be a problem with pathing when Units cannot reach the goal in a single turn.
It looks to me like the pathing assumes that the Units have more movement than they actually have.

Files: 
[debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5083644/debug.zip)

Screenshot:
![20200817120547_1](https://user-images.githubusercontent.com/18492268/90385516-9007f680-e083-11ea-961d-1002dccb4ec0.jpg)

**Comment by RecursiveVision** [comment] 2020-08-17 10:21
Duplicate of #6902

**Comment by LoneGazebo** [comment] 2020-08-19 21:44
Fixed.

**Closed by LoneGazebo** 2020-08-19 21:44 UTC
Labels: Fixed for upcoming version, Paging Dr. Ilteroi

**Comment by LoneGazebo** [comment] 2020-08-19 21:45
@ilteroi used MOVE_DENOMINATOR, which is 60, for checks that are usually 1-4 in value. Whoopsies!
