### ISSUE TITLE
Frequent CTDs after updating

### ISSUE THREAD

**Issue by Circine** [LoneGazebo/Community-Patch-DLL#8884] opened 2022-05-16 21:47 UTC
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.2.0, DX 10 & 11):_
2.2 VP+EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Frequent crashes in early game, usually during my own turn when viewing the city screen.

_4. Steps to reproduce (optional):_
It's not a consistent crash, I can load up the game and continue an uncertain number of turns before it happens again, but it's pretty common. It seems like it only happens after researching fishing and setting boats down, however.
Tried verifying Civ5 files and reinstalling VP already.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8703574/Logs.zip)
2. Save game
[AutoSave_0040 BC-2400.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8703581/AutoSave_0040.BC-2400.zip)
3. CvMiniDump.dmp file
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8703585/CvMiniDump.zip)

**Comment by AndreyK-555** [comment] 2022-05-18 04:50
I have same issue

**Comment by maarten99** [comment] 2022-05-19 18:55
I haven't noticed more crashes than usual this patch.
My game only CTD's late game (a lot of units on screen) upon opening the tech tree

**Comment by cidk2000** [comment] 2022-05-24 14:42
CTD late game from industrial practically every turn at random.
Most frequently when I open the science screen to choose a Technology roughly 80% of the time CTD.  

Vox Populi with EUI 

If I reload the save and do something different before selecting a technology it may not CTD.

I have less frequent crashes on my laptop playing the same game I cant seem to pin down the issue  both are AMD systems 64bit  major diffence is RAM size and graphics 32gb VS 8bg a 6700xt vs a mobile vega  - crashes happen more late game on my desktop vs laptop.

late game standard map originally 5 players now 3 

[catherine.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8763762/catherine.zip)

**Comment by nobubblegums** [comment] 2022-05-24 18:59
It's really weird that Tech screen is somehow linked with CTD, @maarten99 @cidk2000 can you share your lua log after next time it happens?

**Comment by RecursiveVision** [comment] 2022-05-26 09:14
Crashes when opening the tech screen are usually caused by insufficient memory @nobubblegums

**Comment by cidk2000** [comment] 2022-05-26 10:23
Question remains how can I allocate more ram to a 32bit game running on a 64bit platform if im on a standard game less than 5 players (4 AI) id imagine id be crashing well before industrial if the map was huge and 12 players and lots of units? I think civ5 .exe is LBA?

**Comment by RecursiveVision** [comment] 2022-05-26 12:39
@cidk2000 Are you using any additional mods?

**Comment by RecursiveVision** [comment] 2022-05-26 12:42
```
Gamecore Callstack

Lua Callstack
=[C] (-1): IsWork
C:\Documents\My Games\Sid Meier's Civilization 5\MODS\(3a) VP - EUI Compatibility Files\LUA\UnitFlagManager.lua (512): UpdateAutomateFlag
C:\Documents\My Games\Sid Meier's Civilization 5\MODS\(3a) VP - EUI Compatibility Files\LUA\UnitFlagManager.lua (522): ?
=[C] (-1): ?
=[C] (-1): ?
```

**Comment by cidk2000** [comment] 2022-05-26 13:39
> @cidk2000 Are you using any additional mods?

no additional mods Vox Populi  only active 
![Screen shot of mods](https://user-images.githubusercontent.com/106168061/170498732-dd13b1cb-4631-42c9-af31-3121a2140a47.jpg)

two other mods inactive but installed 

the logs folder is overwritten with a completed game ill reload the catherine save and play a few turns and replicate the crash then add additional logs will be added

**Comment by nobubblegums** [comment] 2022-05-26 15:10
@RecursiveVision That's weird, I can't see how they would cause an issue, especially without throwing any errors in lua.log. Maybe the "automated" icons finally pushes the memory out of range? The first save has two dlc mappacks I don't have, I couldn't load it. 

Can you (or @Circine ) try replacing the UnitFlagManager.lua & xml (in (3a) VP - EUI Compatibility Files\LUA) with this to see if it helps? It's basically the old flag manager without automated icons.

[UnitFlagManager.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8779950/UnitFlagManager.zip)
.

**Comment by nobubblegums** [comment] 2022-05-26 19:09
@cidk2000 Thanks for the logs, though they show no errors. That said, judging from the logs Barbarian Spawn mod seems to be active. Sometimes mods still load when not selected, like if you start a game with a mod active and then disable it when you next time you go into the game, it still gets loaded. I think I've heard of some cases where mods loaded even if they were never selected, but never tested that myself. You can try removing that mod from the MODS folder, or moving it out temporarily. 
I'm still able to continue with the save you provided (tried both vp 2.2.0 and 2.2.1), but your second save doesn't seem to be different than the first one.

**Comment by cidk2000** [comment] 2022-05-26 20:00
@nobubblegums thanks for taking your time to look at the logs, I cleared the mods from the folder (the barbarian spawn, exp etc ) by unsubscribing from the steam workshop.

loaded the catherine save from a machine power cycle with just Vox Populi and I put medical labs in the build queue then did proposed a world congress option then a trade unit to another city, pressed next turn then after a a few seconds of processing a pop up occured of building a wonder think it was cristo redento ? then crash to desktop...

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8781727/Logs.zip)

**Comment by maarten99** [comment] 2022-05-26 20:24
@RecursiveVision 
> Crashes when opening the tech screen are usually caused by insufficient memory @nobubblegums 

I'm assuming the game has memory limit? Since I have plenty of system memory left when playing civ 5.

**Comment by Circine** [comment] 2022-05-26 23:48
@nobubblegums Both those .zips are the same, but I didn't crash in a couple games up to turn 70~ using those files. Tried a couple games with unmodified 2.2.1 before that and crashed like clockwork by turn 40 so maybe that's it. I'll continue testing later.
For what it's worth, the crashes on unmodified 2.2.1 took place once when reassigning citizens and once immediately after opening the city screen, before clicking anything else.

**Comment by cidk2000** [comment] 2022-05-27 09:41
update 10:30 BST (UK Time)- CTD turn 249 after video settings turned down to see if they contribute to crash.  I think last thing I did was send a frigate on auto explore 

[AutoSave_0249 AD-1695.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8785572/AutoSave_0249.AD-1695.zip)

logs as of CTD  

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8785598/Logs.zip)

GPU log shows a dip again at around the crash but looking up its core clock dips to 0.0 temps never exceed 60c log file is over 2meg uncompressed 

[GPU-Z Sensor Log.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8785616/GPU-Z.Sensor.Log.zip)

**Comment by nobubblegums** [comment] 2022-05-27 15:20
@cidk2000 Have you tried the files I posted above https://github.com/LoneGazebo/Community-Patch-DLL/issues/8884#issuecomment-1138682663 . Also I can open minidumps now, can you upload it next time it crashes? It should be generated in the Civ5 base directory (like \path\steamapps\common\Sid Meier's Civilization V)

**Comment by cidk2000** [comment] 2022-05-27 16:39
@nobubblegums ill replace and get back to you turning down the graphics also has made a huge difference I had two crashes that last game both in the comments above

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8788114/CvMiniDump.zip) this is the 10:30 crash on turn 249.

ill make the changes to the files above as requested and let you know the results if I have a clean game ill let you know regardless

**Comment by ilteroi** [comment] 2022-05-27 17:20
@nobubblegums : are you sure your unit pointer in lua is always valid?

**Comment by nobubblegums** [comment] 2022-05-27 21:18
I thought it was but adding nil checks before removing IsWork makes sense. 
 
@cidk2000 Happy to hear that, I always play on dx9 and without AA,  maybe that's why I didn't experience the tech screen crashes. Thanks for the minidump, yours also point out to the same function. I'm confident that the files I posted above will fix that particular crash.

**Comment by RecursiveVision** [comment] 2022-05-28 11:23
@nobubblegums Most frequent cause of this kind of crash is a bad unit pointer. != NULL checks may fix it.

**Comment by cidk2000** [comment] 2022-05-28 19:27
@nobubblegums had a CTD very late game on a new game with the new changes as specified went an entire game until 2 or 3 turns from winning. Opened tech screen. CTD 
Guessing this has nothing to do with the flags mentioned earlier. Graphics is lower than normal I pushed the boat out with Large map and 8 players this time 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8791731/Logs.zip)
[AutoSave_0372 AD-1952.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8791734/AutoSave_0372.AD-1952.zip)
Surprised to see a dmp file at 0kb
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8791735/CvMiniDump.zip) - guess this wasnt a programming crash ?

**Comment by nobubblegums** [comment] 2022-05-28 20:21
@cidk2000 Yeah, apparently the game didn't create a proper minidump, it can't be opened, callstack.log was generated but is empty. I can't trace the cause, but at least we can say that flags aren't an issue anymore. Thanks a lot for helping out!
@RecursiveVision there's one lua error for TradeLogic @ 620, thought you might be interested in it, though it is probably not a big deal, There's another one from UnitPanel upgrade help text, I don't remember any changes to that but I'll try to reproduce it.

**Closed** 2022-05-29 12:16 UTC
Labels: Fixed for upcoming version, CTD, Watch this in the next release
