### ISSUE TITLE
Targeting of invisible units

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2297] opened 2016-08-08 07:08 UTC
Bug Report Template

Mod Version (i.e Date - (4/23b)):
August 8th

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Same error as #2221 

3. Steps to reproduce:

4. Additional information:
Screenshot of error:
![civ5screen0012](https://cloud.githubusercontent.com/assets/3291695/17471873/a5c09c3c-5d8a-11e6-85df-edefb4b058bf.jpg)

Savegame at this stage:
[Pedro II_0136 AD-0520.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/406240/Pedro.II_0136.AD-0520.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by pandasnail** [comment] 2016-08-08 14:11
So I'm very confused by this screenshot. I've only seen this with units that can't attack and that are attempting to move into a tile it turns out have a unit, particularly an enemy. So an embarked unit or a ranged unit, or even a citizen unit if it has enough move to move out of its sight range. But what can't a Barbarian Horseman attack? The city itself I guess?

Also, you probably need a save from before it happens, so they can watch it happen in the code. I realize they're hard to plan, but, at least if my games are an indication, you'll get some in naval warfare eventually if you save every turn. I play with other mods, so I can't post a save myself tho. I actually kinda enjoy the fun animations it gives, (you seen a Dromon fire across like five tiles yet?)-once I got used to having to manually look where the enemies really are, like I said especially in naval combat.

**Comment by LoneGazebo** [comment] 2016-08-08 17:22
@ilteroi, my assumption here is that unitmission queues are not being cleared properly, such that tiles that formerly held a unit still retain the data of that unit. That, or the UI is being stupid.

In any case, a save game on this is absolutely essential. You got the screenshot, so next time it happens, immediately save and upload.

**Comment by pandasnail** [comment] 2016-08-08 17:41
He does appear to have a save, under the screenshot, I was saying that I thought a save would need to be before the unit moves, so you two can watch the move, but if that's not the case, my bad.

**Comment by LoneGazebo** [comment] 2016-08-08 18:38
Didn't see save, thanks for pointing out.

**Comment by ilteroi** [comment] 2016-08-08 19:17
unfortunately i cannot load the save ... it crashes with both 8.2 and 8.8

**Comment by ilteroi** [comment] 2016-08-08 21:19
anyway for this arrow to appear,  canRangeStrikeAt() must return true. i cannot reproduce it.

**Comment by Iamblichos** [comment] 2016-08-08 22:00
The actuality of the unit is @ the city strike range, it tried to move further up and ran into a place the pathfinder would not let it go in its final destination plot. The graphic of the unit lies in between somewhere and isn't the real place of the unit.

**Comment by Iamblichos** [comment] 2016-08-08 22:00
Need to get a save he can load so he can see it.

**Comment by GrantSP** [comment] 2016-08-08 22:14
The reason you may be having issues loading is because of the script changes I made to Communitas.
I've re-committed them [here](https://github.com/LoneGazebo/Community-Patch-DLL/commit/64f8cd1b2e6b68eb7c2f4a66528cb994ff08965f).
Whatever method @LoneGazebo uses to maintain his personal repository keeps reverting any changes I make. I've made this commit 3 times now.

Let me clarify a little more what is happening.
My garrison archer has just killed another barbarian horse and the firing you see here is from the city itself. The only reason I noticed this is because there where no visible units in range but the city firing target was still active.

**Comment by LoneGazebo** [comment] 2016-08-09 01:07
And the barbarian horse was there?

**Comment by GrantSP** [comment] 2016-08-09 01:25
Just loaded up the save and now there IS a barbarian horseman. It wasn't visible during the initial playthrough so I'm not sure if it now showing up is helpful or not.

**Comment by pandasnail** [comment] 2016-08-09 01:56
OK, so I'm going to try to explain it in more detail for yall, I've seen this maybe 30 times now, I'm not a genius no, but I think I've seen it enough to know how it works.

Unit A, let's say an embarked Lancer has idk 4 move and 1 vision. The player controlling the Lancer (AI or human) tries to move it all four tiles to another water tile that the player does not have active vision on. If that tile contains something the Lancer cannot attack, a boat or another embarked unit, ie Unit B. Unit A will actually stop 1 tile, or whatever its vision number is, from Unit B. So an embarked Lancer would stop 1 tile away, a Galleass would stop two or three or whatever, can't remember the vision on boats right now, but not important. However, for whatever reason, the graphic for the unit will stay on the original tile until it moves again or it sounds like if the save is reloaded. Its not that the Horseman in Grant's screenshot was missing, the graphic was somewhere else, either its the Horseman we see to the Northeast or out of frame to the East.

Everything that should be able to attack the unit can onto its correct tile, units can move around properly. Everything works for the AI as well, they 'see' the unit as it should be. It just leads to weird animations where a Dromon attacks 5 tiles or whatever. And that you have to manually look for enemy units, especially in the water, with so many embarked.

Does that make sense?

**Comment by GrantSP** [comment] 2016-08-09 03:35
Yeah, that about equates to what I see also.
I think it is also related to the odd behaviour when you use your mouse to move an unit to an obscured tile. The path-finding sees a unit which cancels that move but then you can no longer move that unit with your mouse, you MUST use the keyboard instead.
A bit obscure as it rarely comes up with my games but seems to be similar. Probably also something to do with the way units can, on turn end, be on the same tile and then next turn automatically move on.

**Comment by ilteroi** [comment] 2016-08-09 05:53
ok that gives me an idea what's happening.

**Comment by pandasnail** [comment] 2016-08-09 09:45
Yeah, animations on for both movement and combat.

**Comment by ilteroi** [comment] 2016-08-09 19:12
no time to test it right now, but i think i got it. care to try this and give me feedback?
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/409720/CvGameCore_Expansion2.zip)

**Comment by pandasnail** [comment] 2016-08-09 20:22
Tested it out with an England Industrial Era start, and your fix works! Unit graphics ended up where they should every time.

**Comment by GrantSP** [comment] 2016-08-09 22:22
Glad it worked although I also had animations turned off.

**Comment by ilteroi** [comment] 2016-08-10 06:22
closing this then

**Closed by ilteroi** 2016-08-10 06:22 UTC
Labels: Paging Dr. Ilteroi

**Comment by LoneGazebo** [comment] 2016-08-10 06:37
I added to 8-9 BTW.
