### ISSUE TITLE
Another strange behavior with tiles yields (Golden Age)

### ISSUE THREAD

**Issue by Zarrk** [LoneGazebo/Community-Patch-DLL#4431] opened 2018-05-23 21:07 UTC
_1. Mod version (i.e Date - 4/23):_
5-20-3

_2. Mod list (if using Vox Populi only, leave blank):_
VP no EUI + IGE

_3. Error description:_ 
Entering a Golden Age no extra gold will be added to tiles already producing one. It concerns every type of tiles and will stay true for subsequents turns.

_4. Steps to reproduce (optional):_

**Comment by Iamblichos** [comment] 2018-05-24 04:02
Confirmed will look.

**Comment by Iamblichos** [comment] 2018-05-24 04:12
Yeah I see what's going on. We never get passed the yieldthreshold check because there (normatively) no plots that are getting yields in calculateplayeryield. So this needs to be put somewhere after the total sum of the plot has been evaluated. Could be religion, nature yield, improvement yield, etc.

**Comment by Iamblichos** [comment] 2018-05-24 04:17
By my lights, we need to move this out of calculatePlayerYield() and at the tail end of calculateYieldFast():

```
if (kPlayer.isGoldenAge())
	{
		if (iYield >= kYield.getGoldenAgeYieldThreshold())
		{
			iYield += kYield.getGoldenAgeYield();
		}
	}
```

**Comment by Iamblichos** [comment] 2018-05-24 04:35
Okay fixed. @LoneGazebo: you agree with moving this here in calculateYieldFast()

```
CvPlayer& kPlayer = GET_PLAYER(ePlayer);
	const CvYieldInfo& kYield = *GC.getYieldInfo(eYield);
	int iYield = calculateNatureYield(eYield, ePlayer, false, bDisplay);
	iYield += calculatePlayerYield(eYield, ePlayer, eImprovement, pOwningCity, pMajorityReligion, pSecondaryPantheon, bDisplay);
	iYield += calculateImprovementYield(eImprovement, eYield, ePlayer, false, eRoute);
	iYield += calculateReligionImprovementYield(eImprovement, eYield, ePlayer, pOwningCity, pMajorityReligion, pSecondaryPantheon);
	iYield += calculateReligionNatureYield(eYield, ePlayer, pOwningCity, pMajorityReligion, pSecondaryPantheon);
	if (ePlayer != NO_PLAYER && kPlayer.isGoldenAge())
	{
		if (iYield >= kYield.getGoldenAgeYieldThreshold())
		{
			iYield += kYield.getGoldenAgeYield();
		}
	}
```

**Comment by LoneGazebo** [comment] 2018-05-24 05:21
No need - much much easier to just pass the existing yield to the function and see if it's above the threshold. I'll work something up.

**Comment by Iamblichos** [comment] 2018-05-24 06:56
If you just pass it to the end of the function and then check with the threshold (which is meant to look for at least 1 gold yield on a plot), you’ll just be putting 1 gold on every city plot.

**Comment by LoneGazebo** [comment] 2018-05-24 15:01
No, I’m saying move player yield changes to the last in the list and pass the current yield value for gold into the function as a parameter. Then we know if the tile is making the amount of gold needed without redefining player or anything. Passing values as parameters (especially into) is especially cheap!

**Comment by Iamblichos** [comment] 2018-05-24 16:35
Gotcha. Duh.

**Comment by Iamblichos** [comment] 2018-05-24 16:41
We should probably have it ordered right something like Nature, Religion Nature, Improvements, Religion Improvements, and then Player yield at the end.

**Comment by LoneGazebo** [comment] 2018-05-24 19:33
@Iamblichos that's how it was ordered before your bugfix. ;)

**Comment by Iamblichos** [comment] 2018-05-24 20:02
Dang.

**Closed** 2018-06-01 22:19 UTC
Labels: Fixed for upcoming version
