### ISSUE TITLE
Horses that already attacked can capture cities directly

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#1980] opened 2016-06-16 18:34 UTC
Bug Report Template

Mod Version (i.e Date - (4/23b)):

6/15

1. Mod List (if using standard CPP set, leave blank):

Vox Populi Complete with EUI
+
Faster Aircraft Animations Version 3
Global - City State Airbases Version 3
Global - Commander Influence Borders Version 1
InfoAddict Version 22
Quick Turns Version 10
Really Advanced Setup Version 15
Religion - Fixed Prophets Version 2
UI - Enhanced Demographics Version 6
UI - Summary Antiquities Version 2
UI - Summary Luxuries Version 13
UI - Summary Specialists Version 11
UI - Trade Opportunities Version 28

2. Type of error (i.e. crash, interface bug, AI quirk): 

Gameplay issue

3. Steps to reproduce:

- Kill an enemy with a horseman, and have some moves remaining (orange color next to moves).
- With those move remaining attack an undefended city.
- The city is captured without any attack animations, similar to undefended barbarian camps.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment] 2016-06-16 18:54
@ilteroi, also related to mission quirks? Seems like units aren't completing/switching mission types in-between move types.

**Comment by ilteroi** [comment] 2016-06-16 20:29
cannot reproduce this either. i bet there's another merge error somewhere.

**Comment by LoneGazebo** [comment] 2016-06-16 21:42
@ilteroi turn on movement animations. I merged fefe the other day, had no errors.

**Comment by ilteroi** [comment] 2016-06-17 06:20
disabled quickturns and turned on animations, still no problem. and i'm on 6/14. what's going on here?

**Comment by LoneGazebo** [comment] 2016-06-17 06:37
Get on 6-15-1, and put a melee unit two spaces away from a barb melee unit. Turn on animations so that you can watch them. Have the melee unit attack the other melee unit from two spaces away in one move. The barb unit will move out of the way. For some reason, the DLL is treating the 'attack' move as a 'units are occupying the same tile' check and thus doing the 'jumptovalidplot' function for the barb unit. Seems the mission_move is not being replaced or reset for the attack mission (this may also explain why units are auto-capturing cities without taking damage or dealing it).

**Comment by LoneGazebo** [comment] 2016-06-17 06:38
I traced the function in the dll and this is exactly what happened. Jumptovalidplot was called as a part of a move after the attacking unit ended up on the defending unit's tile (instead of actually attacking it).

**Comment by LoneGazebo** [comment] 2016-06-18 01:14
https://github.com/LoneGazebo/Community-Patch-DLL/issues/1987

**Comment by LoneGazebo** [comment] 2016-06-18 01:15
and https://github.com/LoneGazebo/Community-Patch-DLL/issues/1970

**Comment by ilteroi** [comment] 2016-06-25 09:59
closing as duplicate

**Closed by ilteroi** 2016-06-25 09:59 UTC
Labels: Paging Dr. Ilteroi
