### ISSUE TITLE
4.5 Border growth can't go further than fourth ring

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#10688] opened 2024-02-28 01:22 UTC
Border growth can't go further than fourth ring. It used to go up to fifth ring in previous versions : 

![20240228021556_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/64471766/5b961218-2d9b-4168-af37-69f60f2f8213)

![20240228021937_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/64471766/24113aad-af53-45f0-929a-7db899c88b16)

**Comment by radziu93** [comment] 2024-03-01 18:59
I might be wrong, but this was also a thing before 4.5 (4.4.2 I have also has it), and probably not a bug then? Might be worth it to check chanelogs of few latest version to make sure if it was intended.

**Comment by Zuizgond** [comment] 2024-03-01 21:25
I didn't play with 4.4.2 but before that cities used to go up to 5th ring and I don't see any VP congress proposals asking to reduce it to 4th ring.
I actually don't mind the change but I think this needs VP congress approval if we want to go that way.

**Comment by axatin** [comment] 2024-03-07 23:46
It wasn't intentionally changed afaik.

In CvCity::GetBuyablePlotList, it says
```
SPathFinderUserData data(getOwner(), PT_CITY_INFLUENCE, iMaxRange);
ReachablePlots influencePlots = GC.GetStepFinder().GetPlotsInReach(pThisPlot, data);
```
iMaxRange has the correct value of 5, but influencePlots only contains plots up to a distance of 4. @ilteroi Do you know if that's intended? Should iMaxRange+1 be used?

**Comment by KungCheops** [comment] 2024-03-10 07:37
I believe there was a bug for a long time where iMaxRange was set to INT_MAX instead of 5 for city influence. Was influence capped at distance 5 before or was it uncapped?

It being able to reach 5 tiles away may in fact have been a bug.

**Comment by axatin** [comment] 2024-03-10 09:46
It should go up to five tiles, there‘s a define value that controls it (MAXIMUM_ACQUIRE_PLOT_DISTANCE).

**Comment by bsesar** [comment] 2024-03-10 10:28
Please correct me if I'm wrong, but I thought that all cities can work up to and including the third ring and Tradition finisher extends that range by +1 tile

https://forums.civfanatics.com/threads/1-06-tradition-changes-proposals.679953/

**Comment by ilteroi** [comment] 2024-03-10 17:09
> It wasn't intentionally changed afaik.
> 
> In CvCity::GetBuyablePlotList, it says
> 
> ```
> SPathFinderUserData data(getOwner(), PT_CITY_INFLUENCE, iMaxRange);
> ReachablePlots influencePlots = GC.GetStepFinder().GetPlotsInReach(pThisPlot, data);
> ```
> 
> iMaxRange has the correct value of 5, but influencePlots only contains plots up to a distance of 4. @ilteroi Do you know if that's intended? Should iMaxRange+1 be used?

should be inclusive but maybe not? need to test it

**Comment by azum4roll** [comment] 2024-03-14 08:35
It should NOT be taking iMaxRange. That parameter is iMaxTurns and should not be related to distance.

**Comment by azum4roll** [comment] 2024-03-14 08:47
> I believe there was a bug for a long time where iMaxRange was set to INT_MAX instead of 5 for city influence. Was influence capped at distance 5 before or was it uncapped?
> 
> It being able to reach 5 tiles away may in fact have been a bug.

That line has never been changed.

**Comment by ilteroi** [comment] 2024-03-14 13:14
turns and range are the same for the "influence pathfinder" iirc

**Comment by azum4roll** [comment] 2024-03-15 01:46
> turns and range are the same for the "influence pathfinder" iirc

Can't be. The tile picker prioritizes tiles easier to reach first, and avoids tiles across a river. It also never grows to ocean prior to Astronomy.

**Comment by KungCheops** [comment] 2024-03-18 16:09
> > turns and range are the same for the "influence pathfinder" iirc
> 
> Can't be. The tile picker prioritizes tiles easier to reach first (especially if routed), and avoids tiles across a river. It also never grows to ocean prior to Astronomy.

Turns is not the same thing as cost.

**Comment by azum4roll** [comment] 2024-03-19 03:45
Either way we need a fix (or a bandaid) for this quick. This is quite critical.

**Comment by KungCheops** [comment] 2024-03-19 21:01
Do we know what the intended behavior is?

**Comment by axatin** [comment] 2024-03-19 21:28
I used debug config with the previous version and the current one and found the cause of the changed behavior:

In the previous version, `SPathFinderUserData data(getOwner(), PT_CITY_INFLUENCE, iMaxRange);`  used the constructor `SPathFinderUserData::SPathFinderUserData(PlayerTypes _ePlayer, PathType _ePathType, int _iTypeParameter, int _iMaxTurns, bool _bIsForCapital)`, so the value iMaxRange was not assigned to `iMaxTurns`, but to `iTypeParameter`. `iMaxTurns` stayed at INT_MAX.
![Screenshot (563)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/95587882/be6c4497-effb-47cb-a272-a93f86d11353)

`iTypeParameter` was used for influence pathfinding:
```
int InfluenceValid(const CvAStarNode* parent, const CvAStarNode* node, const SPathFinderUserData& data, const CvAStar* finder)
{
...
	if(plotDistance(*pOrigin,*pToPlot) > data.iTypeParameter)
		return FALSE;
}
```


In this version,  `iTypePathfinder` has apparently been replaced by  `iMaxTurns` in `InfluenceValid`, and that's a problem because in the pathfinding algorithm we have these lines,
```
NodeState CvAStar::LinkChild(CvAStarNode* node, CvAStarNode* check)
{
	//we would have to start a new turn to continue
	if(node->m_iMoves == 0)
		if (node->m_iTurns+1 >= m_sData.iMaxTurns) // path is getting too long ...
			return NS_FORBIDDEN;
```
so paths with a length of iMaxRange are already considered too long. The change should be reverted

**Closed** 2024-03-25 14:48 UTC
Labels: Fixed for upcoming version
