### ISSUE TITLE
10-7-2 CTD on map generation

### ISSUE THREAD

**Issue by JanSobus** [LoneGazebo/Community-Patch-DLL#7141] opened 2020-10-11 08:13 UTC
_1. Mod version (i.e Date - 4/17):_ 10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_
![mod_list](https://user-images.githubusercontent.com/17416468/95673545-b57d3080-0bec-11eb-800d-79f51334a5b4.png)

_3. Error description:_ 
CTD on map start - tried to create a new game as Songhai, huge frontier map - game crashes before the map shows up. 
Tried several times, different map sizes - same result every time.
Logs and dump included

 
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5360757/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5360760/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by bsesar** [comment] 2020-10-11 08:19
Probably a duplicate of #7127 .

**Comment by JanSobus** [comment] 2020-10-11 08:38
I honestly doubt it's the same thing, my Lua log is clean. I have some ERR in Localization Log though:
```
[1800532.640] ERR: Missing argument 2. (All who live under {2_CivDescription} rule are pledged to travel with me through the next world. But what about all those who lived in ages gone by? We must exhume every grave we have record of! Set the priests to it!)
[1800532.640] ERR: Failed to evaluate parameter 1. All who live under {2_CivDescription} rule are pledged to travel with me through the next world. But what about all those who lived in ages gone by? We must exhume every grave we have record of! Set the priests to it!
[1800535.156] ERR: Missing argument 2. (All who live under {2_CivDescription} rule are pledged to travel with me through the next world. But what about all those who lived in ages gone by? We must exhume every grave we have record of! Set the priests to it!)
[1800535.156] ERR: Failed to evaluate parameter 1. All who live under {2_CivDescription} rule are pledged to travel with me through the next world. But what about all those who lived in ages gone by? We must exhume every grave we have record of! Set the priests to it!

```

**Comment by azum4roll** [comment] 2020-10-12 02:45
Does it work with other maps? (Continents etc.)

**Comment by JanSobus** [comment] 2020-10-12 03:20
Crashes on other maps too

**Comment by Mileslewis** [comment] 2020-10-12 13:20
So no maps are working? Try to find out which mod is causing it I suppose.

**Comment by JanSobus** [comment] 2020-10-13 07:16
Ok, so the thing is I always play with a modpack and the crash is happening. Today I tried playing with the same mods through MODS menu and it's working all fine ... The modpack creation must be getting wacky somewhere (and yes I remember about deleting ingame.lua)

**Comment by JanSobus** [comment] 2020-10-14 11:58
I build a modpack again and get the same error in logs again. The source of the error sits in TheocraticRule.xml in (7) Community events, but I have no idea why it appears in modpack game, but not in game started from modding menu.

**Comment by JanSobus** [comment] 2020-10-18 11:31
Ok, I found that "More Wonders for VP" is responsible. Even modpack built just from that single mod on top of bare VP produces the same crash. I already notified adan, but if some of you wizards could help him find the issue, that would be great.

**Closed** 2020-12-02 04:32 UTC
