### ISSUE TITLE
AI embarked units crossing ocean in Classical Era

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2420] opened 2016-08-26 07:14 UTC
Mod Version (i.e Date - (4/23b)):8-18

1. Mod List (if using standard CPP set, leave blank):
FlagPromotions

2. Type of error (i.e. crash, interface bug, AI quirk): 

3. Steps to reproduce:
An AI (Dutch) warrior is seen at an ocean tile. They only discovered 16 technologies which means they are still in Classical Era.

![20160826100817_1](https://cloud.githubusercontent.com/assets/16341598/17997182/a7d0457e-6b75-11e6-8edc-a4fc3d7b7e88.jpg)
[Embarked.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/438731/Embarked.zip)

**Comment by ilteroi** [comment] 2016-08-29 18:10
should be fixed. though i don't understand how it could happen in the first place

**Comment by Enrico-Swagolo** [comment] 2016-08-29 19:24
I see the same happening with ships. Triremes/Dromons of my enemies often end up on ocean tiles, often not ever moving afterwards.

**Comment by ilteroi** [comment] 2016-08-29 20:36
hmm. my change was only for embarked units. back to square one ...

**Comment by ilteroi** [comment] 2016-08-30 21:13
ok found the root cause

**Comment by LoneGazebo** [comment] 2016-08-30 21:14
Celebratory open/close.

**Closed by LoneGazebo** 2016-08-30 21:14 UTC
