### ISSUE TITLE
Bandeirantes UnitPanel broken

### ISSUE THREAD

**Issue by nobubblegums** [LoneGazebo/Community-Patch-DLL#8494] opened 2021-12-28 22:32 UTC
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_
VP with EUI

_3. Error description:_ 
Bandeirantes UnitPanel is bugged and doesn't display the proper unit icon. Lua log returns this error:
[505638.640] Runtime Error: My Games\Sid Meier's Civilization 5\MODS\(6a) Vox Populi - Compatibility Files (EUI)\LUA\UnitPanel.lua:596: bad argument #1 to 'GetNumResourceRequiredForImprovement' (number expected, got nil)

1.2.x doesn't have this issue

**Comment by bsesar** [comment] 2022-02-03 07:24
Duplicate of  #8420.

**Comment by nobubblegums** [comment] 2022-04-28 21:32
As bsesar commented, this sometimes happens with other units, with the same error. I cannot see a pattern though

**Closed** 2022-05-09 05:24 UTC
