### ISSUE TITLE
Barbs not getting promotions?

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#660] opened 2015-09-26 23:33 UTC
It seems that barbs are not starting with any promotions in version 9-24.

**Comment by LoneGazebo** [comment] 2015-09-27 21:43
Can't reproduce, seems fine to me.
G

**Comment by Edaka** [comment] 2015-09-27 22:54
Well, barbs in my latest game (v24/9) don't have their terrain related promotions, either. I haven't really made sure that no other mods except for CPP are involved, but will do tomorrow and report back.

**Comment by LoneGazebo** [comment] 2015-09-28 03:38
Went back, was able to reproduce (turns out the barbs were not getting them in certain situations). Fixed in latest version (9/27v2)

**Closed by LoneGazebo** 2015-09-28 03:38 UTC
Labels: cannot reproduce
