### ISSUE TITLE
GameEvents.ResolutionResult and Events.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3102] opened 2017-02-23 05:55 UTC
For future purposes later that JFD might perhaps ever add resolutions and tried to add dummy events through those custom resolutions once more... You can't apply an event from lua with ResolutionResult since the event probably fires only on the owner.
````
function MovingSwiftly (iResolution, iProposer, iChoice, bEnact, bPassed)
	if iResolution == iSphere then
		print("Working?")
		local minorPlayer = Players[iChoice]
		local majorPlayer = Players[iProposer]
		if bEnact and bPassed then
			print("Wait a grumbling second.")
			if majorPlayer:GetEventChoiceCooldown(GameInfoTypes["PLAYER_EVENT_CHOICE_" .. GameInfo.MinorCivilizations[minorPlayer:GetMinorCivType()].Type]) == 0 then
				majorPlayer:DoStartEvent(GameInfoTypes["PLAYER_EVENT_" .. GameInfo.MinorCivilizations[minorPlayer:GetMinorCivType()].Type])
				majorPlayer:SetEventChoiceCooldown(GameInfoTypes["PLAYER_EVENT_CHOICE_" .. GameInfo.MinorCivilizations[minorPlayer:GetMinorCivType()].Type], 10000)	
			end
		end
	end
end
````
Works very well, the cooldown is 10000; however the event never starts so the effect never applies... I'm assuming this is because since the events aren't fired at the owner's turn. The owner of the event will never get the effect...

**Comment by LoneGazebo** [comment] 2017-02-23 13:55
What about the global tag for the event?

**Comment by TechpriestEnginseer** [comment] 2017-02-23 23:12
global tag?

**Comment by LoneGazebo** [comment] 2017-02-24 01:50
Hmm, not sure.

**Comment by TechpriestEnginseer** [comment] 2017-02-26 03:41
Issue resolved by forcing event choices to exist rather than events itself.

Anyway, Event Overview needs to be looked at. It has the everlasting bug of not letting you end your turn until you do something else...

**Comment by LoneGazebo** [comment] 2017-02-26 04:11
@jfdaly I've noticed the end turn issue. Can you reproduce?

**Comment by LoneGazebo** [comment] 2017-02-26 04:11
Seems like something with the lua.

**Comment by JFDaly** [comment] 2017-02-26 09:08
Hm, can't reproduce the issue with either just CP or the entire VP. Any other conditions that tend to flare up the issue? Perhaps it only occurs later on in a game?

**Comment by LoneGazebo** [comment] 2017-02-26 15:12
Automate a unit to explore, or have a unit with move orders, and click through he tabs in the event overview. Sometimes when you close the overview the next turn button won't work until you go back into the events overview and change tabs. Usually happens as a result of opening the 'choice' tabs. 
also @JFDaly if you are happy with it I'm going to integrate the CID code in the next full version.

**Comment by JFDaly** [comment] 2017-02-26 20:00
I'll keep an eye out, but it must be sporadic.

Yeap, sounds good. Haven't finished implementing things, but as it all probably follows the same logic, if one thing works the rest should too. If not, I'll let you know.

**Comment by LoneGazebo** [comment] 2017-02-26 22:30
Sounds good. If I can create a repeatable scenario I'll let you know. My guess is that the popup isn't cleaning up properly when closing, thus it isn't letting go of the interface.

**Closed** 2017-03-08 01:20 UTC
