### ISSUE TITLE
Defense Pacts Not Triggering Properly- Friends aren't obligated to honor their DP?

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#4047] opened 2018-03-11 18:58 UTC
_1. Mod version (i.e Date - 4/23):_

2/7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Mother has been complaining for the last couple games her DPs arent working properly, this time I verified it. Only have screens but they clearly show the issue, uploading 6pics in zip -  

1st pic shows a defensive pact started with Morocco on turn 271

2nd pic shows pact still active on turn 283, and that Morroco is only at war with France

3rd shows France declared war on player turn 280 (DP worked, Morocco at war also)

4th shows Portugal declared war on player turn 281 (DP with Morocco didn't work, why?)

5th shows Greece declared war on player turn 282 (DP with Morocco didn't work, why?)

6th shows another standing defense pact player had with Polynesia, who is correctly at war with all 3 players they should be- France, Portugal and Greece

for some reason Morocco never got sucked into war with Greece or Portugal. The only thing I see now is that Morocco is friends with Greece and Portugal. Does being friends let you out of your defense pact obligations?

I'm thinking if you don't want to be at war with your friends, then don't declare war on people your friends have a defense pact with.

[Screens.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1800748/Screens.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment] 2018-03-11 20:04
It is possible that they had a cooldown preventing them.

**Comment by deadstarre** [comment] 2018-03-11 20:25
yes thats possible. mother says "if thats the case, shouldn't they enter the war at the end of their peace cooldown?"

**Comment by MoiMagnus** [comment] 2018-03-12 07:23
I'm not sure there is a (simple) way to code "delayed war declaration" (so "that Civ declare war as soon as possible")

I'm not sure too that it is possible to forbid to declare war to someone having a DP with someone you have a peace treaty with. (In some way, it should count as willingly breaking a peace treaty, since DP are publicly known)

If that's not possible, that mean we have to choose between allowing people to break peace treaties, and allowing people to break defensive pacts.

**Comment by LoneGazebo** [comment] 2018-03-12 14:16
It is possible that Mother (which, by the way, using said name in such a way has narrowed down your list of possible realhuman names to Mike Pence or Norman Bates :) ) triggered the DOW through an AI insult event. A few of those were missing originator points, so that DPs couldn't fire. We'll see if that is now fixed.

**Comment by deadstarre** [comment] 2018-03-12 18:03
Norman Bates for certain. come on man, one of those guys is a real psychopath...

anyway, i can definitely confirm she didn't trigger through an insult event, shes too nice of an old lady she doesn't do it. and confirmed, she didnt do it =)

**Comment by MoiMagnus** [comment] 2018-03-13 10:47
@LoneGazebo It remind me of an issue in MP, were DOW trough AI insult were not always working.
(Only the player insulting the AI "see" the war, for other player nothing happened. End of the turn -> desync -> No war)
Maybe that was the cause.

**Closed** 2018-04-09 20:24 UTC
