### ISSUE TITLE
Can't go next turn because of road

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3327] opened 2017-07-02 13:07 UTC
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm playing Theodora. I ordered a worker to build a road to Adrianople. Once the worker builds it and ends his turn on the city tile, it's impossible to click next turn and the map constantly shines the city tile with the worker white, implying it doesn't want to go if he doesn't receive an order. It's impossible to give him an order, though, I click on him and nothing happens. 

Savegames included. One after the happening, one before. I use regular VP with city view mod, but as always I make bonus resources instantly redeemed. Just click next turn, the worker will bug out. I always moved the missionary on the same tile and bursted him to convert adrianople, but it might be unneeded.
[single.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1117799/single.zip)

Also there's a problem with the tiles almost never showing correctly how many turns it will take to move a guy. It often considers a regular guy as if he could move through forests normally.

**Comment by ilteroi** [comment] 2017-07-02 14:40
it's already fixed. just waiting for the next release.

**Comment by ilteroi** [comment] 2017-07-04 09:58
duplicate of #3309

**Closed by ilteroi** 2017-07-04 09:58 UTC
