### ISSUE TITLE
Submarine can't attack from/into a specific spot

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#9727] opened 2023-03-21 15:48 UTC
_1. Mod Version (X.Y.Z). Current Version: 3.2.2_

3.2.2

_2. DirectX Version_

_3. List of Other Mods_

IGE+ v45

_4. Describe the Issue_

![Image](https://user-images.githubusercontent.com/14953746/226657506-dc03bccf-e335-49df-8c4d-8fc05b2cdede.png)
Highlighted submarine cannot attack the enemy submarine (or whatever ship I put there using IGE).
![Image](https://user-images.githubusercontent.com/14953746/226660096-daed5ac0-c42e-4746-86fc-19b4009fcdba.png)
Same with this.

Seems it can't attack if the flanks between it and the target are land tiles.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[IGE3.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11030626/IGE3.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by azum4roll** [comment] 2023-04-02 15:17
![Image](https://user-images.githubusercontent.com/14953746/229362155-a14cf7ec-a48e-4f18-8f30-1d7dc1fd97ec.png)
Welp, can't attack here either. There goes my hypothesis.

**Comment by Stalker012345** [comment] 2023-04-18 18:37
I just noticed this issue for the first time. I've attacked dozens of other ships with no problem with my subs, including cities. but now this ironclad is unattackable.
![image](https://user-images.githubusercontent.com/20593976/232871920-772ddd99-ac9a-4df6-bdbb-56ea69a7ac22.png)

**Comment by Stalker012345** [comment] 2023-04-18 18:37
and I can't attack it from either sub thats next to it

**Comment by ilteroi** [comment] 2023-04-19 05:37
3.3. savegame?

**Comment by axatin** [comment] 2023-05-28 15:52
The problem is that the two tiles are in different areas:
```
// Can only bombard in domain?
if (getUnitInfo().IsRangeAttackOnlyInDomain())
{
	//check areas, not domain types because we want to prevent subs from shooting into lakes
	bool bForbidden = (pTargetPlot->getArea() != pSourcePlot->getArea());
```
I'm not that familiar with plots/areas, can this be fixed by checking landmasses instead of areas?

**Comment by azum4roll** [comment] 2023-05-28 16:14
Well we don't need to prevent subs from shooting into lakes. So use domain types?

**Closed as completed** 2023-06-16 10:00 UTC
Labels: Fixed for upcoming version
