### ISSUE TITLE
Sanction does not end defensive pacts

### ISSUE THREAD

**Issue by calloatti** [LoneGazebo/Community-Patch-DLL#10631] opened 2024-02-03 16:00 UTC
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

3.7.12

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

When a civ is sanctioned by the world congress, defensive pacts are still in effect until they expire, while for example open borders are ended at once.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by vaderkos** [comment] 2024-02-05 14:58
Does sanction end all trade? I think it's ok, because the deal is made before sanctions, after sanctions no new can be done.

**Comment by axatin** [comment] 2024-02-05 20:55
Defensive pacts should be ended by sanctions, this is a bug.

It is probably caused by an error in AI deal renewals that has been fixed for the next version, so I'll close this for now. If the issue _does_ appear again in the next version, reopen the ticket and add a save game.

**Closed by axatin** 2024-02-05 20:55 UTC
Labels: Watch this in the next release
