### ISSUE TITLE
CTD on CS turn

### ISSUE THREAD

**Issue by ZetaLambdaNinja** [LoneGazebo/Community-Patch-DLL#11047] opened 2024-06-27 22:55 UTC
_1. Mod Version (X.Y.Z). Current Version: 4.10_

4.10

_2. DirectX Version_

DX 10 & 11

_3. List of Other Mods_

pdan's 34UC (v. 88.9)

_4. Describe the Issue_

In the attached save, clicking "Next Turn" will ultimately result in a CTD during the processing of the CS turns.  I have replicated the crash four times, varying what I do diplomatically with the major civs each time (renewing, or not, Maria's DoF, for example)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[BUG - CTDonCSturn.zip](https://github.com/user-attachments/files/16022059/BUG.-.CTDonCSturn.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/user-attachments/files/16022060/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.dmp](https://github.com/user-attachments/files/16022065/CvMiniDump.dmp)

_8. Steps to reproduce the Issue (Optional)_

Click "Next Turn" on the attached save.

_9. Screenshots of the Issue (Optional)_

**Comment by ZetaLambdaNinja** [comment] 2024-06-27 22:56
I saw something similar reported on #11038 .  Figured I'd upload mine as well, since the only modmod I'm running is 34uc.

**Comment by ilteroi** [comment] 2024-06-28 06:46
yep, same root cause. closing as duplicate

**Closed by ilteroi** 2024-06-28 06:46 UTC

**Comment by ZetaLambdaNinja** [comment] 2024-06-30 19:35
@RecursiveVision Yep, the turn processed normally without a crash.  Tried it twice just to be sure.
