### ISSUE TITLE
A few small bugs

### ISSUE THREAD

**Issue by crdvis16** [LoneGazebo/Community-Patch-DLL#6323] opened 2020-03-06 01:58 UTC
_1. Mod version (i.e Date - 2/9):_
3/1

_2. Mod list (if using Vox Populi only, leave blank):_
VP+EUI

_3. Error description:_ 
1- civilian units balk at entering tiles shared by non-player units.  Particularly noticeable when sending archaeologists to far away dig sites- have to reroute their pathing multiple times.

2- 'Next Turn' button visible and 'unit needs orders' button is not even though a unit needs a command to in order to actually end the turn.  Happens often after unit upgrades- have to search through your units to find the one that's stuck.

3- AI is giving large deals for strategic resources (maybe 8gpt and lux for 1 or 2 iron in industrial age).  Maybe not a bug but reporting it in case it's not intended. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment] 2020-03-06 03:15
I'm also seeing very high deals for strategics

**Comment by LoneGazebo** [comment] 2020-03-06 03:16
1&2 are probably fixed by ilteroi...3 is me, I know why.

**Comment by ilteroi** [comment] 2020-03-06 07:27
1) is actually by design, when a new unit is revealed the move mission is aborted. but i could make it only enemy units.

2. need to check

**Comment by HeathcliffWarriors** [comment] 2020-03-07 07:29
Pausing human players' units and awaiting new orders is one thing, but redirecting their pathfinding? Is that desirable? @ilteroi

**Comment by ilteroi** [comment] 2020-03-07 09:42
who said anything about redirecting?

anyway current status: unit will abort movement if a new enemy unit is revealed. try it out ...

**Comment by JamesNinelives** [comment] 2020-03-07 09:48
@HeathcliffWarriors I think what crdvis meant is simply that the units needed to be prompted to continue moving (i.e. a new path needed to be selected), rather than the pathing itself being affected.

**Comment by crdvis16** [comment] 2020-03-07 12:02
Yes, James' description is what I was seeing

**Comment by HeathcliffWarriors** [comment] 2020-03-07 21:30
Ah, I misread.

**Closed** 2020-03-16 04:43 UTC
Labels: Fixed for upcoming version
