### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by KristianWasas** [LoneGazebo/Community-Patch-DLL#11438] opened 2024-12-15 02:06 UTC
_1. Mod Version (X.Y.Z). Current Version: 4.17.6_

Version 4.17.6
VP, CP, EUI and Squads. "Default" VP mods

_2. DirectX Version_

_3. List of Other Mods_

None

_4. Describe the Issue_

Game crash to windows on citystate turn. Replicatable for me straight from the save file, just end turn and accept or decline China trade deal.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[save.zip](https://github.com/user-attachments/files/18138583/save.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/user-attachments/files/18138584/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/user-attachments/files/18138585/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by JohnsterID** [comment] 2024-12-15 03:50
Duplicate of https://github.com/LoneGazebo/Community-Patch-DLL/issues/11433.
ASSERT: https://github.com/LoneGazebo/Community-Patch-DLL/blob/master/CvGameCoreDLL_Expansion2/CvDiplomacyAI.cpp#L6630
```
>	CvGameCore_Expansion2.dll!CvDiplomacyAI::GetNoDiggingPromiseState(PlayerTypes ePlayer) Line 6630	C++
 	CvGameCore_Expansion2.dll!CvDiplomacyAI::MadeNoDiggingPromise(PlayerTypes ePlayer) Line 6681	C++
 	CvGameCore_Expansion2.dll!CvDiplomacyAI::IsBadTheftTarget(PlayerTypes ePlayer, TheftTypes eTheftType, const CvPlot * pPlot) Line 48797	C++
 	CvGameCore_Expansion2.dll!CvHomelandAI::FindHomelandTargets() Line 363	C++
 	CvGameCore_Expansion2.dll!CvHomelandAI::Update(bool bUpdateImprovements) Line 207	C++
 	CvGameCore_Expansion2.dll!CvPlayerAI::AI_unitUpdate(bool bUpdateHomelandAI) Line 289	C++
 	CvGameCore_Expansion2.dll!CvGame::updateMoves() Line 9126	C++
 	CvGameCore_Expansion2.dll!CvGame::update() Line 1568	C++
 	CvGameCore_Expansion2.dll!CvDllGame::Update() Line 498	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for CivilizationV.exe]	
```
```
	CvDiplomacyAI::GetNoDiggingPromiseState	0x78c590f0 {CvGameCore_Expansion2.dll!CvDiplomacyAI::GetNoDiggingPromiseState(PlayerTypes)}	PromiseStates(const CvDiplomacyAI::*)(PlayerTypes)
	ePlayer	24	PlayerTypes
+	m_aeNoDiggingPromiseState	0x2bba03b4 "ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ...	char[22]
	CvDiplomacyAI::MadeNoDiggingPromise	0x78c591d0 {CvGameCore_Expansion2.dll!CvDiplomacyAI::MadeNoDiggingPromise(PlayerTypes)}	bool(const CvDiplomacyAI::*)(PlayerTypes)
	PROMISE_STATE_MADE	PROMISE_STATE_MADE (0)	PromiseStates
	GetID	0x78d24c20 {CvGameCore_Expansion2.dll!CvDiplomacyAI::GetID(void)}	PlayerTypes(const CvDiplomacyAI::*)()
	m_eID	4 '\x4'	unsigned char
	m_eTeam	4 '\x4'	unsigned char
```

**Closed** 2024-12-15 14:16 UTC
