### ISSUE TITLE
RNG Desycs

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1584] opened 2016-04-13 15:04 UTC
@ilteroi ,

Further testing, and confirmation from forum-users, has convinced me that the root of the desyncs in MP is the random number generator going out of sync between host and client. Log statements regarding RNG desyncs and in-game desyncs match perfectly and – since barb behavior is heavily reliant on the RNG – it seems we have our culprit. I haven't studied the CvRandom.cpp much, but what changes have been made to it, specifically with regards to interaction with CvGame.cpp?

**Comment by ilteroi** [comment] 2016-04-13 18:28
the question is whether the desync is the cause or the effect. i believe in fact that it's merely an effect: if in a given turn one instance of the game calls it N times and the other instance calls it N+1 times, it will be out of sync. but it's not the fault of the RNG.

anyway, i just checked the logs and the depressing thing is that they can't even format their error messages right.

back on topic, there are in fact three RNG instances
- one for UI purposes: getASyncRand()
- one is for map generation getMapRand()
- one for all AI tasks: getJonRand()

now firstly it is extremely important not to call the AI RNG from the UI.
secondly, the AI may not use any other sources of randomness than the AI RNG. this also includes uninitialized variables.

**Comment by TechpriestEnginseer** [comment] 2016-04-13 18:48
Game.Random instead of math.random for LUA?

**Comment by LoneGazebo** [comment] 2016-04-13 19:02
Good point, @ilteroi, I hadn't considered that.

**Comment by LoneGazebo** [comment] 2016-04-13 19:03
In ay case, I think this needs further investigation.

**Comment by ilteroi** [comment] 2016-04-14 18:42
in my latest commit i also fixed up the desync log message to show the actual seed value.

in CvRandom there is an option (compile-time right now) to switch on verbose logging for RNG calls, including callstack. wouldn't recommend it for a long game but since the desyncs appear to be frequent it shouldn't be a problem.

just get two people to play like that and compare their RNG logs to see if there are different calls.

**Comment by LoneGazebo** [comment] 2016-04-14 18:47
Are the debug logs on by default? I'll let Lynnes know, see if he can scratch up a modpack for debugging.

Maybe at some point you and I should sync up our schedules and do a debug session via MP? Might be the easiest way to fix this. Also, did you see my post re: barbarian passivity? Seems barbs aren't getting duly processed by the homeland/tactical AI, and I wonder if that's partially to blame for barb desyncs as of late.

**Comment by LoneGazebo** [comment] 2016-04-14 18:48
@LynnesCFC, would you mind making a debug modpack of the CP for testing based on ilteroi's debug work he uploaded?

**Comment by LoneGazebo** [comment] 2016-04-14 19:15
Also, @ilteroi , where did you see embarked unit defense? I'd like to make whatever static integers you used a define, so we can balance things a bit more readily.

**Comment by ilteroi** [comment] 2016-04-14 20:14
currently the extended logging is commented out. check for "gStackWalker" in CvRandom.cpp

don't know what you mean exactly by "seeing" embarked unit defense, but if you want to tweak it, look at GetEmbarkedUnitDefense().

**Comment by LoneGazebo** [comment] 2016-04-14 20:18
Sorry, not see, I meant change. Gah, my brain is skipping off today!

**Comment by ilteroi** [comment] 2016-04-16 09:23
there is a lot of randomness in cvbarbarians. i think we can just as well fake it by generating numbers based on plot coordinates, game turn, number of existing units etc. maybe that will help

**Comment by LoneGazebo** [comment] 2016-04-16 16:19
Makes sense. I'll give it a whirl if you want.

**Comment by ilteroi** [comment] 2016-04-16 16:22
nah. already done :)

**Comment by LoneGazebo** [comment] 2016-04-16 16:23
Whoop!

**Comment by ilteroi** [comment] 2016-04-16 16:23
hit a snag with crashes though, apparently when you remove players in the pre-game setup, something breaks

**Comment by LoneGazebo** [comment] 2016-04-16 16:26
Delete them from the UI? That seems bad.

**Comment by LoneGazebo** [comment] 2016-04-16 16:27
What does the UI do when you add/remove players from the UI?

**Comment by ilteroi** [comment] 2016-04-16 16:35
nothing. but then when i start autoplay, something on lua side still tries to access the player, which fails because it's not initialized.

**Comment by LoneGazebo** [comment] 2016-04-16 16:50
Huh. That's real odd. If you change map size from standard to huge and back to standard does it break? If you are attached to the DLL, does it break?

**Comment by ilteroi** [comment] 2016-04-16 17:56
maybe i fixed it for good on dll side. pushed.

barb camp spawning was very RNG intensive, it's now rewritten to use ideally one call per camp only. in other instance we don't need to RNG at all but fake a direction based on game turn etc (for small numbers that's enough entropy)

**Comment by LoneGazebo** [comment] 2016-04-16 18:28
awesome

**Comment by LoneGazebo** [comment] 2016-04-17 15:31
Another report inbound, seems a bit more evidence in favor of an RNG desync: http://forums.civfanatics.com/showpost.php?p=14238253&postcount=765

**Comment by ilteroi** [comment] 2016-04-17 21:28
let's see how the new version works out.

also, i just found a bug in the two-layer pathfinding. pushed a fix and and a change which limits it to the first turn of the path. should result in a major speed improvement.

**Comment by LoneGazebo** [comment] 2016-04-17 23:13
Coolio. Whoward asked me to tell you that at some point, he was wondering if might be possible for us to port the pathfinder changes to a 'fresh' DLL, with proper preprocessor markup, as he really wants to incorporate it into the VMC. No worries if it is too big of a hassle, but your pathfinder is so much better than the stock one it is a shame that we can't readily share it with non CP folk.

**Comment by ilteroi** [comment] 2016-04-18 07:23
short answer: difficult.

long answer: as far as i see it, he still goes for the surgical approach and tags every change - the pathfinder is called in a lot of places! since i changed the interface, you would have to change all of them. the best bet would probably be to take the new CvAStar.h/cpp and write a wrapper around it so that the rest of the code can stay the same. so all the getPathfinder calls would map to the same instance but with different parameters.

**Comment by LoneGazebo** [comment] 2016-04-18 15:21
Figured as much, and that's not a problem. I'll let him know.

**Closed** 2016-04-18 17:56 UTC
Labels: Fixed for upcoming version, Paging Dr. Ilteroi
