### ISSUE TITLE
Does Evangelism work?

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4157] opened 2018-04-08 13:50 UTC
_1. Mod version (i.e Date - 4/23):_ latest hotfix

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I can't seem to confirm that Evangelism (Holy City gains science when my missionaries spread my religion to cities of other religions) works.  I convert citizens, I convert the city, but I get no notification about science gain. Neither does Technology window confirm the gain (the technology being researched didn't get additional science).
Is it a bug or do I get some aspects of VP's mechanic wrong?

**Comment by saamohod** [comment] 2018-04-08 14:15
[EVANGELISM.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1887529/EVANGELISM.zip)

Here is the savegame in case you wanna test. There is a missionary docked at a city of another religion.

**Comment by raphaell666** [comment] 2018-04-09 13:03
Just a heads-up, this reformation belief is called "Missionary Zeal (Scholar-Priests)" by the mod files.

The only line regarding this that I found in the mod files was:

`UPDATE Beliefs
SET SciencePerOtherReligionFollower = '10'
WHERE Type = 'BELIEF_MISSIONARY_ZEAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );`

The mod doesn't seem to have changed the behaviour of `SciencePerOtherReligionFollower`, I believe (unless it was done on the DLL?). So it should work exactly like the "Interfaith Dialogue" vanilla founder belief:
> The "Interfaith Dialogue" belief works every time the action "Spread Religion" is performed, and regardless of whether you manage to convert the city with this particular action. In fact, because the effect only works if the target city has a majority religion other than yours, the moment the city converts to your religion, or even becomes neutral, Interfaith dialogue stops. The amount of Science gained increases with the eras.
http://civilization.wikia.com/wiki/Religion_(Civ5)

Hope this helps.

**Comment by saamohod** [comment] 2018-04-09 13:50
>Just a heads-up, this reformation belief is called...

IIRC this is an enhancer belief, not a reformation belief. Those two are different things I believe.

**Comment by UndeadDevel** [comment] 2018-04-09 16:06
Looks like this is a duplicate of issue #3915

**Comment by saamohod** [comment] 2018-04-09 17:50
>Do you remember if in your test if you successfully converted the city or not?

Yep, I managed to convert both citizens and entire cities. Both my cities as well as foreign ones. Nothing gave me the science bonus.

**Comment by raphaell666** [comment] 2018-04-09 19:13
> Yep, I managed to convert both citizens and entire cities. Both my cities and foreign ones. Nothing gave me the science bonus.

What I was trying to say is that you do not necessarily have to convert the city in order to gain the bonus. Anyways, I took a look at your save and I also couldn't find any hint that using the missionary to convert citizens in that city gave any science bonus, neither per turn nor in the total, nor anywhere else that I checked (you are also using this mod in addition to VP: https://forums.civfanatics.com/resources/24836/).

In addition, I noticed that the VP DLL code seems to change the behavior of `GetSciencePerOtherReligionFollower`:

```
/// Science per other religion follower
int CvReligionBeliefs:: GetSciencePerOtherReligionFollower(PlayerTypes ePlayer, CvCity* pCity, bool bHolyCityOnly) const
{
	CvBeliefXMLEntries* pBeliefs = GC.GetGameBeliefs();
	int rtnValue = 0;

	for(BeliefList::const_iterator it = m_ReligionBeliefs.begin(); it != m_ReligionBeliefs.end(); ++it)
	{
		int iValue = pBeliefs->GetEntry(*it)->GetSciencePerOtherReligionFollower();
		if (iValue != 0 && IsBeliefValid((BeliefTypes)*it, GetReligion(), ePlayer, pCity, bHolyCityOnly))
		{
			rtnValue += iValue;
		}
	}

	return rtnValue;
}
```

I am trying to figure out what is going on with this function. Help would be appreciated.

**Comment by raphaell666** [comment] 2018-04-09 21:57
I found some more relevant portions of the code in CvUnit.cpp (if this is not helpful, please let me know and I'll stop, I'm trying to learn while helping).

This is where it calls for and calculates the bonus:
```
#if defined(MOD_API_UNIFIED_YIELDS)
	iPreSpreadFollowers = pCity->GetCityReligions()->GetNumFollowers(eReligion);
#else
	iScienceBonus = pReligion->m_Beliefs.GetSciencePerOtherReligionFollower();
	if(iScienceBonus > 0)
	{
		// Requires majority for this city to be another religion
		ReligionTypes eCurrentReligion = pCity->GetCityReligions()->GetReligiousMajority();
		if (eCurrentReligion != NO_RELIGION && eCurrentReligion != eReligion)
		{
			iScienceBonus *= pCity->GetCityReligions()->GetFollowersOtherReligions(eReligion);
		}
		else
		{
			iScienceBonus = 0;
		}
	}
#endif
```
It multiplies the belief science bonus with the number of followers of other religions (not what I expected based on the description, I thought it was a fixed value independent of the number of followers). Otherwise, seems fine to me.

And this is where it applies the bonus:
```
#if !defined(MOD_API_UNIFIED_YIELDS)
	if (iScienceBonus > 0)
	{
		CvPlayer &kPlayer = GET_PLAYER(m_eOwner);

		TechTypes eCurrentTech = kPlayer.GetPlayerTechs()->GetCurrentResearch();
		if(eCurrentTech == NO_TECH)
		{
			kPlayer.changeOverflowResearch(iScienceBonus);
		}
		else
		{
			CvTeam &kTeam = GET_TEAM(kPlayer.getTeam());
			kTeam.GetTeamTechs()->ChangeResearchProgress(eCurrentTech, iScienceBonus, kPlayer.GetID());
		}

		if (pCity->plot() && pCity->plot()->GetActiveFogOfWarMode() == FOGOFWARMODE_OFF)
		{
			char text[256] = {0};
			sprintf_s(text, "[COLOR_BLUE]+%d[ENDCOLOR][ICON_RESEARCH]", iScienceBonus);
			float fDelay = GC.getPOST_COMBAT_TEXT_DELAY() * 2;
#if defined(SHOW_PLOT_POPUP)
			SHOW_PLOT_POPUP(pCity->plot(), getOwner(), text, fDelay);
#else
			DLLUI->AddPopupText(pCity->getX(), pCity->getY(), text, fDelay);
#endif
		}
	}
#endif
```
It apparently adds the science bonus directly to the research in progress, if there is not a research in progress it adds to the science overflow, which will be applied once you select a research? Seems fine too. In addition, if it is working correctly, it should be easy for us to know because there should be a blue text popup with the "+ Science" in the city tile.

One doubt I still have is with the `GetSciencePerOtherReligionFollower` function (I copied it in my previous reply) calling itself when defining iValue. I do not understand what will happen when it calls itself. I am still learning pointers and addresses, so I am not sure if I understood it correctly.

**Comment by Iamblichos** [comment] 2018-04-10 00:57
Code is correct:

/// Accessor:: amount of science for each follower of another religion in city spread to
int CvBeliefEntry::GetSciencePerOtherReligionFollower() const
{
	return m_iSciencePerOtherReligionFollower;
}

`	m_iSciencePerOtherReligionFollower= kResults.GetInt("SciencePerOtherReligionFollower");`

Follow m_iSciencePerOtherReligionFollower that's the variable that will store the belief in BeliefClassess. That gets read in the ReligionClasses function when iterates over m_ReligionBeliefs. Just note you have two different functions named GetSciencePerOtherReligionFollower one in BeliefClasses that reads the database and another that's a part of ReligionBeliefs that's a part of the game beliefs.

**Comment by LoneGazebo** [comment] 2018-04-10 00:57
The code itself is fine, but the order is wrong - I see an issue with it. If, for example, your missionary or prophet wipes out another religion, it'll show up as being 0 followers (as currently the instant yield fires after the religion change is fired). I'm going to move that around. And yes, the description of the belief is a little obscure - I'll update it to note that it is the _other_ religion that matters.

G

**Comment by Iamblichos** [comment] 2018-04-10 01:02
So this is the part, as is, won't work?

```
if (eCurrentReligion != NO_RELIGION && eCurrentReligion != eReligion)
		{
			iScienceBonus *= pCity->GetCityReligions()->GetFollowersOtherReligions(eReligion);
		}
```

**Comment by LoneGazebo** [comment] 2018-04-10 01:08
that, and this in cvUnit

```
if(IsGreatPerson())
			{
				pCity->GetCityReligions()->AddProphetSpread(eReligion, iConversionStrength, getOwner());
			}
			else
			{
				pCity->GetCityReligions()->AddReligiousPressure(FOLLOWER_CHANGE_MISSIONARY, eReligion, iConversionStrength, getOwner());
			}
```

that needs to go AFTER the instant yield.

**Closed** 2018-04-28 16:29 UTC
