### ISSUE TITLE
OneShot?

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#11104] opened 2024-07-10 09:43 UTC
_1. Mod Version (X.Y.Z). Current Version: 4.12.1_

VP 4.12

_4. Describe the Issue_
When you choose a policy from Tradition, you get Palace (Treasure, Thron Room etc) in all cities, not just in the capital.

**Comment by azum4roll** [comment] 2024-07-11 01:49
Duplicate of #11108

**Closed by azum4roll** 2024-07-11 01:49 UTC
