### ISSUE TITLE
Horseman boat travelling ashore

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#953] opened 2015-12-19 02:48 UTC
A horseman debarked ashore but kept its boat animation.
Mods used: 
-all six items of CPP
-useful oil mod
-submarines ignore borders
-lake Victoria fix
-Krakatoa fix
-Gibraltar and reef optimizations
-faster plot expansion
-extra victory conditions
-improved air recom
-great prophet historical names

![civ5screen0034](https://cloud.githubusercontent.com/assets/16341598/11910827/db023812-a609-11e5-85fc-231e09ecb6d4.jpg)

Here is the savegame [boat.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/67345/boat.zip)

**Comment by Iamblichos** [comment] 2015-12-19 06:02
I've noticed a couple of things too:

a) If I'm using whoward's Promotions - Terrain Crossing mod with the intent of using Helicopters' as 'deep embarkation' i.e. they don't embark until they hit Ocean tiles, the Helicopter won't embark at all onto Ocean. It's limited to Land and Coast only.

b) Units that don't get the 'PROMOTION_EMBARKATION' promotion because they haven't entered my borders to get it yet (upon researching tech that grants it), are able to walk freely over Coastal tile. Is anybody else seeing this?

**Comment by Kolaris8472** [comment] 2015-12-19 06:08
I had Conscription spawn a Spearman on the coast but it kept its land animations as it sailed around.

**Comment by ilteroi** [comment] 2015-12-19 10:48
ok ...

- the deep water embarkation didn't make the cut when i rewrote the pathfinder. figured nobody would miss it.
- not sure if we're talking about the same thing, but in my testing i did have to "go home" before embarkation works.
- i guess i'll disable spawning land units on water

**Comment by Iamblichos** [comment] 2015-12-19 13:48
Yes you should have to go home before embarkation works. Units that were home or got home would embark upon tech discovery. land Units that didn't go home or weren't home, would walk on water instead as if the tile were land. Same with lake tiles.

In regard to Deep embarkation, any hope you can keep that functional?

**Comment by Iamblichos** [comment] 2015-12-19 15:13
Let me turn off Deep embarkation and see if the non helicopter land unit is still walking on water. Got a hunch it might be that. I'll report back.

**Comment by ilteroi** [comment] 2015-12-19 15:22
embarkation logic is complicated enough as is. so i would rather omit a second kind of embarkation. 

we could allow helis to traverse ocean, but they are pretty powerful already, so that's probably uncalled for.

i just reproduced the unembarked land unit on water though. need to dig in further

**Comment by Iamblichos** [comment] 2015-12-19 15:58
I would leave helicopters as is in regards to traverse ocean. Modders can create their own promotion by dint of DLL and vanilla DLL to traverse all terrain if they so desire.

**Comment by LoneGazebo** [comment] 2015-12-19 16:44
Ilteroi, feel free to release a  beta that doesn't include my changes (I made very few after your last commit, so it won't affect much). You can just toss the DLL in the current CP and upload it if you need people to help test embark stuff.

**Comment by Iamblichos** [comment] 2015-12-19 18:25
Been experimenting a little bit with Helicopters and ocean tiles. Removed all embarkation ability from Helicopter and added a Promotion with Column 'CanMoveAllTerrain' and they won't move over Ocean but they should though.

**Comment by Edaka** [comment] 2015-12-19 19:12
Don't know if it's any helpful, but I got Incan slingers to enter a coast tile without embarkation due to the 'Retreat before melee' promotion.
![embark](https://cloud.githubusercontent.com/assets/12978597/11914870/324f178a-a695-11e5-9f46-2617d7a8ca79.jpg)

**Comment by Iamblichos** [comment] 2015-12-19 20:14
I have a Barbarian Trireme right next to my spearman (which was on land) on beginning turn, and Trireme should've had ZOC on the spearman, but the spearman moved right past him.

**Comment by ilteroi** [comment] 2015-12-20 01:52
ok, i found the root cause of the embarkation fails. also fixed the slinger retreat and the missing traits. helis can currently cross ocean (no embarkation) because they don't have the no-ocean promotion. get an amphibious attack modifier over water though.

https://dl.dropboxusercontent.com/u/16988401/civ/CvGameCore_Expansion2.zip

i do hope these were the last bugs :)

**Comment by Edaka** [comment] 2015-12-20 02:25
Nice job! Should it be savegame compatible or is it better to start anew?

**Comment by saamohod** [comment] 2015-12-20 02:57
Good job!
Does it go to DLC/Expansion2 ?

**Comment by LoneGazebo** [comment] 2015-12-20 03:28
You'll need to put it in the CP mod folder and replace the DLL. 

Will probably be save game compatible, as most pathfinder changes don't affect the game's memory structure.

**Comment by LoneGazebo** [comment] 2015-12-20 03:29
Thanks, ilteroi! Might make a post with it in the current version thread for users.

**Comment by Kolaris8472** [comment] 2015-12-20 04:56
Downloaded new GameCore file, replaced old, cleared Cache, new game

0 yield Coastal Tiles are back =(

**Comment by Iamblichos** [comment] 2015-12-20 10:34
I noticed this new DLL that ilteroi just uploaded is crashing Civ when I try to reload a game after going back to main menu. Did it consistently.

**Comment by ilteroi** [comment] 2015-12-20 12:02
re: coastal yield. was a merge error. fixed.

re: crash - i have that too, but only in conjunction with EUI. it's strange. so it doesn't happen with G's builds with an otherwise identical setup? that's most confusing.

**Comment by Iamblichos** [comment] 2015-12-20 20:46
Lately I've been running a modified EUI with just the Core and Gamesetup folder. So I haven't had any crashing.

**Comment by Iamblichos** [comment] 2015-12-20 22:08
ilteroi, I noticed in this new DLL you uploaded that I'm not able to override a units embark status. I use a custom transport mod in which I do a check that a unit:IsCargo() == true and then I do a unit:SetEmbarked(false) and then convert that unit so it acts as a disembarked unit only while it is cargo on a ship. This allows ranged units to fire from ships like they do on land. I'm guessing when I convert the unit, the DLL checks if its on coast or ocean and re-embarks the unit again.

**Comment by ilteroi** [comment] 2015-12-20 22:14
yeah, that's a failsafe i put in after the last adventures. guess i can remove it again if it interferes

will be posting a new build soon - closing this issue

**Closed by ilteroi** 2015-12-20 22:14 UTC
Labels: Fixed, Paging Dr. Ilteroi

**Comment by Iamblichos** [comment] 2015-12-20 22:16
It would be cool if you removed the failsafe as I have a number of other mods that do a check like that when I convert the unit...namely JFD's Sophet which acts as an Admiral and Great General
