### ISSUE TITLE
Attila settles 3 tiles away from my city!

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#5665] opened 2019-09-27 19:56 UTC
_1. Mod version (i.e Date - 4/23):_
9-15-4
_2. Mod list (if using Vox Populi only, leave blank):_
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
Diplomacy Responses Extended (v1)
Calypso's Colored Religion Icons (Basic) (v 1)

_3. Error description:_ 
Attila lands on the coast and settles a city 3 tiles away from Pataliputra.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[ATTILA SETTLES 3 SQ AWAY NEXT T!.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3664349/ATTILA.SETTLES.3.SQ.AWAY.NEXT.T.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/65798212-58454700-e171-11e9-9e44-97d2e9c5853c.png)
![image](https://user-images.githubusercontent.com/20144751/65798262-8591f500-e171-11e9-93be-605b3610f9d9.png)

**Comment by LoneGazebo** [comment] 2019-10-02 14:04
What map are you on?

**Comment by Edaka** [comment] 2019-12-17 09:57
Can't reproduce, closing due to no answer from the OP. Report back if it happens again.

**Closed by Edaka** 2019-12-17 09:57 UTC
