### ISSUE TITLE
new trade agreements bring cancellation icons immediately

### ISSUE THREAD

**Issue by clif9710** [LoneGazebo/Community-Patch-DLL#8839] opened 2022-04-29 23:41 UTC
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.1.0, DX 10 & 11):_DX 10/11, CP only v104

_2. Mod list (if using Vox Populi only, leave blank):_CP v104 and InfoAddict

_3. Error description:_when a trade agreement is made, immediately following closing the trade window, cancellation icons for that trade appear. This happens whether the AI or the player initiates the trade.

_4. Steps to reproduce (optional):_any trade agreement

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment] 2022-04-30 07:33
Duplicate of #8838

**Closed by RecursiveVision** 2022-04-30 07:33 UTC
