### ISSUE TITLE
C4DF Dev Discussion 

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1364] opened 2016-03-03 18:07 UTC
Hi, 

What is your general philosophy in dealing with reported bugs where the user has a lot of mods installed. 

I've always adopted a hard no-mods in bug reports rule but that is probably not realistic. What would be your system for identifying and fixing them?

**Comment by LoneGazebo** [comment] 2016-03-03 18:30
If there's clearly a conflict, I ignore the bug report (that's harsh, but I can't debug everything). If I see it in both 'lots of mods' and 'no extra mods' scenarios, then I reconsider.

**Comment by Iamblichos** [comment] 2016-03-04 01:44
I think it's realistic too G. You could spend hours upon hours trying to debug someone else's mod.

**Comment by mwhiter** [comment] 2016-03-04 02:01
Totally fair.

Can this thread be a C4DF github discussion? I can rename the title.

**Comment by LoneGazebo** [comment] 2016-03-04 03:17
Sure. I should make you a contributor on the source so you can open/close edit threads.

**Comment by mwhiter** [comment] 2016-03-04 12:59
Thank you. This helps. I'm going to change my repo structure so that I develop on this repo on my custom branch. Will make my life simpler. 

Does anyone know if it's possible to add new Advisor Popups (new player help). On a cursory glance it seems to call into CvDllUtility as virtual functions and idk how to deal with that.

**Comment by mwhiter** [comment] 2016-03-05 00:26
Hi, what is TXT_KEY_HAPPINESS_FROM_VASSALS and where is it used?

**Comment by LoneGazebo** [comment] 2016-03-05 01:23
It's used in the Lua UI. Top Panel and Happiness Screen IIRC. I think it's located in the compatibility files.

**Comment by mwhiter** [comment] 2016-03-06 15:08
Thanks.

I haven't been touching EUI in my development, was it updated in the latest pull?

**Comment by mwhiter** [comment] 2016-03-06 15:30
I've been checking, doesn't seem like it was.

1) Can you post the C4DF - CBP solution file so I download and edit it with ModBuddy on my end?
2) Can you tell me if it's possible to run C4DF and CBP alone (no compatibility files) without any issues? Or do you need to use one of the EUI / Non-EUI files?

**Comment by LoneGazebo** [comment] 2016-03-06 16:27
I've got the EUI one updated, yep. Github isn't updated yet, though.

To run C4DF and CBP, you need the compatibility file. That's where all the lua from C4DF/CSD/CBP is combined.

Two issues:
1.) Two windows appear when you click the vassal button.
2.) There's a typo in the tooltip for capitulation in the second line. I forget the specific word, but I saw it yesterday and forgot to mention.

G

**Comment by LoneGazebo** [comment] 2016-03-09 03:19
Interesting issue: latest version, AI got a vassal. I was curious, so I took a look at the vassal overview for them. The vassals aren't showing up! Savegame with just the Community Patch Project files incoming.

Also, even though Siam capitulated to the Iroquois, it showed up as a 'voluntary' vassal in the notification.

**Comment by LoneGazebo** [comment] 2016-03-09 03:21
[Vassalnovassal.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/164381/Vassalnovassal.zip)

**Comment by LoneGazebo** [comment] 2016-03-09 03:22
Use the 3/8 version of the modpack (all of it, including EUI).

**Comment by mwhiter** [comment] 2016-03-09 11:50
Interesting, what were you expecting from the VO? (have not had a chance to investigate). What did show up? And I'll check it out at some point it would appear the logic for sending notifications maybe reversed.

**Comment by LoneGazebo** [comment] 2016-03-09 15:13
I was expecting to see the vassal itself, so I could fiddle with sliders.

**Comment by mwhiter** [comment] 2016-03-09 18:57
Was it your vassal or the AIs vassal? I'm a bit confused.

**Comment by LoneGazebo** [comment] 2016-03-09 18:58
I stepped into the AI (using firetuner) to look at their vassals. Was otherwise just an AI observation game.

G

**Comment by mwhiter** [comment] 2016-03-09 19:06
Oh, okay. Probably an active player issue!

**Comment by LoneGazebo** [comment] 2016-03-09 19:17
Might be, though I was, technically, the 'active player' when I stepped into the AI's shoes.

**Comment by mwhiter** [comment] 2016-03-09 23:15
so my code is looking at Game.GetActivePlayer(). Were you able to run this command and see what was coming up?

**Comment by LoneGazebo** [comment] 2016-03-09 23:21
I didn't, no. It may've be an aberration, but I haven't run another game in order to test. I figured I'd let you see if you can reproduce something similar using the firetuner.

**Comment by mwhiter** [comment] 2016-03-09 23:23
Since other files use Game.GetActivePlayer(), you might see similar issues with those. Otherwise, I'm not sure (at this moment, since I am not actively debugging that issue, it is rather low-priority).

**Comment by mwhiter** [comment] 2016-03-09 23:31
"Also, even though Siam capitulated to the Iroquois, it showed up as a 'voluntary' vassal in the notification."

What was the text of the notification? I'm looking at the notifications for any vassal event, and the only one that cares if it's capitulated or voluntary is the event where you (the player) has a new vassal, then the message changes for capitulation or voluntary.

**Comment by LoneGazebo** [comment] 2016-03-09 23:39
If users don't report the vassal screen being empty, then let's assume it was a problem with the debug environment.

For the capitulation issue, it was a result of war. When I stepped in to the Iroquois, Siam offered peace with capitulation on their side. I accepted, and – even though it was capitulation – the notification text said that Siam 'recognized our strength' and accepted our offer of vassalage.

**Comment by mwhiter** [comment] 2016-03-09 23:43
Cursory look at the code - doesn't seem anything suspect or glaring. Which is the nastiest kind.

**Comment by LoneGazebo** [comment] 2016-03-09 23:53
Yeah. What's the specific text string for capitulation through war?

**Comment by mwhiter** [comment] 2016-03-09 23:54
"Facing near certain defeat, {1_TeamName} has surrendered as a vassal to our great civilization."

I was trying to debug and the game just crashed randomly at CvRandom::get(). Access violation of some sorts (but not a NULL pointer). It was called by CvBarbarians::DoCamps()

**Comment by LoneGazebo** [comment] 2016-03-09 23:57
Yeah, that text is not what came up, it definitely said 'recognizing our great military strength,.'

DoCamps() ? Are you on the latest 3/9 CP? What turn did it crash?

**Comment by LoneGazebo** [comment] 2016-03-09 23:58
I wonder if that's the crash some users are seeing...I haven't been able to reproduce.

**Comment by mwhiter** [comment] 2016-03-10 00:00
I'm on the latest. I just tested capitulation through war. I cannot reproduce your issue. And it crashed at turn 8 (but, I'm doing a lot of debugging and cheating, so not irrelevant).

also, it was a random crash. Did not occur after a reload.

**Comment by mwhiter** [comment] 2016-03-10 00:02
If you want to test out any capitulation, feel free to call the following function:

Teams[int vassal ID]:DoBecomeVassal(int masterID, bool bVoluntary) in LUA to see if you can reproduce the issue on your machine.

**Comment by LoneGazebo** [comment] 2016-03-10 00:03
May have simply been a quirk related to that debug session, Let's ignore the issue unless another user brings it up.

The only other 'bug' I notice is that clicking the vassal button still results in two windows popping up. I think it's because there are two calls for the vassalage window to popup - one in the diplo corner lua, and one in the vassalage overview lua.

I'll test out vassalage some more.

**Comment by mwhiter** [comment] 2016-03-10 00:06
Yeah, I'm not getting that issue but I haven't tried out EUI yet so it may be related to that.

Once I'm comfortable with my latest C4DF changes I wanna start rolling it out to other setups.

**Comment by LoneGazebo** [comment] 2016-03-10 00:07
Sounds good. Like I said, the EUI code in the Compatibility file should work without issue for you. 
Also, meant to ask – do you want me to bundle the 1a C4DF into the .exe installer as an option?

**Comment by mwhiter** [comment] 2016-03-10 00:08
Absolutely! 1a - C4DF Non-EUI, and at some point in the near future 1b - C4DF EUI will become options for download.

**Comment by LoneGazebo** [comment] 2016-03-10 00:08
Sounds good. That'll save you the trouble of having to write install instructions.

**Comment by mwhiter** [comment] 2016-03-10 00:09
I'll also be adding my standalone C4DF code to my github (all my code sectioned off with MOD_DIPLOMACY_CIV4_FEATURES) so in the future, I'll probably update that version, do my bug testing there, and then roll out to Community Patch. from there.

**Comment by LoneGazebo** [comment] 2016-03-10 00:11
De-bundling from the CP? That's like trying to leave the borg. :)

**Comment by mwhiter** [comment] 2016-03-10 00:12
That's my plan for this weekend, get my standalone version working so that it's more sensible to roll out to other mods (they'll have to do the merge themselves) if they want to adopt my changes.

**Comment by mwhiter** [comment] 2016-03-10 00:12
Community Patch gets my newest version first for keeping it on life support for 3 years. :D

**Comment by LoneGazebo** [comment] 2016-03-10 00:13
Sounds good. I put a lot of time into working out the bugs/quirks with it, so I'm happy to see that its master has returned.

**Comment by mwhiter** [comment] 2016-03-10 00:19
I asked this question before, but do we have any way of getting into ICvDllUtility.h?

I really, REALLY want to dissect the following:

```
	virtual void SetAdvisorBadAttackInterrupt (bool bValue) = 0;
	virtual bool GetAdvisorBadAttackInterrupt (void) = 0;
	virtual void SetAdvisorCityAttackInterrupt (bool bValue) = 0;
	virtual bool GetAdvisorCityAttackInterrupt (void) = 0;
```

so I can add "foreign advisor tells you about vassalage".

Or does anyone know a better way to do this :)

**Comment by LoneGazebo** [comment] 2016-03-10 00:21
I don't think so, no – I originally had a robust advisor system for the CBP, but scrapped it all when I realized that much of the UI stuff is hard-coded.

You could do a luapopup, though (like technologies) that appears at medieval.

**Comment by mwhiter** [comment] 2016-03-10 00:23
The problem with that, however, is that you can't say "never show me this again", since the game probably won't remember that.

That is disappointing, to say the least.

**Comment by LoneGazebo** [comment] 2016-03-10 00:25
Eh, it isn't great, but watching LPs of people running the CBP shows me that no amount of notifications, popups, civilopedia, or any other text help is really going to teach players how to use a mod. You could spend hours working on an advisor message like that, but the first time it appears, the player will disable it, and disable all advsior popups. :)

**Comment by mwhiter** [comment] 2016-03-10 15:08
Re: capitulation / voluntary... Another user reported that issue. So something is not synced between my version and yours. Perhaps a merge issue?

**Comment by mwhiter** [comment] 2016-03-10 15:49
G, I'm really thinking the bug with the capitulation showing up as voluntary vassalage is linked to an issue with EUI. It's a common thread amongst anyone experiencing this issue. I'm thinking EUI and C4DF are extremely unstable at the moment.

**Comment by LoneGazebo** [comment] 2016-03-10 15:50
EUI doesn't affect the notification system in the DLL, though. Notifications and whatnot are all DLL-generated. Plus, the vassalage overview in EUI is identical to the one used in 1a.

**Comment by mwhiter** [comment] 2016-03-10 17:06
Actually my suspicion is more like EUI is sending true for voluntary when it should be sending false for capitulation. A deal issue rather than a DoBecomeVassal issue. If you type Teams[1]:DoBecomeVassal(0, false) and it shows voluntary then I'm wrong, but if it shows capitulation then my suspicion is probably close

**Comment by LoneGazebo** [comment] 2016-03-10 17:13
The tradelogic code in EUI is copy-pasted from the tradelogic code in no-EUI. There could be a bug, but that bug would show up in both.

I'm not trying to be difficult here, but I really don't think it is EUI that's causing the issue (which is a rare thing for me to admit, as I generally loathe EUI!).

**Comment by LoneGazebo** [comment] 2016-03-10 17:50
Cool. If you feel so inclined, the LUA folder in the EUI-Compatibility folder has all your C4DF changes in it. TradeLogic, TopPanel etc. search for putmalk or c4df to find your changes.

G

**Comment by mwhiter** [comment] 2016-03-11 02:56
Okay so I loaded in a game of EUI and I see what you're saying about the VO (appearing twice). Since this doesn't happen on C4DF CP there has to be some difference between them, I'll investigate in more detail tomorrow.

**Comment by LoneGazebo** [comment] 2016-03-11 03:15
Sounds good.

**Comment by mwhiter** [comment] 2016-03-12 02:21
So the hell? I moved my VO from EUI folder to C4DF CBP and it stopped the VO twice issue.

**Comment by mwhiter** [comment] 2016-03-12 02:21
I also saw it added twice in InGameUIAddin - that may have caused the issue.

**Comment by mwhiter** [comment] 2016-03-12 02:32
and the Capitulation issue is because the peace treaty (in EUI at least, haven't tested for Non-EUI CBP) is NO_PEACE_TREATY_TYPE when being sent to DealClasses. So to fix the vassal issue...I'm gonna make this check look for if the teams are at war :)

**Comment by mwhiter** [comment] 2016-03-12 02:32
^^ the peace treaty bug may be a more nefarious issue to look into

**Comment by LoneGazebo** [comment] 2016-03-12 03:17
Weird re: trade issue. Not sure on that.

**Comment by mwhiter** [comment] 2016-03-12 03:28
I knew it was a deal issue but wasn't sure of the cause. For some reason, GetPeaceTreatyType is returning -1 for trade deals. At least in the EUI version. Not sure on the Non-EUI version, did not test it, my solution is universal (call to kDeal.IsPeaceTreatyDeal() )

**Comment by LoneGazebo** [comment] 2016-03-12 03:29
Makes sense. See my request for the new modinfo file for C4DF - should be all I need to get the new version out the door.

**Comment by mwhiter** [comment] 2016-03-12 03:34
See my comment on the commit. Stick with the old way for now, when I get my standalone version up we'll have a universal and maintained version on github to use.

**Comment by LoneGazebo** [comment] 2016-03-12 03:39
Grand. Oh, the joys of merging. :)

**Comment by mwhiter** [comment] 2016-03-12 16:43
Does anyone know if anyone has hosted the official, unmodified Civ 5 source code on git anyway? In CvDealAI.cpp there's a code block:

```
	// Important: check invalid return value!
	if (iTotalValueToMe==INT_MAX)
		return false;
```

That I don't have in the Civ 5 source code I'm using for C4DF standalone, and I wasn't sure if my original source was out of date or if this may possibly be a CPP change that isn't surroudned by #define blocks.

**Comment by LoneGazebo** [comment] 2016-03-12 16:45
You can get the unmodified civ source code in the SDK folder.

**Comment by LoneGazebo** [comment] 2016-03-12 16:47
That _looks_ like an ilteroi change, though. I'd recognize that connected == anywhere. :)
Anyways, that is an absolutely essential value - without it, the AI will accept most any deal. If you're passing INT_MAX values to that point, the deal valuation function is messed up, not that.

**Comment by mwhiter** [comment] 2016-03-12 16:49
I know where to get the unmodified version, I'm asking because I wanted to make sure I had the most up-to-date SDK source code.

Okay, but if it's not surrounded by #define blocks, how am I supposed to know if I'm missing any other "essential" changes? Seems like it would be the perfect candidate for a define block (MOD_ESSENTIAL_BUG_FIXES) or something - I'm trying to create my standalone C4DF stuff and make it as bug-free as possible.

**Comment by LoneGazebo** [comment] 2016-03-12 17:07
Some aspects of the DLL that are mandatory bugfixes were passed down/on by users beyond just ilteroi and I. Not all users used the preprocessor model, and we've done our best to keep with it and/or fix them where possible Some areas, like beliefclasses or the tactical AI/operational AI, were so wholly overhauled that it just didn't make sense to preprocessor anything (as the entire file was essentially changed).

As far as 'how you are supposed to know,' well...that's the trouble with having a bunch of different users modifying the same DLL for three years.

**Comment by mwhiter** [comment] 2016-03-12 17:10
Okay I see. I'm curious to see what the mandatory bugfixes are, but it's okay. My C4DF standalone will keep the existing Civ V bugs and the CPP C4DF will be the "bug-free" edition of the mod.

**Comment by LoneGazebo** [comment] 2016-03-12 17:12
The CP, with its base settings in the CP mod, is nigh identical to the base game except for war score (which, keep in mind, is tied to capitulation currently) and bugfixes. To be completely honest, not sure why you don't just want to use that as your base. Extracting C4DF from the CP will leave you with the entirety of the old AI (on every level), which may or may not cause problems with how C4DF is currently tuned.

**Comment by mwhiter** [comment] 2016-03-12 17:22
I want to release my new version of my standalone mod. Some players may want to only play with my mod and not the Community Patch, which is their choice and I want to provide that option.

C4DF standalone and C4DF CP will be aligned very closely, with minor differences (the capitulation logic, for example). But I think it's good to provide an option not bundled with any other mods.

**Comment by LoneGazebo** [comment] 2016-03-12 17:26
Totally fine, I just wanted to point out that there may be unforeseen consequences of separating C4DF as it is right now from the CP's AI.

**Comment by mwhiter** [comment] 2016-03-12 17:28
If it's any consolation, I plan on playing the CP version of C4DF, but I will admit is harder to develop for when the Community Patch and C4DF mod structures are separated.

**Comment by LoneGazebo** [comment] 2016-03-12 17:33
The 1a mod seems to do a good job - just load that up with the CP and you're good to go. If there's anything I can do to help with ease of operation, let me know.

**Comment by mwhiter** [comment] 2016-03-12 23:38
G, check out my standalone github page for the newest version of C4DF's. My solution is hosted there.

**Comment by mwhiter** [comment] 2016-03-14 15:52
When can I expect my latest (minor) pull request to be merged into the mod?

**Comment by LoneGazebo** [comment] 2016-03-14 15:54
It's all merged up already – I do merges by hand (as I've got so many sources to juggle).

**Comment by mwhiter** [comment] 2016-03-14 16:37
Okay awesome! Thank you!

**Comment by mwhiter** [comment] 2016-03-18 02:03
So I am pushing a new translation to C4DF. I can handle the Community Patch - C4DF Addon but the CBP C4DF will need to be updated by you. My .modinfo is now hosted on my github page, so you can easily find it.

**Comment by LoneGazebo** [comment] 2016-03-18 18:48
Did you push it to your branch here, or just your branch?

**Comment by mwhiter** [comment] 2016-03-18 20:15
Think I forgot to pull request.

**Comment by mwhiter** [comment] 2016-03-18 23:32
not trivial to merge, so I'll do it tomorrow.

**Comment by mwhiter** [comment] 2016-03-19 14:24
I'm a bit confused, was (1a) removed from the repository? I can't find it.

How is C4DF being organized for CPP now?

**Comment by LoneGazebo** [comment] 2016-03-19 16:24
I didn't remove the 1a, no. I think a bad merge must've happened. I'll re-upload.

The C4DF is still in the (4) C4DF folder (everything but its LUA, which is still in the compatibility files).

**Comment by mwhiter** [comment] 2016-03-20 15:05
Okay I'm gonna go ahead and do two things:

1) Re-create and push the (1a) folder (let me do that)
2) Create a new mod for C4DF - CBP.

I think it'd be smart have C4DF - CBP include it's own Lua. It should get overwritten by the CBP Compatibility.

**Comment by LoneGazebo** [comment] 2016-03-20 16:08
I put the lua in the compatibility mod because it's easier for me to manage merge stuff. It doesn't overwrite properly, which is why I keep all lua in the 'last' file to load.

**Comment by mwhiter** [comment] 2016-03-20 16:22
Okay, that's fine.

I will be adding everything in the mod to source control. I think the compatibility mod should be setting the C4DF, CSD, and More Luxuries mods as "references" rather than "dependencies" so that people can only play with C4DF and not CSD if they choose to.

**Comment by LoneGazebo** [comment] 2016-03-21 04:24
I've gone down that road, though, and the problem boils down to lua. Lua doesn't follow the load order preference system - it loads based on the last file to be dropped into the folder (last modified entry, really). It's a pain in the ass, which is why I nuke all lua except for the compatibility lua in the full CPP.

**Comment by mwhiter** [comment] 2016-03-21 14:19
I agree with you. But does the compatibility file break if C4DF or CSD are not loaded into the mod? I'm thinking the Lua files should be compatible if the DLL files in Lua are defined.

**Comment by LoneGazebo** [comment] 2016-03-21 14:56
It doesn't break, but there are some hard edits (city state stuff), text changes, and a few other edits that would not make sense without the full set of mods. Modularity is difficult to manage with LUA due to the aforementioned override problem.

**Comment by mwhiter** [comment] 2016-03-26 17:42
I am noticing a lot of issues with regression testing and things that I thought were fixed but keep propping up. Stuff like: TXT_KEY_TP_HAPPINESS_VASSALS keeps appearing in Community Patch solution which breaks (1a) and CBP C4DF when they write to the same row tag. This results in all my texts breaking. I feel like there are also other issues that appear, but I'll try to point them out when I see them. I'm not sure why that keeps happening, but it's pretty annoying.

**Comment by LoneGazebo** [comment] 2016-03-26 19:23
Hmm...I had a hard time getting the latest master merge to work. Try this: push to your C4DF branch then make a push request to master. I'll manage the push request and keep the master file in-sync.

G

**Comment by mwhiter** [comment] 2016-04-07 13:57
Okay, so I wanted to give some heads up on what I'm doing next:

1) The last pull request from C4DF had some issues due to how out of sync master and my dev branches are. So, I will see what is different between master and C4df-dev (only related to C4DF), create a new "helper" branch similar to corp-helper and then make another push with the changes I want. Once that's in sync, I am deleting C4DF-dev, renaming c4df-helper to that and moving on :).

I will test out this process with corp-overview now, since corp-helper was merged into master successfully :D

**Closed** 2016-06-15 01:20 UTC
Labels: Putmalk's Demesne
