### ISSUE TITLE
Some buttons don't appear when using a multiplayer modpack (But the rest of the UI appears to work fine).

### ISSUE THREAD

**Issue by Rand0miz3d** [LoneGazebo/Community-Patch-DLL#6241] opened 2020-02-13 12:21 UTC
_1. Mod version (i.e Date - 2/9): 2-9-4b

_2. Mod list (if using Vox Populi only, leave blank): Multiplayer Mods Workaround

_3. Error description: When playing VP using a multiplayer modpack, the promotion tree, vassal overview, and corporations buttons do not appear. This only happens with the 2-9 versions. I went back to a modpack of an older version (12-20-3) and the buttons appeared as normal. The issue does not occur when launching mods normally. I am using only Vox Populi (eui version) and the required Multiplayer Mods Workaround, obviously, and I am following the [CBP wikia modpack guide](https://civ-5-cbp.fandom.com/wiki/Creating_a_Modpack) exactly, as I have always done.

_4. Steps to reproduce (optional): Create a multiplayer modpack with Vox Populi 2-9-x

---------------------------
Supporting information:

1. Log files: (Don't know if my logs are relevant at all in this scenario, but here they are)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4198134/Logs.zip)

4. Screenshots (optional):
![20200211175236_1](https://user-images.githubusercontent.com/59127824/74433370-2e5a9b80-4e58-11ea-98a0-4c43417c9632.jpg)
---------------------------
I could also provide my modpack folders if needed, but they are too big to upload here directly.

I don't know if modpacks are supported here or not, since it doesn't seem like many people use them. Anyway I'm making this report just in case anyone feels like taking a look. Cheers.

**Comment by HeathcliffWarriors** [comment] 2020-02-13 18:07
If I remember correctly, Gazebo does not have the equipment to debug multiplayer. Not sure if that's still the case. @LoneGazebo ?

**Comment by Rand0miz3d** [comment] 2020-02-13 18:54
I'm not actually playing multiplayer, if that makes a difference. I just use a modpack in single player to reduce loading screens.

**Comment by MoiMagnus** [comment] 2020-02-13 22:18
I can confirm with my newest modpack (with just VP and EUI), the top panel is missing some features.

**Comment by kdm2k6** [comment] 2020-02-13 23:09
I was wondering if I had done something wrong. I have created a number of basic VP modpacks; however, some of the UI buttons (like corporations ...) on the top right corner seem not to appear (for this version). The archer range is 1 and I start with a pathfinder and warrior, however, so other parts of the mod look good.

**Comment by Adonis-VII** [comment] 2020-02-17 09:31
I am using the non-EUI version and I can confirm issues with this version of the mod. In the Modpack Non-EUI of 2-9-4b both the Corporations & Monopolies and the Events buttons are non responsive. This hasn't been an issue in the past 3 years.

**Comment by Cat-du-Fromage** [comment] 2020-02-17 11:41
try evertyhing but it won't work. I hope this is not the end of multiplayer..

**Comment by MoiMagnus** [comment] 2020-02-17 11:47
Peoples are also reporting so gamebreaking bugs when using a modpack: after 50-60 turns, an empty event open and nothing get you out of it (I don't have more info on that). So my guess is that it's the Events that are broken, and every tab which is loaded after the even tab doesn't work either.

**Comment by Cat-du-Fromage** [comment] 2020-02-17 12:05
i actually play without event and i reported several bug with the 1-11 version where all custom bonus civ goes wild, for exemple, ethiopia could choose meiji's unique corporation, tojo could do his courthouse replacement in non-conquered cities. and desync became far more frequent and longer.

**Comment by JanSobus** [comment] 2020-02-18 03:01
Can confirm this as well. Created modpack, could play fine but icons in hte top panel were missing - even InfoAddict and corporations. I play with events enabled option (for Unique City States), but otherwise with events off (no good/bad/neutral/trade/civspecific events) so no problems with empty ones ruining the game. Turn 200 now.

**Comment by azum4roll** [comment] 2020-02-19 07:44
I'm guessing one of the xml/sql files in one of the mods is broken so everything after isn't considered by the MPMPM.

**Comment by LoneGazebo** [comment] 2020-02-19 14:51
I'd need logs from latest to confirm.

**Comment by Cat-du-Fromage** [comment] 2020-02-19 15:12
Here, i just try today with the last version
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4225780/Logs.zip)

**Comment by Cat-du-Fromage** [comment] 2020-02-20 15:18
i got this weird folder i never saw before maybe it is related? 
![image](https://user-images.githubusercontent.com/46396184/74948479-ad257a80-53fc-11ea-87e8-2d23aa4e9f9e.png)

**Comment by LoneGazebo** [comment] 2020-02-20 15:56
not sure- with no log errors and no XML errors, nearly impossible to diagnose.

**Comment by LoneGazebo** [comment] 2020-02-20 15:56
If someone can post their modpack using the latest, I'll try it out.

**Comment by Cat-du-Fromage** [comment] 2020-02-20 16:26
Here, I hope you will find the issue and revive the multiplayer on the beta version^^
https://drive.google.com/file/d/1gpgNluyT8ZXJDfOCQgXukbW8Ye4o3_1k/view?usp=sharing

**Comment by Cat-du-Fromage** [comment] 2020-02-27 18:05
i know you have a lot of other issue to solve but did you find something about the MPMP^^'?

**Comment by LoneGazebo** [comment] 2020-03-01 06:18
aha, got it. I'd added an InGame.lua file update to the CoreLua of the CP (adds distance ring when choosing a scan action for airplanes). Apparently, this causes Problem 13b on the modspack page: https://forums.civfanatics.com/threads/mpmpm-multiplayer-mod-dlc-hack-updated.533238/



![image](https://user-images.githubusercontent.com/7849458/75620738-1bcbac00-5b52-11ea-87a5-c2e065d4e699.png)

[InGame.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4271426/InGame.zip)

To fix, download that file, drop into /UI folder of modspack, and DELETE the InGame.lua from DLC\MP_MODSPACK\Mods\(1) Community Patch (v 94)\Core Files\CoreLua

**Comment by LoneGazebo** [comment] 2020-03-01 06:19
Someone needs to update the MP maker wiki for VP with this info, it's a simple step.

**Comment by MoiMagnus** [comment] 2020-03-01 09:24
Is it something that can be dealt through the "(6x) Compatibility files" as for CityView.lua, (which is also under problem 13b), hence only a temporary fix for this version, or is it a permanent step to add to making modpacks?

**Comment by LoneGazebo** [comment] 2020-03-01 15:51
I'm not 100% sure, we'd need to experiment.

**Comment by LoneGazebo** [comment] 2020-03-01 15:52
I think it's a more pressing issue because of the content added to the end of the file - there's a set of lines added to the end of ingame.lua that directly enables the extra lua that loads the corporation lua etc.

**Closed** 2020-03-02 00:53 UTC
Labels: Fixed for upcoming version, SLAIN LIKE THE HYDRA

**Comment by JanSobus** [comment] 2020-03-02 13:46
I tried this lua swap today with the newest version and while it fixes some of the problems, it's still not a complete method - icons from smaller mods like wonder planner are still missing

**Comment by LoneGazebo** [comment] 2020-03-02 16:33
@JanSobus you have to follow the instructions directly for problem 13b.

**Comment by Rand0miz3d** [comment] 2020-03-08 13:28
I have updated the wiki. One question: will the InGame.lua replacement work with every future version, or will it need to be updated?

**Comment by whatsdown44** [comment] 2021-04-16 15:14
Hi, I'm trying to make modpack for new version 16-4, seems to be broken again, the fix not working, all UI is messed now too,

**Comment by bukowa** [comment] 2022-01-07 16:06
While creating modpack with VP 1.3.4 (which is the latest)  it was enough to just delete `DLC\MP_MODSPACK\Mods(1) Community Patch (v 94)\Core Files\CoreLua\InGame.lua` to make UI work again. But i still start with a warrior
![5ab681223bc8fc196728c04293958d01](https://user-images.githubusercontent.com/38087302/148571426-3f5c4047-53ed-4b12-aeab-237c2794af2e.jpg)
 
 13b in forum thread does not state anything about deleting old file (LoneGazebo solution mentions this)

**Comment by azum4roll** [comment] 2022-01-08 08:48
Well I already updated the wiki months ago.
