### ISSUE TITLE
CTD 

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#1759] opened 2016-05-08 10:48 UTC
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

4/23 with the autoinstaller

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 

crash
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/253864/CvMiniDump.zip)

4. Steps to reproduce:

play a turn
[AutoSave_0119 AD-0100.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/253865/AutoSave_0119.AD-0100.zip)

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by ErikSteiner** [comment] 2016-05-08 12:17
Strange thing is, since I activated logging I never experienced any CTDs or infinite turn processings.. Good to see that there are others that have the same issue.

**Comment by ilteroi** [comment] 2016-05-08 15:10
that's a typical sign of a thread safety problem. logging changes the timing. i think i found the root cause, should be fixed

**Comment by AnastaseAlex** [comment] 2016-05-10 07:30
So should I stop posting crash dumps? I have been unable to finish a game or even reach modern in some time.

**Comment by ilteroi** [comment] 2016-05-10 10:19
well, can you try this dll

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/256824/CvGameCore_Expansion2.zip)

and report back? unfortunately it's not savegame compatible. but it has a lot of goodies inside :)

**Comment by ErikSteiner** [comment] 2016-05-10 10:39
Hey ilteroi, how will enabled logging affect the testing environment of the new dll? Should we disable logging first and have a look at crashes and infinite turns then? What would you suggest?

**Comment by ilteroi** [comment] 2016-05-10 13:31
it should work fine both with logging and without (in the 4/23 beta environment).

logging is important for diagnosing a lot of other issues, so it recommend having it active all the time, just in case something happens.

**Comment by ErikSteiner** [comment] 2016-05-10 13:46
Yes you are right. I ask it because after I told you about my experience with logging enabled and having no CTDs since then, I wonder of what we will get then. I mean there is no difference in getting no CTDs or infinite turns by activating logging, or on the other hand having thia issue fixed. As long as you can see the difference I am totally fine with it. To the dll that was released for a while, I never were able to reproduce any issues while having logging and validate..whatever is enabled. I played three games for 50 turns..

**Closed** 2016-05-10 23:22 UTC
Labels: CTD
