### ISSUE TITLE
don't settle near me notification still broken

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1579] opened 2016-04-11 20:51 UTC
i settled neapolis and the indians complained

![image](https://cloud.githubusercontent.com/assets/1358966/14442017/e3235994-0037-11e6-834f-a1dc81191b05.png)

**Comment by LoneGazebo** [comment] 2016-04-11 20:55
Complained about you settling, or complained that you broke the promise? The former isn't impossible – if pataliputra was settled after antium/cumae, but before neapolis, the AI won't refresh its CoM v. your CoM until you settle your next city.

**Comment by ilteroi** [comment] 2016-04-11 21:10
complained about settling - i don't think they should do it, however logical the explanation.

**Comment by LoneGazebo** [comment] 2016-04-11 21:14
Why? It is still reasonably close to Pataliputra, and a human player would very much like that spot (Neapolis) in order to have a coast-to-coast empire. I just don't see how that's unreasonable.

**Comment by ilteroi** [comment] 2016-04-11 21:26
then i guess we have different points of view here ... if they settle 5 plots from one of my cities, they shouldn't cry about a city that is 10 plots away.

**Comment by LoneGazebo** [comment] 2016-04-11 21:28
Ah, so the issue isn't so much your settlement, as it is the fact that they settled closer?

**Comment by ilteroi** [comment] 2016-04-11 22:00
correct. although i would even go further and claim that the history of who settled where previously should be irrelevant. only the inter-empire distance should count and that did not change with the new city

**Comment by LoneGazebo** [comment] 2016-04-11 22:08
That's the way it works, technically, but since India settled close to you it wasn't allowed to 'complain' about your further settling until you settled something. Previously India could have complained after being the party to cause the border conflict!

**Comment by LoneGazebo** [comment] 2016-04-12 02:08
It isn't broken, so I'm closing, but we may need to fine-tune it.

**Closed by LoneGazebo** 2016-04-12 02:08 UTC
