### ISSUE TITLE
Upgraded unit promotion errors.

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2238] opened 2016-07-29 03:40 UTC
Bug Report Template

Mod Version (i.e Date - (4/23b)):
July 27th

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
UnitPanel icon errors
Savegame: [AutoSave_0080 BC-0875.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/389836/AutoSave_0080.BC-0875.zip)
Lua log: [Lua.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/389839/Lua.txt)
Screenshot with the first three promotions options:
![comp-bowman-promotion-error](https://cloud.githubusercontent.com/assets/3291695/17237067/728cf122-5591-11e6-87b3-37ffa2246212.jpg)

3. Steps to reproduce:
This is a Composite bowman that was upgraded via a goody hut so the actual tech for it hasn't been researched yet.

4. Additional information:
Logs seem to indicate an error in finding the correct icon in the atlas:

> [14764.078] UnitPanel: IconHookup error - icon index:	57	icon size:	45	atlas:	ABILITY_ATLAS	image control:	UnitActionIcon
[14764.187] UnitPanel: IconHookup error - icon index:	57	icon size:	45	atlas:	ABILITY_ATLAS	image control:	UnitActionIcon

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment] 2016-07-29 05:28
That's odd. Getting any database errors?

**Comment by Iamblichos** [comment] 2016-07-29 12:53
This is not a database error. PROMOTION_ONLY_DEFENSIVE gets dropped on upgrade. Take an archer. Notice it'll have the promotion in the unit panel. Get Composite Bowman tech and upgrade it. Promotion gets dropped. Something in your new promotion code in CvUnit.cpp I bet.

**Comment by Iamblichos** [comment] 2016-07-29 14:36
I think I found the problem.

#if defined(MOD_BALANCE_CORE_JFD)
```
CvUnit* CvPlayer::initUnit(UnitTypes eUnit, int iX, int iY, UnitAITypes eUnitAI, DirectionTypes eFacingDirection, bool bNoMove, bool bSetupGraphical, int iMapLayer /* = 0 */, int iNumGoodyHutsPopped, ContractTypes eContract)
#else
CvUnit* CvPlayer::initUnit(UnitTypes eUnit, int iX, int iY, UnitAITypes eUnitAI, DirectionTypes eFacingDirection, bool bNoMove, bool bSetupGraphical, int iMapLayer /* = 0 */, int iNumGoodyHutsPopped
#endif
```
Need to close off your parentheses on the #else.

**Comment by Iamblichos** [comment] 2016-07-29 15:24
Doing a new build now. Will confirm here if it is fixed.

**Comment by LoneGazebo** [comment] 2016-07-29 15:26
Eh, I typed a message, didn't post apparently. Anyways that isn't the issue. The issue is in ::convert.

**Comment by Iamblichos** [comment] 2016-07-29 15:27
I was going to look at that one next if this didn't work.

**Comment by Iamblichos** [comment] 2016-07-29 15:33
```
// Old unit has the promotion
bGivePromotion = false;
```
That line seems suspect.

**Comment by LoneGazebo** [comment] 2016-07-29 15:38
Mm yeah. Prolly that.

**Comment by LoneGazebo** [comment] 2016-07-29 15:40
Try this: 

			// Old unit has the promotion
			if(pUnit->isHasPromotion(ePromotion))
			{
				if(pkPromotionInfo->IsLostWithUpgrade())
				{
#if defined(MOD_BALANCE_CORE)
					if(ePromotion == (PromotionTypes)GC.getPROMOTION_OCEAN_IMPASSABLE() || ePromotion == (PromotionTypes)GC.getPROMOTION_OCEAN_IMPASSABLE_UNTIL_ASTRONOMY())
					{
						//Can't embark yet, or the unit should auto get it?
						if(!GET_PLAYER(getOwner()).GetPlayerTraits()->IsEmbarkedAllWater() && !GET_TEAM(GET_PLAYER(getOwner()).getTeam()).canEmbarkAllWaterPassage() && getUnitInfo().GetFreePromotions(ePromotion))
						{
							bGivePromotion = true;
						}
					}
					else
					{
#endif
					bGivePromotion = false;
#if defined(MOD_BALANCE_CORE)
					}
#endif
				}
#if defined(MOD_BALANCE_CORE)
				else
				{
					bGivePromotion = true;
				}
#endif
			}

**Comment by Iamblichos** [comment] 2016-07-29 15:40
Testing now...let you know

**Comment by Iamblichos** [comment] 2016-07-29 15:57
Your code above didn't work. Archer still drops the cannot melee attack promotion. Gonna try something else in there.

**Comment by Iamblichos** [comment] 2016-07-29 16:13
Went back to the old code for convert and it works fine:

```
void CvUnit::convert(CvUnit* pUnit, bool bIsUpgrade)
{
	VALIDATE_OBJECT
	IDInfo* pUnitNode;
	CvUnit* pTransportUnit;
	CvUnit* pLoopUnit;
	CvPlot* pPlot;

	pPlot = plot();
#if defined(MOD_BALANCE_CORE)
	int iLostPromotions = 0;
	bool bFree = false;
#endif
	// Transfer Promotions over
	for(int iI = 0; iI < GC.getNumPromotionInfos(); iI++)
	{
		const PromotionTypes ePromotion = static_cast<PromotionTypes>(iI);
		CvPromotionEntry* pkPromotionInfo = GC.getPromotionInfo(ePromotion);
		if(pkPromotionInfo)
		{
			bool bGivePromotion = false;

#if defined(MOD_PROMOTIONS_DEEP_WATER_EMBARKATION)
			if (pkPromotionInfo->IsEmbarkedDeepWater()) {
				// Deep water promotions are handled as special cases of the general embark promotion
				continue;
			}
#endif
			// Old unit has the promotion
			if(pUnit->isHasPromotion(ePromotion) && !pkPromotionInfo->IsLostWithUpgrade())
			{
				bGivePromotion = true;
			}

			// New unit gets promotion for free (as per XML)
			else if(getUnitInfo().GetFreePromotions(ePromotion) && (!bIsUpgrade || !pkPromotionInfo->IsNotWithUpgrade()))
			{
				bGivePromotion = true;
#if defined(MOD_BALANCE_CORE)
				bFree = true;
				if((ePromotion == (PromotionTypes)GC.getPROMOTION_OCEAN_IMPASSABLE() || ePromotion == (PromotionTypes)GC.getPROMOTION_OCEAN_IMPASSABLE_UNTIL_ASTRONOMY()) && (GET_PLAYER(getOwner()).GetPlayerTraits()->IsEmbarkedAllWater() || GET_TEAM(GET_PLAYER(getOwner()).getTeam()).canEmbarkAllWaterPassage()))
				{
					bGivePromotion = false;
					bFree = false;
				}
#endif
			}

			// if we get this due to a policy or wonder
			else if(GET_PLAYER(getOwner()).IsFreePromotion(ePromotion) && (
						::IsPromotionValidForUnitCombatType(ePromotion, getUnitType()) || ::IsPromotionValidForCivilianUnitType(ePromotion, getUnitType())))
			{
				bGivePromotion = true;
#if defined(MOD_BALANCE_CORE)
				bFree = true;
				if((ePromotion == (PromotionTypes)GC.getPROMOTION_OCEAN_IMPASSABLE() || ePromotion == (PromotionTypes)GC.getPROMOTION_OCEAN_IMPASSABLE_UNTIL_ASTRONOMY()) && (GET_PLAYER(getOwner()).GetPlayerTraits()->IsEmbarkedAllWater() || GET_TEAM(GET_PLAYER(getOwner()).getTeam()).canEmbarkAllWaterPassage()))
				{
					bGivePromotion = false;
					bFree = false;
				}
#endif
			}
#if defined(MOD_BALANCE_CORE)
			if(pUnit->getUnitCombatType() != getUnitCombatType())
			{
				bool bRanged = false;
				if((pkPromotionInfo->GetRangedAttackModifier() > 0) || (pkPromotionInfo->GetRangeChange() > 0) || (pkPromotionInfo->GetRangedAttackModifier() > 0) || (pkPromotionInfo->IsRangeAttackIgnoreLOS()) || (pkPromotionInfo->GetOpenRangedAttackMod() > 0) || (pkPromotionInfo->GetRoughRangedAttackMod() > 0) || (pkPromotionInfo->GetExtraAttacks() > 0))
				{
					bRanged = true;
				}
				//If we're losing standard promotions because of a combatclass change, let's replace with some experience.
				if(!isRanged() && pUnit->HasPromotion(ePromotion) && pUnit->isRanged() && bRanged && !bFree)
				{
					iLostPromotions++;
					bGivePromotion = false;
				}
				//Naval Misfire Promotion Catch (sorry for hardcode)
				else if(!isRanged() && pUnit->HasPromotion(ePromotion) && pUnit->isRanged() && (pkPromotionInfo->GetDomainModifierPercent(DOMAIN_SEA) < 0) && (getDomainType() == DOMAIN_LAND))
				{
					iLostPromotions++;
					bGivePromotion = false;
				}
			}
#endif

			setHasPromotion(ePromotion, bGivePromotion);
#if defined(MOD_PROMOTIONS_DEEP_WATER_EMBARKATION)
			if (MOD_PROMOTIONS_DEEP_WATER_EMBARKATION && bGivePromotion && pkPromotionInfo->IsAllowsEmbarkation() && IsHoveringUnit())
			{
				setHasPromotion(GET_PLAYER(getOwner()).GetDeepWaterEmbarkationPromotion(), true);
			}
#endif
		}
	}
#if defined(MOD_BALANCE_CORE)
	//20 xp per lost 'good' promotion (plus level).
	if(iLostPromotions > 0)
	{
		int iLevel = pUnit->getLevel();
		if(iLevel <= 0)
		{
			iLevel = 1;
		}
#if defined(MOD_UNITS_XP_TIMES_100)
		changeExperienceTimes100(20 * iLostPromotions * iLevel * 100);
#else
		changeExperience(20 * iLostPromotions * iLevel);
#endif
	}
#endif
	setGameTurnCreated(pUnit->getGameTurnCreated());
	setLastMoveTurn(pUnit->getLastMoveTurn());
#if defined(MOD_UNITS_MAX_HP)
	// Don't kill the unit if upgrading from a unit with more base hit points!!!
	setDamage(min(pUnit->getDamage(), GetMaxHitPoints()-1));
#else
	setDamage(pUnit->getDamage());
#endif
	setMoves(pUnit->getMoves());
	setEmbarked(pUnit->isEmbarked());
	setFacingDirection(pUnit->getFacingDirection(false));
	SetBeenPromotedFromGoody(pUnit->IsHasBeenPromotedFromGoody());
	SetTourismBlastStrength(pUnit->GetTourismBlastStrength());
#if defined(MOD_BALANCE_CORE)
	SetScienceBlastStrength(pUnit->getDiscoverAmount());
	SetCultureBlastStrength(pUnit->getGivePoliciesCulture());
#endif
	if (pUnit->getUnitInfo().GetNumExoticGoods() > 0)
	{
		setNumExoticGoods(pUnit->getNumExoticGoods());
	}
#if defined(MOD_BALANCE_CORE)
	if(pUnit->getUnitCombatType() != getUnitCombatType() && (iLostPromotions > 0))
	{
		setLevel(1);
	}
	else
	{
#endif
	setLevel(pUnit->getLevel());
#if defined(MOD_BALANCE_CORE)
	}
#endif
	int iOldModifier = std::max(1, 100 + GET_PLAYER(pUnit->getOwner()).getLevelExperienceModifier());
	int iOurModifier = std::max(1, 100 + GET_PLAYER(getOwner()).getLevelExperienceModifier());
#if defined(MOD_UNITS_XP_TIMES_100)
	setExperienceTimes100(std::max(0, (pUnit->getExperienceTimes100() * iOurModifier) / iOldModifier));
#else
	setExperience(std::max(0, (pUnit->getExperience() * iOurModifier) / iOldModifier));
#endif

	setName(pUnit->getNameNoDesc());
	setLeaderUnitType(pUnit->getLeaderUnitType());
	ChangeNumGoodyHutsPopped(pUnit->GetNumGoodyHutsPopped());

	pTransportUnit = pUnit->getTransportUnit();

	if(pTransportUnit != NULL)
	{
		pUnit->setTransportUnit(NULL);
		setTransportUnit(pTransportUnit);
	}

	pUnitNode = pPlot->headUnitNode();

	while(pUnitNode != NULL)
	{
		pLoopUnit = ::getUnit(*pUnitNode);
		pUnitNode = pPlot->nextUnitNode(pUnitNode);

		if(pLoopUnit && pLoopUnit->getTransportUnit() == pUnit)
		{
			pLoopUnit->setTransportUnit(this);
		}
	}

	pUnit->kill(true);
}
```

**Comment by Iamblichos** [comment] 2016-07-29 16:14
Not sure what you were trying to do in there with making some added if's for Polynesia....may want to review it.

**Comment by LoneGazebo** [comment] 2016-07-29 16:32
Game was not designed for ships to transfer 'ocean impassable' traits on upgrade, as there were no pre-astronomy upgrades for ships. We've changed that, and convert needs to account for it. I'll give it another look later.

**Comment by biship** [comment] 2016-07-30 00:36
Is this also causing scouting 1 and 2 being available on first scout promotion? As well as the ability to upgrade to <red triangle> no melee attack?

**Comment by Iamblichos** [comment] 2016-07-31 02:32
G, mind syncing up your changes so I can see what you did?

**Comment by biship** [comment] 2016-07-31 16:07
@LoneGazebo plz :)

**Comment by LoneGazebo** [comment] 2016-08-01 04:58
Sorry, I've been out of town. Code uploaded now.

**Comment by Iamblichos** [comment] 2016-08-01 14:24
@LoneGazebo, just curious, did you have an issue prior to implementing the change to ::convert? The reason I ask as I've had a bireme that upgrades to a trireme (both ocean impassible) in my mod for well over a year now, and have not had an issue. Seemed like the promotion got transferred correctly.

**Comment by LoneGazebo** [comment] 2016-08-01 16:10
Yes. I ignored the issue but decided to solve it recently. All works as intended now.

**Closed** 2016-08-03 02:10 UTC
Labels: Fixed for upcoming version, Gazebo is on the case
