### ISSUE TITLE
City State City Capture Quest bugged

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#8850] opened 2022-05-02 12:57 UTC
Version 2.1.1

I keep getting quests to capture a city with no city specified. The quest then cancels next turn.

Game is OCC so might be to do with that?

**Comment by maarten99** [comment] 2022-05-02 20:24
I have had this same bug in the last 2 years, not always/ very randomly when it occurred. But when I did get it in a game, the quest never gave me a valid city target.
Clearing cache seems to fix this bug (before starting new game)

**Comment by maarten99** [comment] 2022-06-13 11:39
I started an OCC game while clearing cache first, but I still had the bug. That might have just been my superstition, I also believe it to be an OCC bug now. Here is how it looks in game:

![image](https://user-images.githubusercontent.com/24713571/173345628-b32ba0a4-e52d-42e8-97f1-f467af795730.png)

**Comment by axatin** [comment] 2022-07-21 22:57
It is an OCC bug. It was intended that this quest is not assigned to human players at all if they can't acquire any cities.

**Comment by maarten99** [comment] 2022-07-21 23:03
That would be an awful restriction to OCC, imo the quest should be changed to Capture instead of Acquire the city.

**Comment by axatin** [comment] 2022-07-22 10:31
The "Acquite City" quest is not fulfillable in OCC as captured cities are instantly destroyed, so it has to be excluded. When the bug is fixed, the city state will always give another quest to the player instead, so I don't see it as a big restriction.

The same bug can also happen with the quest "Liberate another City-State". I think this quest should be available in OCC since city liberation is possible.

**Comment by axatin** [comment] 2022-07-22 11:17
I don't have any experience with OCC games myself. I can imagine that when you have only one city it's very difficult to capture other cities, and maybe that's why the quest to liberate cities was also excluded? What do you think, should the quest be offered in OCC games?

**Comment by maarten99** [comment] 2022-07-22 12:50
The quest should definitely be offered to OCC players.

While it is true that capturing cities is more difficult when you're constrained by a low supply cap like in OCC, it is the most powerful quest reward and not offering it to OCC players would be an unreasonable nerf.

Even though you are disadvantaged in OCC, the instant raze is also very useful for civs like France, because they have bonuses on city capture. These bonuses together with instant raze can even be used to win the game more quickly than in non-OCC (I won a culture victory on turn ~240 with France OCC like this)

**Comment by axatin** [comment] 2022-07-23 19:59
okay, I'm working on it. I will create a new quest for OCC games only with the goal to destroy a city and with the same rewards as the other quest.

**Comment by LessRekkless** [comment] 2022-07-25 04:49
Go for it. Seems relatively easy to lock to OCC inside `IsValidQuestForPlayer()`. Also, stop OCC from getting the quest in the same function.

I would use the word conquer instead of destroy.

**Closed** 2022-08-11 09:09 UTC
