### ISSUE TITLE
Game breaks when AI declares war on player

### ISSUE THREAD

**Issue by TyborPL** [LoneGazebo/Community-Patch-DLL#5160] opened 2019-02-08 11:25 UTC
_1. Mod version : 1-29-2

_2. Mod list (if using Vox Populi only, leave blank): Custom Advanced Setup, 

_3. Error description: When AI declares war on me, sometimes when I try to click "You will pay me..." the button is inactive and I click "Very well.." then game goes haywire: Remaining "back" dialog button from the discussion, flickering and missing textures, when try to save and reload get CTD. Save is corrupted and has only ~ 15kB

_4. Steps to reproduce (optional): Cannot reproduce. When reloading earlier autosave it is all normal even if AI DOW me the same way.

**Comment by supermerill** [comment] 2019-02-08 16:01
duplicate of #5097

**Closed by supermerill** 2019-02-08 16:01 UTC
