### ISSUE TITLE
Problem locking city tiles

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#6692] opened 2020-06-20 08:35 UTC
_1. Mod version (i.e Date - 4/17):_

6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Several cases described in the thread, starting here:

https://forums.civfanatics.com/threads/new-official-version-june-19th-6-19.659579/#post-15806488

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Cokolwiek-Unni** [comment] 2020-06-20 21:13
Yeah, I can confirm that the bug persist in both DirectX 9 and 11 versions, I have only Vox Populi without any other mods
For some people the governor reassigns the tiles each turn or on the birth of the new citizen, for some he doesn't
I think that maybe you can look up laborers as a specialists? Some people reported that they can lock if they hadn't left citizen as laborers.

**Comment by InkAxis** [comment] 2020-06-21 18:16
I have this issue as well. Here's the mods I'm using, none other than VP:
![image](https://user-images.githubusercontent.com/40811935/85231880-a6f5d980-b3af-11ea-97a7-bff51803f37c.png)

Here you can see my city view, I took my first citizen and made them a labourer:
![image](https://user-images.githubusercontent.com/40811935/85231914-fe944500-b3af-11ea-8bb2-ce00c13f627c.png)

And then here's what happens when I click  on the tile:
![image](https://user-images.githubusercontent.com/40811935/85231925-2388b800-b3b0-11ea-959e-6deaccbc01c7.png)

Instead of locking the tile, it just sets the citizen there, so the governor can override it. So it's difficult to select which tiles I want to work. This happens every turn, in every city, in every game. It always happens, no matter what.

**Comment by ilteroi** [comment] 2020-06-21 19:02
can confirm, something is wrong

i was able to lock some tiles. but each time i locked a tile, another tile flipped to non-working state.

then after the forth tile or so it got all weird, i can only flip between working/nonworking now, even on the ones i was able to lock before.

observation: 
* i can lock a non-worked tile as long as there is no laborer in the city
* i can not lock a worked tile, because clicking it creates a laborer

**Comment by RecursiveVision** [comment] 2020-06-21 20:58
> by the way. looking at it tells me that clicking the city plot itself restores the default assignment. never knew that ...

Been the case since vanilla, it says so if you mouse over the city plot.

**Comment by LoneGazebo** [comment] 2020-06-21 22:46
@ilteroi I don’t recall touching that section at all, didn’t make any changes there. Must’ve been an accidental change? Perhaps a merge from someone else and I messed up a manual merge? Not sure.

**Closed** 2020-08-06 17:21 UTC
Labels: Already fixed
