### ISSUE TITLE
Can't perform ranged attack on embarked unit with right mouse button

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6713] opened 2020-06-23 20:45 UTC
_1. Mod version (i.e Date - 4/17):_ 6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

- Subs ignore borders http://www.picknmixmods.com/mods/CivV/Units/Subs Ignore Borders.html
- UI - religion spread (Vox Populi) https://forums.civfanatics.com/threads/ui-religion-spread-vox-populi.627375/
- UI - notify exit resistance http://www.picknmixmods.com/mods/CivV/UI/Notify Exit Resistance.html
- Quick Turns https://steamcommunity.com/sharedfiles/filedetails/?id=220250184
- Promotion flags EUI (for VP) version 3
- UI - wonder planner http://www.picknmixmods.com/mods/CivV/UI/Wonder Planner.html

_3. Error description:_ 

My ranged units cannot attack enemy's embarked units with usual right mouse click. Need to press the unit menu "Attack" button.

**Comment by Mcantona** [comment] 2020-06-24 20:28
I am experiencing the same issue (with the not hotfixed version)

1. Mod version: 6-19

2. Mod list (if using Vox Populi only, leave blank):

- Promotion flags EUI (for VP) version 3
- UI Promotion Tree for VP (V .22)
- City States Leaders for VP (V.74)
- Unique City States (.6)

**Comment by ilteroi** [comment] 2020-06-26 05:48
duplicate of #6716

**Closed** 2020-06-26 05:48 UTC
