### ISSUE TITLE
5/19 Tile not workable after pillaging.

### ISSUE THREAD

**Issue by Palaki** [LoneGazebo/Community-Patch-DLL#7896] opened 2021-05-21 19:18 UTC
_1. Mod version (i.e Date - 4/14):_
5-19

_2. Mod list (if using Vox Populi only, leave blank):_
VP + EUI
Community Events
Enhanced Air Warfare
More Unique Components
More Wonders
Promotion Overhaul ( Text)
Trade Opportunities
Wonder Planner
Calypsos Colored Religions Icons / Extended
Enhanced Naval Warfare
JFD´s Cultural Diversity
Quick Turns
Really Advanced Setup
Unique City States
ZNW Symbolic Ideology Tenets
Filters in Trade Route overview
Show XP in military overview

so much typing... :D

_3. Error description:_ 

After Isabella pillaged the farm, i could not use the tile anymore.
![Screenshot_2](https://user-images.githubusercontent.com/60859061/119187678-f3dba780-ba79-11eb-9483-762a524ba7d2.png)

**Comment by LoneGazebo** [comment] 2021-05-21 19:41
Dupe of #7890

See DLL I posted there

**Closed** 2021-05-21 19:42 UTC
Labels: Already fixed
